import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const substances = [
  // ── CLASSE 1 — Matières explosives ──────────────────────
  { unNumber: '0336', nameFR: 'Feux d\'artifice', nameEN: 'Fireworks', casNumber: null, tmdClass: '1.4G', tmdClassLabel: 'Matières explosives', packingGroup: null, simdutClass: 'E', simdutLabel: 'Matière explosive', placardCode: '1', keywords: ['feux artifice', 'pyrotechnie'], isCommon: false },
  { unNumber: '0332', nameFR: 'Émulsions explosives', nameEN: 'Emulsion explosives', casNumber: null, tmdClass: '1.5D', tmdClassLabel: 'Matières explosives', packingGroup: null, simdutClass: 'E', simdutLabel: 'Matière explosive', placardCode: '1', keywords: ['explosif', 'emulsion'], isCommon: false },

  // ── CLASSE 2.1 — Gaz inflammables ───────────────────────
  { unNumber: '1011', nameFR: 'Butane', nameEN: 'Butane', casNumber: '106-97-8', tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['butane', 'gaz', 'propane'], isCommon: true },
  { unNumber: '1978', nameFR: 'Propane', nameEN: 'Propane', casNumber: '74-98-6', tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['propane', 'gaz', 'bbq', 'chauffage'], isCommon: true },
  { unNumber: '1965', nameFR: 'Hydrocarbures gazeux en mélange liquéfié (GPL)', nameEN: 'Hydrocarbon gas mixture liquefied (LPG)', casNumber: null, tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['gpl', 'propane', 'butane', 'gaz liquéfié'], isCommon: true },
  { unNumber: '1049', nameFR: 'Hydrogène comprimé', nameEN: 'Hydrogen compressed', casNumber: '1333-74-0', tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['hydrogène', 'hydrogen', 'gaz'], isCommon: false },
  { unNumber: '1954', nameFR: 'Gaz inflammable comprimé, N.S.A.', nameEN: 'Compressed gas, flammable, N.O.S.', casNumber: null, tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['gaz inflammable', 'comprimé'], isCommon: false },
  { unNumber: '1075', nameFR: 'Gaz de pétrole liquéfiés', nameEN: 'Liquefied petroleum gas', casNumber: null, tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['gpl', 'propane', 'butane', 'pétrole liquéfié'], isCommon: true },
  { unNumber: '1001', nameFR: 'Acétylène dissous', nameEN: 'Acetylene dissolved', casNumber: '74-86-2', tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['acétylène', 'soudage', 'chalumeau'], isCommon: true },
  { unNumber: '1971', nameFR: 'Méthane comprimé', nameEN: 'Methane compressed', casNumber: '74-82-8', tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz comprimé, gaz inflammable', placardCode: '2_1', keywords: ['méthane', 'gaz naturel'], isCommon: true },

  // ── CLASSE 2.2 — Gaz non inflammables, non toxiques ─────
  { unNumber: '1013', nameFR: 'Dioxyde de carbone', nameEN: 'Carbon dioxide', casNumber: '124-38-9', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['co2', 'dioxyde carbone', 'gaz carbonique'], isCommon: true },
  { unNumber: '1977', nameFR: 'Azote liquide réfrigéré', nameEN: 'Nitrogen refrigerated liquid', casNumber: '7727-37-9', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['azote', 'nitrogen', 'azote liquide'], isCommon: true },
  { unNumber: '1072', nameFR: 'Oxygène comprimé', nameEN: 'Oxygen compressed', casNumber: '7782-44-7', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['oxygène', 'oxygen', 'gaz médical'], isCommon: true },
  { unNumber: '1006', nameFR: 'Argon comprimé', nameEN: 'Argon compressed', casNumber: '7440-37-1', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['argon', 'gaz inerte', 'soudage'], isCommon: true },
  { unNumber: '1002', nameFR: 'Air comprimé', nameEN: 'Air compressed', casNumber: null, tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['air comprimé', 'air'], isCommon: true },

  // ── CLASSE 2.3 — Gaz toxiques ───────────────────────────
  { unNumber: '1005', nameFR: 'Ammoniac anhydre', nameEN: 'Ammonia anhydrous', casNumber: '7664-41-7', tmdClass: '2.3', tmdClassLabel: 'Gaz toxiques', packingGroup: null, simdutClass: 'A,D1A,E', simdutLabel: 'Gaz comprimé, matière toxique', placardCode: '2_3', keywords: ['ammoniac', 'ammoniaque', 'NH3', 'réfrigération'], isCommon: true },
  { unNumber: '1017', nameFR: 'Chlore', nameEN: 'Chlorine', casNumber: '7782-50-5', tmdClass: '2.3', tmdClassLabel: 'Gaz toxiques', packingGroup: null, simdutClass: 'A,D1A,E', simdutLabel: 'Gaz comprimé, matière toxique, corrosif', placardCode: '2_3', keywords: ['chlore', 'chlorine', 'piscine', 'désinfection'], isCommon: true },
  { unNumber: '1040', nameFR: 'Oxyde d\'éthylène', nameEN: 'Ethylene oxide', casNumber: '75-21-8', tmdClass: '2.3', tmdClassLabel: 'Gaz toxiques', packingGroup: null, simdutClass: 'A,B1,D1A,E', simdutLabel: 'Gaz comprimé, toxique, inflammable', placardCode: '2_3', keywords: ['oxyde éthylène', 'stérilisation'], isCommon: false },

  // ── CLASSE 3 — Liquides inflammables ────────────────────
  { unNumber: '1202', nameFR: 'Diesel', nameEN: 'Diesel fuel', casNumber: '68334-30-5', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'III', simdutClass: 'B3', simdutLabel: 'Liquide combustible', placardCode: '3', keywords: ['diesel', 'carburant diesel', 'gazole', 'fuel', 'huile diesel'], isCommon: true },
  { unNumber: '1203', nameFR: 'Essence', nameEN: 'Gasoline', casNumber: '86290-81-5', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['essence', 'gasoline', 'super', 'carburant'], isCommon: true },
  { unNumber: '1090', nameFR: 'Acétone', nameEN: 'Acetone', casNumber: '67-64-1', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['acétone', 'solvant', 'décapant'], isCommon: true },
  { unNumber: '1170', nameFR: 'Éthanol', nameEN: 'Ethanol', casNumber: '64-17-5', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['éthanol', 'alcool', 'alcool éthylique', 'ethanol'], isCommon: true },
  { unNumber: '1230', nameFR: 'Méthanol', nameEN: 'Methanol', casNumber: '67-56-1', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2,D1A', simdutLabel: 'Liquide inflammable, toxique', placardCode: '3', keywords: ['méthanol', 'alcool méthylique', 'alcool bois'], isCommon: true },
  { unNumber: '1267', nameFR: 'Pétrole brut', nameEN: 'Petroleum crude oil', casNumber: '8002-05-9', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['pétrole brut', 'crude oil', 'pétrole'], isCommon: false },
  { unNumber: '1263', nameFR: 'Peinture (y compris peinture, laque, émail, colorant, gomme laque, vernis, cirage, encaustique, enduit liquide)', nameEN: 'Paint', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['peinture', 'paint', 'laque', 'vernis', 'solvant'], isCommon: true },
  { unNumber: '1114', nameFR: 'Benzène', nameEN: 'Benzene', casNumber: '71-43-2', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2,D2A', simdutLabel: 'Liquide inflammable, cancérogène', placardCode: '3', keywords: ['benzène', 'benzene', 'solvant aromatique'], isCommon: false },
  { unNumber: '1294', nameFR: 'Toluène', nameEN: 'Toluene', casNumber: '108-88-3', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['toluène', 'toluene', 'solvant'], isCommon: true },
  { unNumber: '1760', nameFR: 'Liquide corrosif, N.S.A.', nameEN: 'Corrosive liquid N.O.S.', casNumber: null, tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'I,II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['corrosif', 'liquide corrosif'], isCommon: false },
  { unNumber: '1993', nameFR: 'Liquide inflammable, N.S.A.', nameEN: 'Flammable liquid N.O.S.', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['liquide inflammable', 'solvant'], isCommon: false },
  { unNumber: '1133', nameFR: 'Adhésifs', nameEN: 'Adhesives', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['adhésif', 'colle', 'adhesive'], isCommon: true },
  { unNumber: '1197', nameFR: 'Extraits aromatiques liquides', nameEN: 'Extracts flavouring liquid', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['extrait', 'arôme', 'parfum'], isCommon: false },
  { unNumber: '1219', nameFR: 'Propanol', nameEN: 'Propanol', casNumber: '71-23-8', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['propanol', 'alcool isopropylique', 'isopropanol'], isCommon: true },
  { unNumber: '1145', nameFR: 'Cyclohexane', nameEN: 'Cyclohexane', casNumber: '110-82-7', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['cyclohexane', 'solvant'], isCommon: false },
  { unNumber: '1128', nameFR: 'Acétate de butyle normal', nameEN: 'n-Butyl acetate', casNumber: '123-86-4', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['acétate butyle', 'solvant peinture'], isCommon: false },
  { unNumber: '1381', nameFR: 'Phosphore blanc ou jaune sec', nameEN: 'Phosphorus white or yellow dry', casNumber: '7723-14-0', tmdClass: '4.2', tmdClassLabel: 'Matières spontanément combustibles', packingGroup: 'I', simdutClass: 'B4,D1A', simdutLabel: 'Matière spontanément combustible', placardCode: '4_2', keywords: ['phosphore', 'blanc', 'jaune'], isCommon: false },

  // ── CLASSE 4.1 — Matières solides inflammables ──────────
  { unNumber: '1325', nameFR: 'Matière organique inflammable solide, N.S.A.', nameEN: 'Flammable solid organic N.O.S.', casNumber: null, tmdClass: '4.1', tmdClassLabel: 'Matières solides inflammables', packingGroup: 'II,III', simdutClass: 'B6', simdutLabel: 'Matière combustible solide', placardCode: '4_1', keywords: ['solide inflammable', 'combustible solide'], isCommon: false },
  { unNumber: '1350', nameFR: 'Soufre', nameEN: 'Sulphur', casNumber: '7704-34-9', tmdClass: '4.1', tmdClassLabel: 'Matières solides inflammables', packingGroup: 'III', simdutClass: 'B6', simdutLabel: 'Matière combustible solide', placardCode: '4_1', keywords: ['soufre', 'sulfur', 'sulphur'], isCommon: true },

  // ── CLASSE 4.2 — Matières spontanément combustibles ─────
  { unNumber: '2014', nameFR: 'Solution de peroxyde d\'hydrogène', nameEN: 'Hydrogen peroxide aqueous solution', casNumber: '7722-84-1', tmdClass: '5.1', tmdClassLabel: 'Matières comburantes', packingGroup: 'I,II', simdutClass: 'C,D1B', simdutLabel: 'Comburant, oxydant', placardCode: '5_1', keywords: ['peroxyde hydrogène', 'eau oxygénée', 'H2O2'], isCommon: true },

  // ── CLASSE 4.3 — Matières hydroréactives ────────────────
  { unNumber: '1428', nameFR: 'Sodium', nameEN: 'Sodium', casNumber: '7440-23-5', tmdClass: '4.3', tmdClassLabel: 'Matières hydroréactives', packingGroup: 'I', simdutClass: 'B3,E', simdutLabel: 'Matière réagissant à l\'eau', placardCode: '4_3', keywords: ['sodium', 'métal alcalin'], isCommon: false },
  { unNumber: '1402', nameFR: 'Carbure de calcium', nameEN: 'Calcium carbide', casNumber: '75-20-7', tmdClass: '4.3', tmdClassLabel: 'Matières hydroréactives', packingGroup: 'I,II', simdutClass: 'B6,E', simdutLabel: 'Matière combustible, réagissant à l\'eau', placardCode: '4_3', keywords: ['carbure calcium', 'acétylène', 'carbure'], isCommon: true },

  // ── CLASSE 5.1 — Matières comburantes ───────────────────
  { unNumber: '1942', nameFR: 'Nitrate d\'ammonium', nameEN: 'Ammonium nitrate', casNumber: '6484-52-2', tmdClass: '5.1', tmdClassLabel: 'Matières comburantes', packingGroup: 'III', simdutClass: 'C,E', simdutLabel: 'Comburant', placardCode: '5_1', keywords: ['nitrate ammonium', 'engrais', 'explosif agricole'], isCommon: true },
  { unNumber: '1072', nameFR: 'Oxygène comprimé', nameEN: 'Oxygen compressed', casNumber: '7782-44-7', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A,C', simdutLabel: 'Gaz comprimé, comburant', placardCode: '2_2', keywords: ['oxygène', 'oxygen'], isCommon: true },
  { unNumber: '1479', nameFR: 'Solide comburant, N.S.A.', nameEN: 'Oxidizing solid N.O.S.', casNumber: null, tmdClass: '5.1', tmdClassLabel: 'Matières comburantes', packingGroup: 'I,II,III', simdutClass: 'C', simdutLabel: 'Comburant, oxydant', placardCode: '5_1', keywords: ['comburant', 'oxydant', 'solide comburant'], isCommon: false },
  { unNumber: '1748', nameFR: 'Hypochlorite de calcium sec', nameEN: 'Calcium hypochlorite dry', casNumber: '7778-54-3', tmdClass: '5.1', tmdClassLabel: 'Matières comburantes', packingGroup: 'II', simdutClass: 'C,E', simdutLabel: 'Comburant, corrosif', placardCode: '5_1', keywords: ['hypochlorite calcium', 'chlore piscine', 'désinfectant'], isCommon: true },

  // ── CLASSE 5.2 — Peroxydes organiques ───────────────────
  { unNumber: '3101', nameFR: 'Peroxyde organique de type B, liquide', nameEN: 'Organic peroxide type B liquid', casNumber: null, tmdClass: '5.2', tmdClassLabel: 'Peroxydes organiques', packingGroup: null, simdutClass: 'C,D1B', simdutLabel: 'Peroxyde organique', placardCode: '5_2', keywords: ['peroxyde organique'], isCommon: false },

  // ── CLASSE 6.1 — Matières toxiques ──────────────────────
  { unNumber: '1593', nameFR: 'Dichlorométhane', nameEN: 'Dichloromethane', casNumber: '75-09-2', tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'III', simdutClass: 'D2B', simdutLabel: 'Matière toxique', placardCode: '6_1', keywords: ['dichlorométhane', 'chlorure de méthylène', 'DCM', 'décapant'], isCommon: true },
  { unNumber: '1654', nameFR: 'Nicotine', nameEN: 'Nicotine', casNumber: '54-11-5', tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'II', simdutClass: 'D1A', simdutLabel: 'Matière très toxique', placardCode: '6_1', keywords: ['nicotine', 'tabac'], isCommon: false },
  { unNumber: '1580', nameFR: 'Chloropicrine', nameEN: 'Chloropicrin', casNumber: '76-06-2', tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'I', simdutClass: 'D1A,E', simdutLabel: 'Matière très toxique, corrosive', placardCode: '6_1', keywords: ['chloropicrine', 'fumigant'], isCommon: false },
  { unNumber: '2810', nameFR: 'Liquide toxique organique, N.S.A.', nameEN: 'Toxic liquid organic N.O.S.', casNumber: null, tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'I,II,III', simdutClass: 'D1A,D1B,D2A', simdutLabel: 'Matière toxique', placardCode: '6_1', keywords: ['toxique', 'liquide toxique'], isCommon: false },
  { unNumber: '2902', nameFR: 'Pesticide liquide toxique, N.S.A.', nameEN: 'Pesticide liquid toxic N.O.S.', casNumber: null, tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'I,II,III', simdutClass: 'D1A,D1B', simdutLabel: 'Matière toxique', placardCode: '6_1', keywords: ['pesticide', 'insecticide', 'herbicide', 'fongicide'], isCommon: true },
  { unNumber: '2588', nameFR: 'Pesticide solide toxique, N.S.A.', nameEN: 'Pesticide solid toxic N.O.S.', casNumber: null, tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'I,II,III', simdutClass: 'D1A,D1B', simdutLabel: 'Matière toxique', placardCode: '6_1', keywords: ['pesticide solide', 'herbicide', 'insecticide'], isCommon: true },
  { unNumber: '1092', nameFR: 'Acroléine stabilisée', nameEN: 'Acrolein stabilized', casNumber: '107-02-8', tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'I', simdutClass: 'B2,D1A,E', simdutLabel: 'Liquide inflammable, très toxique, corrosif', placardCode: '6_1', keywords: ['acroléine', 'acrolein'], isCommon: false },

  // ── CLASSE 8 — Matières corrosives ──────────────────────
  { unNumber: '1789', nameFR: 'Acide chlorhydrique', nameEN: 'Hydrochloric acid', casNumber: '7647-01-0', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['acide chlorhydrique', 'HCl', 'acide muriatique', 'acide', 'corrosif'], isCommon: true },
  { unNumber: '1830', nameFR: 'Acide sulfurique', nameEN: 'Sulphuric acid', casNumber: '7664-93-9', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['acide sulfurique', 'H2SO4', 'acide', 'batterie', 'corrosif'], isCommon: true },
  { unNumber: '1824', nameFR: 'Solution d\'hydroxyde de sodium', nameEN: 'Sodium hydroxide solution', casNumber: '1310-73-2', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['hydroxyde sodium', 'soude caustique', 'NaOH', 'lessive soude'], isCommon: true },
  { unNumber: '1791', nameFR: 'Hypochlorite en solution', nameEN: 'Hypochlorite solution', casNumber: '7681-52-9', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['hypochlorite', 'javel', 'eau de javel', 'chlore', 'désinfectant'], isCommon: true },
  { unNumber: '1805', nameFR: 'Acide phosphorique en solution', nameEN: 'Phosphoric acid solution', casNumber: '7664-38-2', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['acide phosphorique', 'H3PO4'], isCommon: false },
  { unNumber: '1719', nameFR: 'Solution alcaline caustique, N.S.A.', nameEN: 'Caustic alkali liquid N.O.S.', casNumber: null, tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'I,II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['alcalin caustique', 'base', 'corrosif'], isCommon: false },
  { unNumber: '2031', nameFR: 'Acide nitrique', nameEN: 'Nitric acid', casNumber: '7697-37-2', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'I,II', simdutClass: 'C,E', simdutLabel: 'Comburant, corrosif', placardCode: '8', keywords: ['acide nitrique', 'HNO3', 'acide azotique'], isCommon: false },
  { unNumber: '2796', nameFR: 'Acide sulfurique avec au plus 51% d\'acide', nameEN: 'Sulfuric acid with not more than 51% acid', casNumber: '7664-93-9', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['acide sulfurique', 'batterie', 'accumulateur'], isCommon: true },
  { unNumber: '1823', nameFR: 'Hydroxyde de sodium solide', nameEN: 'Sodium hydroxide solid', casNumber: '1310-73-2', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['hydroxyde sodium', 'soude caustique', 'NaOH solide'], isCommon: true },
  { unNumber: '2672', nameFR: 'Solution d\'ammoniac', nameEN: 'Ammonia solution', casNumber: '1336-21-6', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'III', simdutClass: 'D2B,E', simdutLabel: 'Matière toxique, corrosive', placardCode: '8', keywords: ['ammoniaque', 'solution ammoniac', 'nettoyant'], isCommon: true },
  { unNumber: '1778', nameFR: 'Acide fluorosilicique', nameEN: 'Fluorosilicic acid', casNumber: '16961-83-4', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II', simdutClass: 'D1A,E', simdutLabel: 'Matière toxique, corrosive', placardCode: '8', keywords: ['acide fluorosilicique', 'fluorosilicate'], isCommon: false },
  { unNumber: '1750', nameFR: 'Acide chloroacétique en solution', nameEN: 'Chloroacetic acid solution', casNumber: '79-11-8', tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'II', simdutClass: 'D1A,E', simdutLabel: 'Matière très toxique, corrosive', placardCode: '6_1', keywords: ['acide chloroacétique'], isCommon: false },

  // ── CLASSE 9 — Matières dangereuses diverses ────────────
  { unNumber: '3090', nameFR: 'Piles au lithium', nameEN: 'Lithium batteries', casNumber: null, tmdClass: '9', tmdClassLabel: 'Matières dangereuses diverses', packingGroup: null, simdutClass: null, simdutLabel: null, placardCode: '9', keywords: ['lithium', 'batterie lithium', 'pile lithium', 'lithium-ion'], isCommon: true },
  { unNumber: '3091', nameFR: 'Piles au lithium contenues dans des équipements', nameEN: 'Lithium batteries contained in equipment', casNumber: null, tmdClass: '9', tmdClassLabel: 'Matières dangereuses diverses', packingGroup: null, simdutClass: null, simdutLabel: null, placardCode: '9', keywords: ['lithium', 'batterie lithium équipement', 'véhicule électrique'], isCommon: true },
  { unNumber: '3480', nameFR: 'Piles au lithium-ion', nameEN: 'Lithium ion batteries', casNumber: null, tmdClass: '9', tmdClassLabel: 'Matières dangereuses diverses', packingGroup: null, simdutClass: null, simdutLabel: null, placardCode: '9', keywords: ['lithium-ion', 'batterie li-ion', 'accumulateur lithium', 'VE'], isCommon: true },
  { unNumber: '3077', nameFR: 'Matière dangereuse pour l\'environnement, solide, N.S.A.', nameEN: 'Environmentally hazardous substance solid N.O.S.', casNumber: null, tmdClass: '9', tmdClassLabel: 'Matières dangereuses diverses', packingGroup: 'III', simdutClass: null, simdutLabel: null, placardCode: '9', keywords: ['environnement', 'dangereux environnement', 'polluant'], isCommon: false },
  { unNumber: '3082', nameFR: 'Matière dangereuse pour l\'environnement, liquide, N.S.A.', nameEN: 'Environmentally hazardous substance liquid N.O.S.', casNumber: null, tmdClass: '9', tmdClassLabel: 'Matières dangereuses diverses', packingGroup: 'III', simdutClass: null, simdutLabel: null, placardCode: '9', keywords: ['environnement', 'dangereux environnement', 'polluant liquide'], isCommon: false },
  { unNumber: '2211', nameFR: 'Billes de polymère expansibles', nameEN: 'Polymeric beads expandable', casNumber: null, tmdClass: '9', tmdClassLabel: 'Matières dangereuses diverses', packingGroup: 'III', simdutClass: null, simdutLabel: null, placardCode: '9', keywords: ['styromousse', 'polystyrène', 'mousse'], isCommon: false },
  { unNumber: '1950', nameFR: 'Aérosols', nameEN: 'Aerosols', casNumber: null, tmdClass: '2.1', tmdClassLabel: 'Gaz inflammables', packingGroup: null, simdutClass: 'A,B1', simdutLabel: 'Gaz sous pression, inflammable', placardCode: '2_1', keywords: ['aérosol', 'spray', 'bombes aérosol'], isCommon: true },

  // ── HUILES ET LUBRIFIANTS ────────────────────────────────
  { unNumber: '3256', nameFR: 'Liquide transporté à chaud, inflammable, N.S.A.', nameEN: 'Elevated temperature liquid flammable N.O.S.', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'III', simdutClass: 'B3', simdutLabel: 'Liquide combustible', placardCode: '3', keywords: ['huile chaude', 'liquide chaud', 'asphalte'], isCommon: false },
  { unNumber: '1268', nameFR: 'Distillats de pétrole, N.S.A.', nameEN: 'Petroleum distillates N.O.S.', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable/combustible', placardCode: '3', keywords: ['distillat pétrole', 'kérosène', 'naphta', 'white spirit'], isCommon: true },
  { unNumber: '1223', nameFR: 'Kérosène', nameEN: 'Kerosene', casNumber: '8008-20-6', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'III', simdutClass: 'B3', simdutLabel: 'Liquide combustible', placardCode: '3', keywords: ['kérosène', 'kerosene', 'jet fuel', 'carburéacteur'], isCommon: true },
  { unNumber: '1866', nameFR: 'Solution de résine, inflammable', nameEN: 'Resin solution flammable', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['résine', 'epoxy', 'polyester', 'fibre verre'], isCommon: true },

  // ── PRODUITS DE NETTOYAGE / ENTRETIEN ───────────────────
  { unNumber: '1719', nameFR: 'Solution alcaline caustique', nameEN: 'Caustic alkali solution', casNumber: null, tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['nettoyant industriel', 'dégraissant alcalin', 'caustique'], isCommon: true },
  { unNumber: '3267', nameFR: 'Liquide corrosif basique organique, N.S.A.', nameEN: 'Corrosive liquid basic organic N.O.S.', casNumber: null, tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'I,II,III', simdutClass: 'E', simdutLabel: 'Matière corrosive', placardCode: '8', keywords: ['corrosif basique', 'nettoyant', 'dégraissant'], isCommon: false },

  // ── RÉFRIGÉRANTS ─────────────────────────────────────────
  { unNumber: '1018', nameFR: 'Chlorodifluorométhane (Réfrigérant R-22)', nameEN: 'Chlorodifluoromethane (Refrigerant R-22)', casNumber: '75-45-6', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['R22', 'fréon', 'réfrigérant', 'climatisation', 'R-22'], isCommon: true },
  { unNumber: '3340', nameFR: 'Réfrigérant R-134a', nameEN: 'Refrigerant R-134a', casNumber: '811-97-2', tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['R134a', 'réfrigérant', 'climatisation', 'R-134a', 'HFC'], isCommon: true },
  { unNumber: '3337', nameFR: 'Réfrigérant R-404A', nameEN: 'Refrigerant R-404A', casNumber: null, tmdClass: '2.2', tmdClassLabel: 'Gaz non inflammables, non toxiques', packingGroup: null, simdutClass: 'A', simdutLabel: 'Gaz comprimé', placardCode: '2_2', keywords: ['R404A', 'réfrigérant', 'congélateur', 'HFC'], isCommon: true },

  // ── PEINTURES ET SOLVANTS ────────────────────────────────
  { unNumber: '1210', nameFR: 'Encre d\'imprimerie', nameEN: 'Printing ink', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['encre', 'imprimerie', 'sérigraphie'], isCommon: false },
  { unNumber: '1139', nameFR: 'Solution de revêtement', nameEN: 'Coating solution', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['revêtement', 'peinture', 'coating', 'vernis'], isCommon: true },
  { unNumber: '1274', nameFR: 'Propanol normal', nameEN: 'n-Propanol', casNumber: '71-23-8', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II', simdutClass: 'B2', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['propanol', 'alcool propylique', 'solvant'], isCommon: false },
  { unNumber: '1171', nameFR: 'Éther monoéthylique de l\'éthylène-glycol', nameEN: 'Ethylene glycol monoethyl ether', casNumber: '110-80-5', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'III', simdutClass: 'B3', simdutLabel: 'Liquide combustible', placardCode: '3', keywords: ['éther glycol', 'solvant', 'peinture'], isCommon: false },

  // ── PRODUITS CHIMIQUES INDUSTRIELS COURANTS ──────────────
  { unNumber: '2491', nameFR: 'Éthanolamine', nameEN: 'Ethanolamine', casNumber: '141-43-5', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'III', simdutClass: 'D2B,E', simdutLabel: 'Matière toxique, corrosive', placardCode: '8', keywords: ['éthanolamine', 'MEA', 'traitement eau'], isCommon: false },
  { unNumber: '1170', nameFR: 'Solution d\'éthanol', nameEN: 'Ethanol solution', casNumber: '64-17-5', tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'II,III', simdutClass: 'B2,B3', simdutLabel: 'Liquide inflammable', placardCode: '3', keywords: ['alcool', 'éthanol', 'désinfectant', 'gel hydroalcoolique'], isCommon: true },
  { unNumber: '2924', nameFR: 'Liquide inflammable corrosif, N.S.A.', nameEN: 'Flammable liquid corrosive N.O.S.', casNumber: null, tmdClass: '3', tmdClassLabel: 'Liquides inflammables', packingGroup: 'I,II,III', simdutClass: 'B2,E', simdutLabel: 'Liquide inflammable, corrosif', placardCode: '3', keywords: ['inflammable corrosif'], isCommon: false },
  { unNumber: '2922', nameFR: 'Liquide corrosif toxique, N.S.A.', nameEN: 'Corrosive liquid toxic N.O.S.', casNumber: null, tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'I,II,III', simdutClass: 'D1A,E', simdutLabel: 'Matière toxique, corrosive', placardCode: '8', keywords: ['corrosif toxique'], isCommon: false },
  { unNumber: '1593', nameFR: 'Dichlorométhane', nameEN: 'Dichloromethane', casNumber: '75-09-2', tmdClass: '6.1', tmdClassLabel: 'Matières toxiques', packingGroup: 'III', simdutClass: 'D2B', simdutLabel: 'Matière toxique', placardCode: '6_1', keywords: ['DCM', 'méthylène chlorure', 'décapant peinture'], isCommon: true },
  { unNumber: '2209', nameFR: 'Formaldéhyde en solution', nameEN: 'Formaldehyde solution', casNumber: '50-00-0', tmdClass: '8', tmdClassLabel: 'Matières corrosives', packingGroup: 'III', simdutClass: 'D1A,D2A,E', simdutLabel: 'Matière cancérogène, toxique, corrosive', placardCode: '8', keywords: ['formaldéhyde', 'formol', 'formaline'], isCommon: true },
];

async function main() {
  console.log('Seeding dangerous substances...');

  // Supprimer les doublons par unNumber + nameFR
  const unique = new Map<string, typeof substances[0]>();
  for (const s of substances) {
    const key = `${s.unNumber}-${s.nameFR}`;
    if (!unique.has(key)) unique.set(key, s);
  }

  let count = 0;
  for (const substance of unique.values()) {
    await prisma.dangerousSubstance.upsert({
      where: { id: `un-${substance.unNumber}-${substance.nameFR.substring(0, 20).replace(/[^a-zA-Z0-9]/g, '')}` },
      update: substance,
      create: {
        id: `un-${substance.unNumber}-${substance.nameFR.substring(0, 20).replace(/[^a-zA-Z0-9]/g, '')}`,
        ...substance,
      },
    });
    count++;
  }

  console.log(`✅ ${count} substances dangereuses importées.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());