/* eslint-disable @typescript-eslint/no-require-imports */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),path=require('node:path'),ts=require('typescript');
const filename=path.join(__dirname,'workScheduleEditor.ts');const output=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const loaded=new Module(filename,module.parent);loaded.filename=filename;loaded.paths=Module._nodeModulePaths(__dirname);loaded._compile(output,filename);const e=loaded.exports;
test('40 h and 37.5 h templates keep weekends off',()=>{assert.equal(e.weeklyMinutes(e.SCHEDULE_TEMPLATES[0].slots),2400);assert.equal(e.weeklyMinutes(e.SCHEDULE_TEMPLATES[1].slots),2250);assert.ok(e.SCHEDULE_TEMPLATES[0].slots.every(s=>s.dayOfWeek>=1&&s.dayOfWeek<=5));});
test('multiple slots and copy Monday to weekdays total 40 h',()=>{const monday=[{dayOfWeek:1,startTime:450,endTime:720},{dayOfWeek:1,startTime:780,endTime:990}];const result=e.copyDay(monday,1,[1,2,3,4,5]);assert.equal(result.length,10);assert.equal(e.weeklyMinutes(result),2400);assert.deepEqual(e.slotsForDay(result,5).map(({startTime,endTime})=>[startTime,endTime]),[[450,720],[780,990]]);});
test('cloning creates an independent draft and excludes unrelated data',()=>{const source={intervals:[{dayOfWeek:1,startTime:480,endTime:720}],unavailabilities:[{id:'private'}]};const draft=e.cloneSlots(source.intervals);draft[0].startTime=500;assert.equal(source.intervals[0].startTime,480);assert.equal(draft.length,1);});
test('changing timezone in a draft leaves ten slots intact',()=>{const draft={timeZone:'America/Toronto',slots:e.cloneSlots(e.SCHEDULE_TEMPLATES[0].slots)};const changed={...draft,timeZone:'America/Vancouver'};assert.equal(changed.slots.length,10);});
test('overnight boundary and DST conversion remain supported',()=>{assert.equal(e.toClock(1440),'24:00');assert.equal(e.localDateTimeToIso('2026-03-09T09:00','America/Toronto'),'2026-03-09T13:00:00.000Z');assert.equal(e.nextCivilDate('2026-11-01'),'2026-11-02');assert.equal(e.previousCivilDate('2026-11-02'),'2026-11-01');});
test('unavailability tokens have French labels',()=>{assert.equal(e.UNAVAILABILITY_LABELS.SICK,'Maladie');assert.equal(e.UNAVAILABILITY_LABELS.ADMIN_BLOCK,'Blocage administratif');});
