'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import api from '@/lib/api';
import { cloneSlots, copyDay, fromClock, humanMinutes, localDateTimeToIso, nextCivilDate, SCHEDULE_TEMPLATES,
  previousCivilDate, setDayWorking, slotsForDay, toClock, UNAVAILABILITY_LABELS, WEEK_DAYS, weeklyMinutes, type WorkSlot } from './workScheduleEditor';

type Schedule={id:string;timeZone:string;effectiveFrom:string;effectiveUntil?:string|null;verifiedAt:string;intervals:WorkSlot[]};
type Current={timeZone:string;timeZoneVerified:boolean;schedule:Schedule|null};
type Absence={id:string;startAt:string;endAt:string;allDay:boolean;localStartDate?:string|null;localEndDate?:string|null;timeZone:string;type:string;privateNote?:string|null;cancelledAt?:string|null};
type TeamUser={id:string;firstName:string;lastName:string};
const kinds=Object.keys(UNAVAILABILITY_LABELS);
const today=()=>new Date().toISOString().slice(0,10);
const errorMessage=(error:unknown,fallback:string)=>(error as {response?:{data?:{message?:string}}})?.response?.data?.message||fallback;

export default function WorkScheduleEditorPanel({userId,manager,userName,onDirtyChange}:{userId?:string;manager:boolean;userName?:string;onDirtyChange?:(dirty:boolean)=>void}){
 const [tab,setTab]=useState<'schedule'|'absences'>('schedule'),[current,setCurrent]=useState<Current|null>(null),[history,setHistory]=useState<Schedule[]>([]),[absences,setAbsences]=useState<Absence[]>([]),[team,setTeam]=useState<TeamUser[]>([]);
 const [slots,setSlots]=useState<WorkSlot[]>([]),[timeZone,setTimeZone]=useState('America/Toronto'),[absenceTimeZone,setAbsenceTimeZone]=useState('America/Toronto'),[effectiveFrom,setEffectiveFrom]=useState(today()),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [absence,setAbsence]=useState({type:'VACATION',allDay:false,startAt:'',endAt:'',localStartDate:'',localEndDate:'',privateNote:''});
 const base=userId?`/work-schedules/users/${userId}`:'/work-schedules/me';
 const markDirty=()=>{setDirty(true);setMessage('');};
 const refresh=useCallback(async()=>{try{const requests=[api.get(base),api.get(`${base}/unavailabilities`)];const [schedule,list]=await Promise.all(requests);const data:Current=schedule.data;setCurrent(data);setSlots(cloneSlots(data.schedule?.intervals??[]));setTimeZone(data.timeZone);setAbsenceTimeZone(data.timeZone);setAbsences(list.data);if(manager&&userId){const [versions,users]=await Promise.all([api.get(`${base}/history`),api.get('/users/organization')]);setHistory(versions.data);setTeam(users.data);}}catch(err){setError(errorMessage(err,'Chargement impossible'));}},[base,manager,userId]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const total=weeklyMinutes(slots);
 const changeTab=(next:'schedule'|'absences')=>{if(next!==tab&&dirty&&!window.confirm('Des modifications de l’horaire ne sont pas enregistrées. Changer d’onglet?'))return;setTab(next);};
 const applyTemplate=(id:string)=>{if(!id)return;const template=SCHEDULE_TEMPLATES.find(x=>x.id===id);if(!template)return;if(dirty&&!window.confirm('Remplacer les plages non enregistrées par ce modèle?'))return;setSlots(cloneSlots(template.slots));markDirty();};
 const cloneFrom=async(sourceId:string)=>{if(!sourceId)return;if(dirty&&!window.confirm('Remplacer les plages non enregistrées par l’horaire de ce conseiller?'))return;try{const source=(await api.get(`/work-schedules/users/${sourceId}`)).data as Current;setSlots(cloneSlots(source.schedule?.intervals??[]));markDirty();setMessage('Horaire copié dans le brouillon. Aucune donnée n’est encore enregistrée.');}catch(err){setError(errorMessage(err,'Copie impossible'));}};
 const save=async()=>{if(!userId)return;setBusy(true);setError('');try{await api.post(base,{effectiveFrom,intervals:slots,timeZone});await refresh();setDirty(false);setMessage(`Horaire vérifié · ${timeZone} · ${humanMinutes(total)} / semaine`);}catch(err){setError(errorMessage(err,'Horaire invalide'));}finally{setBusy(false);}};
 const saveAbsence=async()=>{setBusy(true);setError('');try{const body=absence.allDay?{type:absence.type,allDay:true,timeZone:absenceTimeZone,localStartDate:absence.localStartDate,localEndDate:nextCivilDate(absence.localEndDate),privateNote:absence.privateNote}:{type:absence.type,allDay:false,timeZone:absenceTimeZone,startAt:localDateTimeToIso(absence.startAt,absenceTimeZone),endAt:localDateTimeToIso(absence.endAt,absenceTimeZone),privateNote:absence.privateNote};await api.post(`${base}/unavailabilities`,body);setAbsence({type:'VACATION',allDay:false,startAt:'',endAt:'',localStartDate:'',localEndDate:'',privateNote:''});await refresh();setMessage('Indisponibilité enregistrée.');}catch(err){setError(errorMessage(err,'Indisponibilité invalide'));}finally{setBusy(false);}};
 const cancelAbsence=async(id:string)=>{setBusy(true);try{await api.delete(`/work-schedules/unavailabilities/${id}`);await refresh();setMessage('Indisponibilité annulée.');}catch(err){setError(errorMessage(err,'Annulation impossible'));}finally{setBusy(false);}};
 const status=useMemo(()=>current?.timeZoneVerified&&timeZone===current.timeZone?'✓ Fuseau vérifié':'⚠ Fuseau à vérifier',[current,timeZone]);
 const input='rounded-md border border-[#CED4DA] bg-white px-3 py-2 text-sm focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[#2980B9]';
 return <section className="rounded-lg border border-[#E1E5E8] bg-white p-4 sm:p-6"><header className="mb-5"><p className="text-xs font-bold uppercase tracking-widest text-[#ADB5BD]">Planification</p><h3 className="mt-1 text-xl font-bold text-[#2C3E50]">{userName||'Mon horaire'}</h3></header>
 <div className="mb-5 flex gap-1 border-b" role="tablist"><button role="tab" aria-selected={tab==='schedule'} onClick={()=>changeTab('schedule')} className={`px-4 py-2 text-sm font-semibold ${tab==='schedule'?'border-b-2 border-[#C0392B] text-[#922B21]':'text-[#6C757D]'}`}>Horaire régulier</button><button role="tab" aria-selected={tab==='absences'} onClick={()=>changeTab('absences')} className={`px-4 py-2 text-sm font-semibold ${tab==='absences'?'border-b-2 border-[#C0392B] text-[#922B21]':'text-[#6C757D]'}`}>Indisponibilités</button></div>
 {error&&<p role="alert" className="mb-4 rounded bg-[#FCEFED] p-3 text-sm text-[#922B21]">{error}</p>}{message&&<p role="status" className="mb-4 rounded bg-[#EAF7EE] p-3 text-sm text-[#277245]">{message}</p>}
 {tab==='schedule'&&<div className="space-y-6"><div className="grid gap-4 rounded-lg bg-[#F8F9FA] p-4 sm:grid-cols-3"><label className="text-sm font-semibold text-[#45515C]">Fuseau horaire<input className={`${input} mt-1 w-full`} list="iana-time-zones" value={timeZone} onChange={e=>{setTimeZone(e.target.value);markDirty();}}/><datalist id="iana-time-zones"><option value="America/Toronto"/><option value="America/Montreal"/><option value="America/Vancouver"/><option value="America/Edmonton"/><option value="America/Halifax"/></datalist><span className="mt-1 block text-xs font-normal text-[#6C757D]">{status}</span></label><label className="text-sm font-semibold text-[#45515C]">Date d’effet<input className={`${input} mt-1 w-full`} type="date" value={effectiveFrom} onChange={e=>{setEffectiveFrom(e.target.value);markDirty();}}/></label><div className="text-sm text-[#45515C]"><strong>Horaire actuel</strong><p className="mt-2">{current?.schedule?'Configuré':'Non configuré'}</p>{current?.schedule&&<p className="text-xs text-[#6C757D]">Depuis le {new Date(current.schedule.effectiveFrom).toLocaleDateString('fr-CA',{timeZone:current.schedule.timeZone})}</p>}</div></div>
 {manager&&userId&&<><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-[#45515C]">Modèle d’horaire<select className={`${input} mt-1 w-full`} defaultValue="" onChange={e=>{applyTemplate(e.target.value);e.target.value='';}}><option value="">Sélectionner un modèle</option>{SCHEDULE_TEMPLATES.map(t=><option key={t.id} value={t.id}>{t.label} — {t.description}</option>)}<option value="">Personnalisé</option></select></label><label className="text-sm font-semibold text-[#45515C]">Copier l’horaire de<select className={`${input} mt-1 w-full`} defaultValue="" onChange={e=>{void cloneFrom(e.target.value);e.target.value='';}}><option value="">Choisir un conseiller</option>{team.filter(u=>u.id!==userId).map(u=><option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select></label></div>
 <div className="space-y-3">{WEEK_DAYS.map(day=>{const daySlots=slotsForDay(slots,day.value),working=daySlots.length>0;return <article key={day.value} className="rounded-lg border border-[#E1E5E8] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 font-bold text-[#2C3E50]"><input type="checkbox" checked={working} onChange={e=>{setSlots(setDayWorking(slots,day.value,e.target.checked));markDirty();}}/>{day.label}<span className="text-xs font-normal text-[#6C757D]">{working?'Travaille':'Non travaillé'}</span></label>{working&&<select aria-label={`Copier ${day.label} vers`} className={input} defaultValue="" onChange={e=>{const targets=e.target.value==='weekdays'?[1,2,3,4,5]:e.target.value==='all'?WEEK_DAYS.map(d=>d.value):[Number(e.target.value)];if(targets.some(target=>target!==day.value&&slotsForDay(slots,target).length)&&!window.confirm('Remplacer les plages des jours cibles?')){e.target.value='';return;}setSlots(copyDay(slots,day.value,targets));markDirty();e.target.value='';}}><option value="">Copier vers…</option>{WEEK_DAYS.filter(d=>d.value!==day.value).map(d=><option key={d.value} value={d.value}>{d.label}</option>)}<option value="weekdays">Tous les jours ouvrables</option><option value="all">Tous les jours</option></select>}</div>
 {working&&<div className="mt-3 space-y-2">{daySlots.map((slot,index)=>{const realIndex=slots.indexOf(slot);return <div key={`${slot.startTime}-${index}`} className="flex flex-wrap items-center gap-2"><input aria-label={`Début ${day.label} plage ${index+1}`} className={input} type="time" value={toClock(slot.startTime)} onChange={e=>{setSlots(slots.map((s,i)=>i===realIndex?{...s,startTime:fromClock(e.target.value)}:s));markDirty();}}/><span>—</span><input aria-label={`Fin ${day.label} plage ${index+1}`} className={input} type="time" value={slot.endTime===1440?'00:00':toClock(slot.endTime)} onChange={e=>{setSlots(slots.map((s,i)=>i===realIndex?{...s,endTime:fromClock(e.target.value)}:s));markDirty();}}/><label className="text-xs"><input type="checkbox" checked={slot.endTime===1440} onChange={e=>{setSlots(slots.map((s,i)=>i===realIndex?{...s,endTime:e.target.checked?1440:1439}:s));markDirty();}}/> Fin à minuit</label><button aria-label={`Retirer la plage ${index+1} du ${day.label}`} className="text-sm font-semibold text-[#A93226] underline" onClick={()=>{setSlots(slots.filter((_,i)=>i!==realIndex));markDirty();}}>Retirer</button></div>;})}<button className="text-sm font-semibold text-[#2471A3]" onClick={()=>{setSlots([...slots,{dayOfWeek:day.value,startTime:540,endTime:1020}]);markDirty();}}>+ Ajouter une plage</button></div>}</article>;})}</div>
 <div className="sticky bottom-0 flex flex-col gap-3 rounded-lg border border-[#D7DEE3] bg-white p-4 shadow-lg sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-[#2C3E50]">Total : {humanMinutes(total)} / semaine</strong>{dirty&&<p className="text-xs font-semibold text-[#9A6700]">Modifications non enregistrées</p>}</div><button disabled={busy||!dirty} onClick={save} className="rounded-md bg-[#C0392B] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Enregistrer et vérifier l’horaire</button></div></>}
 {history.length>0&&<details className="rounded border p-4"><summary className="cursor-pointer font-semibold">Historique des horaires ({history.length})</summary><div className="mt-3 space-y-2 text-sm">{history.map(version=><p key={version.id}>{new Date(version.effectiveFrom).toLocaleDateString('fr-CA',{timeZone:version.timeZone})} → {version.effectiveUntil?new Date(version.effectiveUntil).toLocaleDateString('fr-CA',{timeZone:version.timeZone}):'actuel'} · {version.timeZone} · {humanMinutes(weeklyMinutes(version.intervals))}</p>)}</div></details>}</div>}
 {tab==='absences'&&<div className="space-y-5"><div className="space-y-2">{absences.filter(x=>!x.cancelledAt).map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3 text-sm"><div><strong>{UNAVAILABILITY_LABELS[item.type]||'Indisponible'}</strong><p className="text-[#6C757D]">{item.allDay&&item.localStartDate?`${item.localStartDate} au ${item.localEndDate?previousCivilDate(item.localEndDate):''} inclus`:`${new Date(item.startAt).toLocaleString('fr-CA',{timeZone:item.timeZone})} – ${new Date(item.endAt).toLocaleString('fr-CA',{timeZone:item.timeZone})}`}</p></div><button disabled={busy} className="font-semibold text-[#A93226] underline" onClick={()=>void cancelAbsence(item.id)}>Annuler</button></article>)}{!absences.some(x=>!x.cancelledAt)&&<p className="rounded bg-[#F8F9FA] p-4 text-sm text-[#6C757D]">Aucune indisponibilité active.</p>}</div>
 <div className="rounded-lg border p-4"><h4 className="mb-4 font-bold">Ajouter une indisponibilité</h4><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Type<select className={`${input} mt-1 w-full`} value={absence.type} onChange={e=>setAbsence({...absence,type:e.target.value})}>{kinds.map(kind=><option key={kind} value={kind}>{UNAVAILABILITY_LABELS[kind]}</option>)}</select></label><label className="text-sm">Fuseau<input className={`${input} mt-1 w-full`} value={absenceTimeZone} onChange={e=>setAbsenceTimeZone(e.target.value)}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={absence.allDay} onChange={e=>setAbsence({...absence,allDay:e.target.checked})}/> Journée entière</label></div>
 <div className="mt-4 grid gap-4 sm:grid-cols-2">{absence.allDay?<><label className="text-sm">Du<input className={`${input} mt-1 w-full`} type="date" value={absence.localStartDate} onChange={e=>setAbsence({...absence,localStartDate:e.target.value})}/></label><label className="text-sm">Au (inclus)<input className={`${input} mt-1 w-full`} type="date" value={absence.localEndDate} onChange={e=>setAbsence({...absence,localEndDate:e.target.value})}/></label></>:<><label className="text-sm">Début<input className={`${input} mt-1 w-full`} type="datetime-local" value={absence.startAt} onChange={e=>setAbsence({...absence,startAt:e.target.value})}/></label><label className="text-sm">Fin<input className={`${input} mt-1 w-full`} type="datetime-local" value={absence.endAt} onChange={e=>setAbsence({...absence,endAt:e.target.value})}/></label></>}<label className="text-sm sm:col-span-2">Note privée<input className={`${input} mt-1 w-full`} maxLength={2000} value={absence.privateNote} onChange={e=>setAbsence({...absence,privateNote:e.target.value})}/></label></div><p className="mt-3 text-xs text-[#6C757D]">Les dates et heures sont interprétées dans le fuseau affiché. La date « Au » est incluse.</p><button disabled={busy} className="mt-4 rounded bg-[#C0392B] px-4 py-2 text-sm font-bold text-white disabled:opacity-50" onClick={()=>void saveAbsence()}>Ajouter l’indisponibilité</button></div></div>}
 </section>;
}
