export const POPULATION_CONTACT_CHANGE_OPERATION_VERSION =
  'population-contact-change/v1';
export const POPULATION_CONTACT_CHANGE_SOURCE = 'PUBLIC_PORTAL';
export const POPULATION_CONTACT_CHANGE_SURFACE =
  'SENTINELLE_POPULATION_PROFILE';
export const POPULATION_CONTACT_CHANGE_TTL_MS = 10 * 60 * 1000;
export const POPULATION_CONTACT_CHANGE_MAX_ATTEMPTS = 5;
export const POPULATION_CONTACT_CHANGE_MAX_RESENDS = 3;
