/**
 * Homepage content module (MIG-08A). Every string is carried over verbatim or near-verbatim from the legacy
 * `HomePageClient.tsx` TRANSLATIONS dictionary and section copy (see docs/website-v2/05-migration/MIG-08-HOMEPAGE-GATE.md
 * §6-8 for the preservation matrix and claim audit this module implements). No new claims are introduced here;
 * PGC/PRA/PUE are marked `phase: 2` and must never be presented as available today (CLAUDE.md §3).
 */
import type { Locale } from '@/lib/site/locale';

const fr = {
  hero: {
    label: 'Plateforme de résilience opérationnelle · Québec & Canada',
    title: ['La résilience commence', 'bien avant l’urgence.'],
    lead: 'CORO relie vos plans, vos bâtiments, vos équipes et vos opérations d’urgence dans un même environnement — pour transformer la conformité en préparation opérationnelle mesurable, jusqu’à l’intervention.',
    detail: 'Conçue au Québec · Données hébergées au Canada',
    primary: { label: 'Demander une démonstration', href: '/#demo' },
    watchVideo: 'Voir la vidéo',
    overlays: [
      { label: 'Connaître', text: 'Plans · Procédures\nSystèmes' },
      { label: 'Personnes', text: 'Occupation\nÉquipes d’urgence' },
      { label: 'Agir', text: 'Incident · Actions\nTraçabilité' },
    ],
  },
  tension: {
    label: 'Pourquoi CORO',
    heading: 'Avoir un plan ne signifie pas être prêt.',
    lead: 'Les plans, les procédures, les équipes, les systèmes et les données existent souvent déjà — chacun de leur côté. La difficulté commence quand il faut les relier pour comprendre, décider et agir.',
    inputs: ['Plans', 'Procédures', 'Personnes', 'Systèmes', 'Données', 'Incidents'],
    destination: 'Information → Décision → Action',
    destinationNote: 'Relier l’information à l’action.',
    demoAccount: 'Compte démo',
  },
  continuum: {
    label: 'Un continuum de résilience',
    heading: 'Avant. Pendant. Après. Une même continuité opérationnelle.',
    lead: 'CORO relie la connaissance du bâtiment, la préparation, la réponse opérationnelle, la preuve et l’amélioration continue au sein d’un même environnement — pour que l’information reste utile tout au long du cycle.',
    zones: [
      { key: 'avant', label: 'Avant' },
      { key: 'pendant', label: 'Pendant' },
      { key: 'apres', label: 'Après' },
    ],
    stages: [
      { id: 'connaitre', name: 'Connaître', phrase: 'Comprendre son environnement' },
      { id: 'anticiper', name: 'Anticiper', phrase: 'Se préparer en amont' },
      { id: 'detecter', name: 'Détecter', phrase: 'Identifier ce qui survient' },
      { id: 'decider', name: 'Décider', phrase: 'Éclairer la décision' },
      { id: 'agir', name: 'Agir', phrase: 'Passer à l’action' },
      { id: 'proteger', name: 'Protéger', phrase: 'Protéger les personnes' },
      { id: 'prouver', name: 'Prouver', phrase: 'Conserver la trace' },
      { id: 'apprendre', name: 'Apprendre', phrase: 'Tirer parti de l’expérience' },
      { id: 'ameliorer', name: 'Améliorer', phrase: 'Renforcer la capacité' },
    ],
    punchlineLead: 'La résilience n’est pas une succession d’outils.',
    punchline: 'C’est une continuité.',
    link: { label: 'Explorer l’écosystème', href: '#ecosysteme' },
  },
  ecosystem: {
    label: 'Connaître l’environnement',
    heading: 'Un bâtiment. Une vision complète.',
    lead: 'CORO relie l’information, les personnes et les systèmes d’un bâtiment pour soutenir sa préparation et sa réponse.',
    imageAlt: 'Illustration en coupe d’un bâtiment montrant différents espaces, personnes et systèmes opérationnels.',
    callouts: [
      { id: 'plans', label: 'Plans & documents', text: 'PMU · PSI · PCA', top: '5%', left: '42%' },
      { id: 'occupation', label: 'Occupation', text: 'Employés · Visiteurs · Entrepreneurs', top: '30%', left: '28%' },
      { id: 'equipes', label: 'Équipes d’urgence', text: 'Rôles · Disponibilité', top: '18%', left: '58%' },
      { id: 'systemes', label: 'Systèmes', text: 'Équipements · Signaux', top: '76%', left: '36%' },
      { id: 'incidents', label: 'Incidents & opérations', text: 'Chronologie · Actions · Preuves', top: '76%', left: '60%' },
    ],
    indice: {
      label: 'L’indice CORO',
      lead: 'Un indicateur clair pour une meilleure résilience.',
      scoreLabel: 'Exemple de démonstration',
      checklist: ['Risques identifiés', 'Plans à jour', 'Exercices réalisés', 'Capacité opérationnelle', 'Amélioration continue'],
      scoreAccessibleText: '78 sur 100',
      maturityNote: 'Modèle en développement — illustré ici à titre indicatif.',
    },
  },
  documents: {
    label: '01. Une suite complète',
    heading: 'Tous vos documents. Un seul endroit.',
    lead: 'Des modèles structurés, alignés sur les normes applicables au Québec et au Canada, adaptés à votre réalité.',
    linkLabel: 'En savoir plus',
    phaseLabel: 'Phase 2',
    items: [
      { code: 'PMU', name: 'Plan de mesures d’urgence', purpose: 'Bâtiments et occupants', color: '#2980B9', href: '/documents/plan-mesures-urgence-pmu' },
      { code: 'PSI', name: 'Plan de sécurité incendie', purpose: 'Prévention et intervention', color: '#C0392B', href: '/documents/plan-securite-incendie-psi' },
      { code: 'PCA', name: 'Plan de continuité des activités', purpose: 'Maintien des opérations', color: '#27AE60', href: '/documents/plan-continuite-activites-pca' },
      { code: 'PGC', name: 'Plan de gestion de crise', purpose: 'Gestion stratégique', color: '#8E44AD', phase: 2 as const },
      { code: 'PRA', name: 'Plan de reprise des activités', purpose: 'Retour aux opérations', color: '#E67E22', phase: 2 as const },
      { code: 'PUE', name: 'Plan d’urgence environnementale', purpose: 'Sites industriels / RUE/E2', color: '#16A085', phase: 2 as const },
    ],
  },
  sentinelle: {
    label: 'Présence et évacuation',
    heading: 'Savoir qui est là. Savoir qui est sorti. Savoir qui manque.',
    lead: 'Présence en temps réel, registre d’occupation, mode évacuation et point de rassemblement — CORO Sentinelle relie le bâtiment aux personnes qui s’y trouvent, en tout temps.',
    imageAlt: 'Une personne enregistre sa présence par code QR à l’entrée d’un bâtiment pendant qu’un agent de sécurité suit l’occupation et l’évacuation depuis un poste CORO Sentinelle.',
    sequence: ['Savoir', 'Confirmer', 'Évacuer', 'Rassembler', 'Protéger'],
    alert: { label: 'Urgent', title: 'Alerte incendie', meta: 'RDC · 10:31 — Procédures activées', accessibleLabel: 'Exemple d’alerte — démonstration' },
    links: [
      { label: 'Découvrir Sentinelle', href: '/sentinelle' },
      { label: 'Sentinelle Population', href: '/sentinelle-population' },
    ],
  },
  interventionImprovement: {
    label: 'De l’action à l’amélioration',
    heading: 'De l’intervention à l’amélioration.',
    left: {
      label: 'Intervenir',
      heading: 'La bonne information. Au bon moment.',
      lead: 'CORO relie l’événement, les procédures, les rôles et les actions pour soutenir une intervention coordonnée.',
      markers: ['Procédures', 'Rôles', 'Actions', 'Chronologie'],
      cta: { label: 'Découvrir CORO Incident', href: '/coro-incident' },
      imageAlt: 'Équipe d’intervention consultant les procédures et le suivi opérationnel.',
    },
    right: {
      label: 'Améliorer',
      heading: 'Chaque événement doit rendre le prochain meilleur.',
      lead: 'Le document n’est plus la fin du processus : l’exercice et l’incident nourrissent la révision, les actions correctives et la mise à jour des plans.',
      loop: ['Rapport', 'REX', 'Actions correctives', 'Plans actualisés'],
      loopDesc: ['Ce qui s’est passé', 'Ce qu’on apprend', 'Ce qu’on corrige', 'Ce qu’on améliore'],
      imageAlt: 'Exercice de préparation et débreffage d’équipe après simulation.',
    },
    connector: ['Intervenir', 'Prouver', 'Apprendre', 'Améliorer'],
  },
  resilience: {
    label: '01 · MESURER LA PRÉPARATION',
    heading: 'Votre plan dit que vous êtes prêt. CORO vous montre où vous en êtes.',
    lead: 'L’Indice CORO transforme les données de préparation en une lecture claire de la capacité opérationnelle et de son évolution.',
    benefits: ['Détecter les écarts', 'Prioriser les actions', 'Suivre la progression'],
    cta: { label: 'Découvrir l’Indice CORO', href: '/resilience-operationnelle' },
    graph: {
      cardTitle: 'Évolution de l’Indice CORO',
      demoDisclosure: 'Exemple de démonstration',
      points: [{ label: 'Jan', value: 52 }, { label: 'Mar', value: 60 }, { label: 'Jun', value: 68 }, { label: 'Sep', value: 78 }],
      progressionValue: '+50 %',
      progressionSpan: 'en 9 mois',
      indicators: ['Risques identifiés', 'Plans à jour', 'Exercices réalisés', 'Actions correctives'],
      maturityNote: 'Modèle en développement — illustré ici à titre indicatif.',
      accessibleSummary: 'Progression illustrative de l’Indice CORO : janvier 52, mars 60, juin 68, septembre 78 (données de démonstration).',
    },
  },
  platform: {
    label: '04 · L’écosystème CORO',
    heading: 'Une plateforme. Tout un écosystème.',
    lead: 'Chaque bâtiment.\nChaque personne.\nChaque situation.',
    cards: [
      { id: 'documents', title: 'Documents', desc: 'Plans, procédures,\ntoujours à jour.', image: 'ecosystem-documents.webp', color: '#2980B9', href: '/gestion-documentaire' },
      { id: 'sentinelle', title: 'Sentinelle', desc: 'Occupation et évacuation\nen temps réel.', image: 'ecosystem-sentinelle.webp', color: '#0EA5B7', href: '/sentinelle' },
      { id: 'population', title: 'Population', desc: 'Informer. Protéger.\nRassurer.', image: 'ecosystem-population.webp', color: '#6366F1', href: '/sentinelle-population' },
      { id: 'incident', title: 'Incident', desc: 'Réagir vite.\nBien. Ensemble.', image: 'ecosystem-incident.webp', color: '#C0392B', href: '/coro-incident' },
      { id: 'exercices', title: 'Exercices', desc: 'S’entraîner pour\nêtre prêt.', image: 'ecosystem-exercices.webp', color: '#E67E22' },
      { id: 'resilience', title: 'Résilience', desc: 'Mesurer et\naméliorer.', image: 'ecosystem-resilience.webp', color: '#16A085', href: '/resilience-operationnelle' },
      { id: 'client', title: 'Portail client', desc: 'Multi-sites et\ngouvernance.', image: 'ecosystem-client.webp', color: '#8E44AD', href: '/portail-client' },
    ],
  },
  trust: {
    label: 'Confiance & sécurité',
    heading: 'Vos opérations critiques méritent un environnement conçu avec rigueur.',
    lead: 'CORO intègre des mesures de protection, de contrôle et de traçabilité adaptées à une plateforme qui centralise des informations opérationnelles importantes.',
    items: [
      { code: '01', title: 'Infrastructure canadienne', text: 'Hébergement principal au Canada (Toronto).', source: { label: 'Voir la page Sécurité', href: '/security' } },
      { code: '02', title: 'Plateforme bilingue', text: 'Documents et interface disponibles en français et en anglais.' },
      { code: '03', title: 'Documents disponibles', text: 'PMU, PSI et PCA disponibles dès maintenant.', source: { label: 'Voir les documents', href: '/gestion-documentaire' } },
      { code: '04', title: 'Cadres & références', text: 'ISO 22301, CNPI 2020, CNESST — références utilisées dans les rapports générés.' },
    ],
    cta: { label: 'Voir la page Sécurité', href: '/security' },
  },
  ctaFinal: {
    label: 'Prêt à mesurer votre résilience ?',
    statement: 'Transformons vos données en capacité d’action.',
    support: 'CORO centralise vos documents de continuité, votre occupation en temps réel et vos indicateurs de résilience dans une seule plateforme.',
    secondary: { label: 'Nous contacter', href: '/contact' },
    manifesto: 'DES DONNÉES.\nDES DÉCISIONS.\nDES ORGANISATIONS PLUS FORTES.',
  },
  demoProof: {
    label: 'Parlons de votre réalité',
    headline: 'Une plateforme qui doit\nfaire ses preuves sur le terrain.',
    intro: 'CORO est conçu pour relier ce qui est encore trop souvent dispersé : bâtiments, plans, personnes, opérations et amélioration continue.',
    values: [
      { title: 'Temps gagné', text: 'Dans la préparation et le suivi.' },
      { title: 'Information accessible', text: 'Au moment où elle compte.' },
      { title: 'Équipes préparées', text: 'Avant que l’événement survienne.' },
      { title: 'Amélioration continue', text: 'Après chaque exercice et incident.' },
    ],
    proofLabel: 'Retours d’expérience',
    proofTitle: 'Les premiers retours d’expérience seront publiés ici.',
    proofBody: 'CORO entre dans sa prochaine phase : confronter la plateforme aux réalités des organisations, mesurer son impact et continuer à l’améliorer.',
    contribution: 'Vous utilisez CORO ? Votre expérience contribuera à son évolution.',
    formLabel: 'Demander une démonstration',
    formHeading: 'Parlons de vos bâtiments,\nde vos équipes et de vos défis.',
    formSupport: 'Remplissez ce court formulaire et notre équipe vous contactera rapidement pour planifier une démonstration personnalisée.',
  },
  resources: {
    label: 'Ressources',
    heading: 'Explorer avant de démarrer',
    links: [
      { label: 'Guides', href: '/guides' },
      { label: 'Blogue', href: '/blog' },
      { label: 'Tarifs', href: '/pricing' },
    ],
  },
};

export type HomeContent = typeof fr;

const en: HomeContent = {
  hero: {
    label: 'Operational resilience platform · Quebec & Canada',
    title: ['Resilience starts', 'long before the emergency.'],
    lead: 'CORO connects your plans, buildings, teams and emergency operations in one environment — turning compliance into measurable operational readiness, all the way through response.',
    detail: 'Designed in Quebec · Data hosted in Canada',
    primary: { label: 'Request a demonstration', href: '/?lang=en#demo' },
    watchVideo: 'Watch the video',
    overlays: [
      { label: 'Know', text: 'Plans · Procedures\nSystems' },
      { label: 'People', text: 'Occupancy\nEmergency teams' },
      { label: 'Act', text: 'Incident · Actions\nTraceability' },
    ],
  },
  tension: {
    label: 'Why CORO',
    heading: 'Having a plan does not mean being ready.',
    lead: 'Plans, procedures, teams, systems and data often already exist — each on their own. The difficulty starts when they need to come together to understand, decide and act.',
    inputs: ['Plans', 'Procedures', 'People', 'Systems', 'Data', 'Incidents'],
    destination: 'Information → Decision → Action',
    destinationNote: 'Connecting information to action.',
    demoAccount: 'Demo account',
  },
  continuum: {
    label: 'A resilience continuum',
    heading: 'Before. During. After. One operational continuity.',
    lead: 'CORO connects knowledge of the building, preparation, operational response, proof and continuous improvement within one environment — so information remains useful throughout the entire cycle.',
    zones: [
      { key: 'avant', label: 'Before' },
      { key: 'pendant', label: 'During' },
      { key: 'apres', label: 'After' },
    ],
    stages: [
      { id: 'connaitre', name: 'Know', phrase: 'Understand your environment' },
      { id: 'anticiper', name: 'Anticipate', phrase: 'Prepare in advance' },
      { id: 'detecter', name: 'Detect', phrase: 'Spot what’s happening' },
      { id: 'decider', name: 'Decide', phrase: 'Inform the decision' },
      { id: 'agir', name: 'Act', phrase: 'Take action' },
      { id: 'proteger', name: 'Protect', phrase: 'Protect people' },
      { id: 'prouver', name: 'Prove', phrase: 'Keep the record' },
      { id: 'apprendre', name: 'Learn', phrase: 'Learn from experience' },
      { id: 'ameliorer', name: 'Improve', phrase: 'Strengthen capability' },
    ],
    punchlineLead: 'Resilience is not a collection of tools.',
    punchline: 'It is continuity.',
    link: { label: 'Explore the ecosystem', href: '#ecosysteme' },
  },
  ecosystem: {
    label: 'Know the environment',
    heading: 'One building. A complete view.',
    lead: 'CORO connects the information, people and systems of a building to support its preparedness and response.',
    imageAlt: 'Cutaway illustration of a building showing different spaces, people and operational systems.',
    callouts: [
      { id: 'plans', label: 'Plans & documents', text: 'ERP · FSP · BCP', top: '5%', left: '42%' },
      { id: 'occupation', label: 'Occupancy', text: 'Employees · Visitors · Contractors', top: '30%', left: '28%' },
      { id: 'equipes', label: 'Emergency teams', text: 'Roles · Availability', top: '18%', left: '58%' },
      { id: 'systemes', label: 'Systems', text: 'Equipment · Signals', top: '76%', left: '36%' },
      { id: 'incidents', label: 'Incidents & operations', text: 'Timeline · Actions · Evidence', top: '76%', left: '60%' },
    ],
    indice: {
      label: 'The CORO Index',
      lead: 'A clear indicator for stronger resilience.',
      scoreLabel: 'Demonstration example',
      checklist: ['Risks identified', 'Plans up to date', 'Exercises completed', 'Operational capacity', 'Continuous improvement'],
      scoreAccessibleText: '78 out of 100',
      maturityNote: 'Model in development — shown here for illustration only.',
    },
  },
  documents: {
    label: '01. A complete suite',
    heading: 'All your documents. One place.',
    lead: 'Structured templates, aligned with applicable standards in Quebec and Canada, adapted to your reality.',
    linkLabel: 'Learn more',
    phaseLabel: 'Phase 2',
    items: [
      { code: 'PMU', name: 'Emergency Response Plan', purpose: 'Buildings and occupants', color: '#2980B9', href: '/documents/plan-mesures-urgence-pmu' },
      { code: 'PSI', name: 'Fire Safety Plan', purpose: 'Prevention and response', color: '#C0392B', href: '/documents/plan-securite-incendie-psi' },
      { code: 'PCA', name: 'Business Continuity Plan', purpose: 'Maintaining operations', color: '#27AE60', href: '/documents/plan-continuite-activites-pca' },
      { code: 'PGC', name: 'Crisis Management Plan', purpose: 'Strategic management', color: '#8E44AD', phase: 2 as const },
      { code: 'PRA', name: 'Disaster Recovery Plan', purpose: 'Return to operations', color: '#E67E22', phase: 2 as const },
      { code: 'PUE', name: 'Environmental Emergency Plan', purpose: 'Industrial sites / RUE/E2', color: '#16A085', phase: 2 as const },
    ],
  },
  sentinelle: {
    label: 'Occupancy and evacuation',
    heading: 'Know who is there. Know who left. Know who is missing.',
    lead: 'Real-time occupancy, an occupancy registry, evacuation mode and assembly points — CORO Sentinelle connects the building to the people inside it, at all times.',
    imageAlt: 'A person checks in with a QR code at a building entrance while a security officer monitors occupancy and evacuation from a CORO Sentinelle station.',
    sequence: ['Know', 'Confirm', 'Evacuate', 'Assemble', 'Protect'],
    alert: { label: 'Urgent', title: 'Fire alert', meta: 'Ground floor · 10:31 — Procedures activated', accessibleLabel: 'Alert example — demonstration' },
    links: [
      { label: 'Discover Sentinelle', href: '/sentinelle?lang=en' },
      { label: 'Sentinelle Population', href: '/sentinelle-population?lang=en' },
    ],
  },
  interventionImprovement: {
    label: 'From action to improvement',
    heading: 'From intervention to improvement.',
    left: {
      label: 'Respond',
      heading: 'The right information. At the right time.',
      lead: 'CORO connects the event, procedures, roles and actions to support a coordinated response.',
      markers: ['Procedures', 'Roles', 'Actions', 'Timeline'],
      cta: { label: 'Discover operational resilience', href: '/resilience-operationnelle?lang=en' },
      imageAlt: 'Response team reviewing procedures and operational tracking.',
    },
    right: {
      label: 'Improve',
      heading: 'Every event should make the next one better.',
      lead: 'The document is no longer the end of the process: exercises and incidents feed review, corrective actions and updated plans.',
      loop: ['Report', 'REX', 'Corrective actions', 'Updated plans'],
      loopDesc: ['What happened', 'What we learn', 'What we fix', 'What we improve'],
      imageAlt: 'Preparedness exercise and team debrief after simulation.',
    },
    connector: ['Respond', 'Prove', 'Learn', 'Improve'],
  },
  resilience: {
    label: '01 · MEASURE READINESS',
    heading: 'Your plan says you’re ready. CORO shows you where you stand.',
    lead: 'The CORO Index turns preparedness data into a clear picture of operational capability and how it evolves.',
    benefits: ['Detect the gaps', 'Prioritize actions', 'Track progress'],
    cta: { label: 'Discover the CORO Index', href: '/resilience-operationnelle?lang=en' },
    graph: {
      cardTitle: 'CORO Index progression',
      demoDisclosure: 'Demonstration example',
      points: [{ label: 'Jan', value: 52 }, { label: 'Mar', value: 60 }, { label: 'Jun', value: 68 }, { label: 'Sep', value: 78 }],
      progressionValue: '+50 %',
      progressionSpan: 'in 9 months',
      indicators: ['Risks identified', 'Plans up to date', 'Exercises completed', 'Corrective actions'],
      maturityNote: 'Model in development — shown here for illustration only.',
      accessibleSummary: 'Illustrative CORO Index progression: January 52, March 60, June 68, September 78 (demonstration data).',
    },
  },
  platform: {
    label: '04 · The CORO ecosystem',
    heading: 'One platform. A complete ecosystem.',
    lead: 'Every building.\nEvery person.\nEvery situation.',
    cards: [
      { id: 'documents', title: 'Documents', desc: 'Plans and procedures,\nalways up to date.', image: 'ecosystem-documents.webp', color: '#2980B9', href: '/gestion-documentaire?lang=en' },
      { id: 'sentinelle', title: 'Sentinelle', desc: 'Occupancy and evacuation\nin real time.', image: 'ecosystem-sentinelle.webp', color: '#0EA5B7', href: '/sentinelle?lang=en' },
      { id: 'population', title: 'Population', desc: 'Inform. Protect.\nReassure.', image: 'ecosystem-population.webp', color: '#6366F1', href: '/sentinelle-population?lang=en' },
      { id: 'incident', title: 'Incident', desc: 'Respond fast.\nWell. Together.', image: 'ecosystem-incident.webp', color: '#C0392B', href: '/coro-incident?lang=en' },
      { id: 'exercices', title: 'Exercises', desc: 'Train to\nbe ready.', image: 'ecosystem-exercices.webp', color: '#E67E22' },
      { id: 'resilience', title: 'Resilience', desc: 'Measure and\nimprove.', image: 'ecosystem-resilience.webp', color: '#16A085', href: '/resilience-operationnelle?lang=en' },
      { id: 'client', title: 'Client portal', desc: 'Multi-site\ngovernance.', image: 'ecosystem-client.webp', color: '#8E44AD', href: '/portail-client?lang=en' },
    ],
  },
  trust: {
    label: 'Trust & security',
    heading: 'Your critical operations deserve an environment designed with care.',
    lead: 'CORO incorporates protection, access control and traceability measures suited to a platform that centralizes important operational information.',
    items: [
      { code: '01', title: 'Canadian infrastructure', text: 'Primary hosting in Canada (Toronto).', source: { label: 'See the Security page', href: '/security?lang=en' } },
      { code: '02', title: 'Bilingual platform', text: 'Documents and interface available in French and English.' },
      { code: '03', title: 'Available documents', text: 'ERP, FSP and BCP available now.', source: { label: 'See the documents', href: '/gestion-documentaire?lang=en' } },
      { code: '04', title: 'Frameworks & references', text: 'ISO 22301, NFPA, CCOHS — references used within generated reports.' },
    ],
    cta: { label: 'See the Security page', href: '/security?lang=en' },
  },
  ctaFinal: {
    label: 'Ready to measure your resilience?',
    statement: 'Turn your data into the capacity to act.',
    support: 'CORO brings your continuity documents, real-time occupancy and resilience indicators together in one platform.',
    secondary: { label: 'Contact us', href: '/contact?lang=en' },
    manifesto: 'DATA.\nDECISIONS.\nSTRONGER ORGANIZATIONS.',
  },
  demoProof: {
    label: 'Let’s talk about your reality',
    headline: 'A platform that has to\nprove itself in the field.',
    intro: 'CORO is designed to connect what is still too often fragmented: buildings, plans, people, operations and continuous improvement.',
    values: [
      { title: 'Time saved', text: 'In preparation and follow-up.' },
      { title: 'Accessible information', text: 'When it matters.' },
      { title: 'Prepared teams', text: 'Before an event occurs.' },
      { title: 'Continuous improvement', text: 'After every exercise and incident.' },
    ],
    proofLabel: 'Field feedback',
    proofTitle: 'The first field feedback will be published here.',
    proofBody: 'CORO is entering its next phase: confronting the platform with the realities of organizations, measuring its impact and continuing to improve it.',
    contribution: 'Using CORO? Your experience will help shape where it goes next.',
    formLabel: 'Request a demonstration',
    formHeading: 'Let’s talk about your buildings,\nyour teams and your challenges.',
    formSupport: 'Fill out this short form and our team will reach out quickly to plan a personalized demonstration.',
  },
  resources: {
    label: 'Resources',
    heading: 'Explore before you start',
    links: [
      { label: 'Guides', href: '/guides?lang=en' },
      { label: 'Blog', href: '/blog?lang=en' },
      { label: 'Pricing', href: '/pricing?lang=en' },
    ],
  },
};

const dictionary = { fr, en } as const;

export function getHomeContent(locale: Locale): HomeContent {
  return dictionary[locale];
}
