import type { Locale } from '@/lib/site/locale';

/**
 * Design Lab demonstration copy for LAB-03. Lab copy only, never final marketing copy.
 * Nothing here invents customers, testimonials, certifications, usage numbers or ROI. Values that are not backed by
 * the product are labelled as demonstration data.
 */
type Prim = { name: string; use: string; avoid: string };
type Feature = { title: string; text: string; meta?: string };

const fr = {
  zone: {
    title: 'Rythme de page et contenu',
    lead: 'Comment une page CORO reste distinctive après le héros : espace éditorial, surfaces techniques, grand média, information structurée, preuve et transitions clair / sombre. Aucune étude n’est une page de production.',
    rule: 'Règle du Lab : aucune étude ne répète 3 cartes flottantes identiques (ou plus) comme motif dominant.',
    surfaceRule: 'Le papier d’architecte est contextuel, pas universel.',
    families: [['Architectural', 'Surface douce, grande photo, filets et repères.'], ['Opérationnel', 'Marine, blanc et terrain : personnes, état, processus.'], ['Technique', 'Papier, plans, index et cartouches.']] as (readonly [string, string])[],
    primitives: 'Primitives',
    studies: 'Études de rythme',
    heroRef: 'Héros de référence',
    openView: 'Ouvrir la vue isolée (avec le héros)',
    use: 'Utiliser',
    avoid: 'Éviter',
  },
  prim: {
    statement: { name: 'SectionStatement', use: 'Une seule idée, juste après un héros.', avoid: 'Ne pas empiler, ne pas en faire une carte.' } as Prim,
    editorial: { name: 'EditorialBlock + SplitContent', use: 'Expliquer sans mur de texte ; texte / média ou média / texte, proportions asymétriques.', avoid: 'Ni 50/50 systématique, ni bloc flottant.' } as Prim,
    media: { name: 'MediaFrame', use: 'Photo (10 px sur les coins visibles) ou média technique (cadre 4 px + cartouche).', avoid: 'Pas d’ombre, pas de carte autour de chaque image.' } as Prim,
    features: { name: 'FeatureIndex', use: 'Capacités (rows) ou étapes (steps) : numérotation et filets.', avoid: 'Pas de cinq cartes à icône. La séquence horizontale est rejetée.' } as Prim,
    proof: { name: 'SectionProof', use: 'Preuve réelle ou exemple étiqueté « démo ».', avoid: 'Aucun logo, témoignage, certification ou chiffre inventé.' } as Prim,
    metric: { name: 'MetricComposition', use: 'Un chiffre dominant et ses dimensions en lignes.', avoid: 'Pas de grille de tuiles de métriques.' } as Prim,
    accordion: { name: 'Accordion', use: 'Contenu secondaire, FAQ (details / summary natifs).', avoid: 'Pas d’information essentielle cachée.' } as Prim,
  },
  a: {
    heroName: 'HeroSignature (A2)',
    statement: { before: 'Un plan n’est utile que lorsqu’il devient une ', em: 'capacité d’action', after: '.' },
    statementLabel: 'Principe',
    support: 'CORO relie les plans, les personnes et l’information opérationnelle pour que la préparation devienne une action coordonnée.',
    splitLabel: 'Le bâtiment',
    splitHeading: 'Tout commence par le bâtiment réel.',
    splitBody: ['Chaque plan, chaque procédure et chaque rôle se rattache à un lieu précis : l’entrée, l’étage, l’issue, le point de rassemblement.', 'CORO garde cette relation visible, du document jusqu’au terrain.'],
    splitItems: ['Plans rattachés aux niveaux', 'Procédures liées aux lieux', 'Rôles d’urgence par bâtiment'],
    splitCta: 'Voir la plateforme',
    mediaAlt: 'Entrée d’une tour de bureaux en fin de journée : hall vitré, personnes qui entrent, parvis en pierre.',
    mediaCaption: 'Entrée principale · bâtiment de démonstration',
    featuresLabel: 'Du plan au maintien',
    featuresHeading: 'De la structure au maintien.',
    featuresList: 'Étapes du cycle documentaire',
    features: [
      { title: 'Plans structurés', text: 'Organiser les informations du bâtiment et les procédures.' },
      { title: 'Validation', text: 'Faire réviser le contenu par les responsables.' },
      { title: 'Approbation', text: 'Approuver une version précise du document.' },
      { title: 'Diffusion', text: 'Rendre la version approuvée accessible aux parties prenantes.' },
      { title: 'Mise à jour', text: 'Maintenir le document à jour lorsque le bâtiment change.' },
    ] as Feature[],
    proofLabel: 'Preuve',
    proofHeading: 'Chaque approbation laisse une trace.',
    proofLead: 'Le cycle documentaire du portail client conserve l’approbation, la signature et l’historique des versions.',
    proofDemo: 'Capture réelle · données de démonstration',
    proofAlt: 'Capture du portail client : document PMU exporté, progression reçu / consulté / signé, approbation, signatures et historique des versions.',
    proofCartouche: ['Portail client', 'Cycle documentaire', 'Démo'] as readonly [string, string, string],
    proofFacts: [['Approbation', 'Enregistrée avec le nom et la date.'], ['Signature', 'Suivie par destinataire.'], ['Historique', 'Une entrée par version.']] as (readonly [string, string])[],
    ctaLabel: 'CTA — emplacement (LAB-07)',
    ctaText: 'Voir CORO sur votre bâtiment.',
    ctaButton: 'Demander une démonstration',
  },
  b: {
    heroName: 'HeroOperational',
    statement: { before: 'Quand la situation change, il faut savoir ', em: 'qui est là', after: '.' },
    statementLabel: 'Opérations',
    support: 'Occupation, rôles et procédures réunis dans une seule vue de commandement, avant, pendant et après l’événement.',
    infoLabel: 'Mesure',
    infoHeading: 'Mesurer la préparation, pas seulement la conformité.',
    infoBody: ['L’Indice CORO agrège quatre composantes pondérées et montre où la préparation est solide et où elle ne l’est pas.'],
    metricLabel: 'Indice CORO',
    metricDemo: 'Démo',
    metricNote: 'Valeurs de démonstration, non réelles.',
    dimensionsLabel: 'Composantes de l’indice (démonstration)',
    dimensions: [{ label: 'Rôles', value: 82 }, { label: 'Qualifications', value: 76 }, { label: 'Plans', value: 68 }, { label: 'Exercices', value: 85 }],
    fieldLabel: 'Sur le terrain',
    fieldHeading: 'Une évacuation se joue dans l’escalier.',
    fieldAlt: 'Un membre de l’équipe d’évacuation en gilet jaune guide des personnes dans un escalier vers la sortie de secours.',
    fieldCaption: 'Équipe d’évacuation · escalier de secours · image de démonstration',
    processLabel: 'Processus',
    processHeading: 'Une réponse structurée, de la détection au retour à la normale.',
    processLead: 'Chaque étape a un responsable et laisse une trace exploitable pour la revue.',
    processList: 'Étapes de la réponse à un incident',
    process: [
      { title: 'Détecter', text: 'Recevoir et qualifier le signal.' },
      { title: 'Évaluer', text: 'Analyser la situation.' },
      { title: 'Mobiliser', text: 'Activer les équipes et les ressources.' },
      { title: 'Coordonner', text: 'Suivre les actions sur le terrain.' },
      { title: 'Informer', text: 'Prévenir les parties prenantes.' },
      { title: 'Rétablir', text: 'Revenir à la normale et documenter.' },
    ] as Feature[],
    recoveryLabel: 'Après l’événement',
    recoveryHeading: 'Apprendre de chaque incident.',
    recoveryBody: ['Le retour d’expérience relie ce qui s’est passé aux actions correctives, pour améliorer la préparation suivante.'],
    recoveryItems: ['Chronologie et décisions conservées', 'Recommandations et actions correctives', 'Version mise à jour du plan'],
    recoveryCta: 'Voir le retour d’expérience',
  },
  c: {
    heroName: 'HeroTechnical',
    editorialLabel: 'Documents',
    editorialHeading: 'Des documents structurés à partir du bâtiment.',
    editorialBody: ['Une seule description du bâtiment alimente les documents : moins de ressaisie, des versions cohérentes.'],
    editorialItems: ['Procédures présélectionnées selon le bâtiment', 'Approbation et export PDF bilingue', 'Historique des versions'],
    deskAlt: 'Un bureau avec des classeurs de plans, un plan d’étage annoté et un ordinateur portable affichant un bâtiment.',
    deskCaption: 'Plans et classeurs · image de démonstration',
    indexLabel: 'Index technique',
    indexHeading: 'Trois documents, une même source de données.',
    indexList: 'Documents disponibles',
    index: [
      { title: 'Plan de mesures d’urgence', text: 'Rôles, procédures et mesures à entreprendre.', meta: 'PMU' },
      { title: 'Plan de sécurité incendie', text: 'Prévention, évacuation et intervention incendie.', meta: 'PSI' },
      { title: 'Plan de continuité des activités', text: 'Maintenir les opérations critiques.', meta: 'PCA' },
    ] as Feature[],
    planLabel: 'Planche',
    planHeading: 'Le plan reste la référence.',
    planBody: ['Les documents pointent vers les plans du bâtiment : élévation, coupe, plans d’étage.'],
    planAlt: 'Planche de dessin bleue d’un bâtiment de démonstration : élévation, coupe transversale, plans et axonométrie.',
    planCartouche: ['Planche 01', 'Élévation · coupe · plans', 'Échelle 1:200 · Démo'] as readonly [string, string, string],
    proofLabel: 'Sortie',
    proofHeading: 'Le même document, dans les deux langues.',
    proofLead: 'Les documents produits sont bilingues, avec le même niveau de détail en français et en anglais.',
    proofTitle: 'Exemple de sortie bilingue',
    proofDemo: 'Démo',
    proofNote: 'Extrait de démonstration.',
    proofLabelAria: 'Exemple de sortie bilingue',
    proofPairs: [['Plan de mesures d’urgence', 'Emergency measures plan'], ['Version approuvée', 'Approved version'], ['Point de rassemblement', 'Assembly point'], ['Équipe d’évacuation', 'Evacuation team']] as (readonly [string, string])[],
    faqLabel: 'Questions',
    faqHeading: 'Questions fréquentes.',
    faqList: 'Questions fréquentes',
    faq: [
      { id: 'q1', question: 'Quelle est la différence entre un PMU, un PSI et un PCA, et lequel faut-il produire en premier pour un bâtiment existant ?', answer: 'Le PMU décrit les mesures d’urgence et les rôles, le PSI concerne la sécurité incendie, le PCA la continuité des activités. L’ordre dépend des obligations applicables à votre organisation ; CORO structure les trois à partir des mêmes données. (Contenu de démonstration.)' },
      { id: 'q2', question: 'Les documents sont-ils disponibles en français et en anglais ?', answer: 'Oui : l’export PDF est bilingue. (Contenu de démonstration.)' },
      { id: 'q3', question: 'Peut-on conserver l’historique des versions ?', answer: 'Oui : chaque version approuvée est conservée avec sa date. (Contenu de démonstration.)' },
    ],
  },
};

type RhythmCopy = typeof fr;

const en: RhythmCopy = {
  zone: {
    title: 'Page rhythm and content',
    lead: 'How a CORO page stays distinctive after the hero: editorial space, technical surfaces, large media, structured information, proof and light / dark transitions. No study is a production page.',
    rule: 'Lab rule: no study repeats 3 or more identical floating cards as its dominant pattern.',
    surfaceRule: 'Architectural paper is contextual, not universal.',
    families: [['Architectural', 'Soft surface, large photography, rules and references.'], ['Operational', 'Navy, white and field: people, state, process.'], ['Technical', 'Paper, plans, indexing and cartouches.']],
    primitives: 'Primitives',
    studies: 'Rhythm studies',
    heroRef: 'Reference hero',
    openView: 'Open the isolated view (with the hero)',
    use: 'Use',
    avoid: 'Avoid',
  },
  prim: {
    statement: { name: 'SectionStatement', use: 'One idea, right after a hero.', avoid: 'Do not stack them or turn them into a card.' },
    editorial: { name: 'EditorialBlock + SplitContent', use: 'Explain without a wall of text; text / media or media / text, asymmetric proportions.', avoid: 'No systematic 50/50, no floating block.' },
    media: { name: 'MediaFrame', use: 'Photo (10px on visible corners) or technical media (4px frame + cartouche).', avoid: 'No shadow, no card around every image.' },
    features: { name: 'FeatureIndex', use: 'Capabilities (rows) or steps (steps): numbering and hairlines.', avoid: 'No five icon cards. The horizontal sequence is rejected.' },
    proof: { name: 'SectionProof', use: 'Real evidence or an example labelled demo.', avoid: 'No invented logo, testimonial, certification or figure.' },
    metric: { name: 'MetricComposition', use: 'One dominant figure and its dimensions as lines.', avoid: 'No grid of metric tiles.' },
    accordion: { name: 'Accordion', use: 'Secondary content, FAQ (native details / summary).', avoid: 'Do not hide essential information.' },
  },
  a: {
    heroName: 'HeroSignature (A2)',
    statement: { before: 'A plan is only useful when it becomes the ', em: 'capacity to act', after: '.' },
    statementLabel: 'Principle',
    support: 'CORO connects plans, people and operational information so preparation can become coordinated action.',
    splitLabel: 'The building',
    splitHeading: 'Everything starts with the real building.',
    splitBody: ['Every plan, procedure and role attaches to a precise place: the entrance, the floor, the exit, the assembly point.', 'CORO keeps that relationship visible, from the document to the field.'],
    splitItems: ['Plans attached to levels', 'Procedures linked to places', 'Emergency roles per building'],
    splitCta: 'See the platform',
    mediaAlt: 'Entrance of an office tower at the end of the day: glass lobby, people walking in, stone plaza.',
    mediaCaption: 'Main entrance · demonstration building',
    featuresLabel: 'From plan to upkeep',
    featuresHeading: 'From structure to upkeep.',
    featuresList: 'Steps of the document cycle',
    features: [
      { title: 'Structured plans', text: 'Organize building information and procedures.' },
      { title: 'Validation', text: 'Have the content reviewed by the people in charge.' },
      { title: 'Approval', text: 'Approve one precise version of the document.' },
      { title: 'Distribution', text: 'Make the approved version available to stakeholders.' },
      { title: 'Updates', text: 'Keep the document current when the building changes.' },
    ],
    proofLabel: 'Evidence',
    proofHeading: 'Every approval leaves a trace.',
    proofLead: 'The client portal document cycle keeps the approval, the signature and the version history.',
    proofDemo: 'Real capture · demonstration data',
    proofAlt: 'Client portal capture: exported PMU document, received / viewed / signed progress, approval, signatures and version history.',
    proofCartouche: ['Client portal', 'Document cycle', 'Demo'],
    proofFacts: [['Approval', 'Recorded with name and date.'], ['Signature', 'Tracked per recipient.'], ['History', 'One entry per version.']],
    ctaLabel: 'CTA — placeholder (LAB-07)',
    ctaText: 'See CORO on your building.',
    ctaButton: 'Request a demo',
  },
  b: {
    heroName: 'HeroOperational',
    statement: { before: 'When the situation changes, you need to know ', em: 'who is there', after: '.' },
    statementLabel: 'Operations',
    support: 'Occupancy, roles and procedures brought together in one command view, before, during and after the event.',
    infoLabel: 'Measure',
    infoHeading: 'Measure preparedness, not only compliance.',
    infoBody: ['The CORO Index aggregates four weighted components and shows where preparedness is solid and where it is not.'],
    metricLabel: 'CORO Index',
    metricDemo: 'Demo',
    metricNote: 'Demonstration values, not real.',
    dimensionsLabel: 'Index components (demonstration)',
    dimensions: [{ label: 'Roles', value: 82 }, { label: 'Qualifications', value: 76 }, { label: 'Plans', value: 68 }, { label: 'Exercises', value: 85 }],
    fieldLabel: 'In the field',
    fieldHeading: 'An evacuation is decided on the stairs.',
    fieldAlt: 'An evacuation team member in a yellow vest guides people down a stairwell towards the emergency exit.',
    fieldCaption: 'Evacuation team · emergency stairwell · demonstration image',
    processLabel: 'Process',
    processHeading: 'A structured response, from detection to return to normal.',
    processLead: 'Every step has an owner and leaves a usable trace for the review.',
    processList: 'Incident response steps',
    process: [
      { title: 'Detect', text: 'Receive and qualify the signal.' },
      { title: 'Assess', text: 'Analyze the situation.' },
      { title: 'Mobilize', text: 'Activate teams and resources.' },
      { title: 'Coordinate', text: 'Follow actions in the field.' },
      { title: 'Inform', text: 'Notify stakeholders.' },
      { title: 'Recover', text: 'Return to normal and document.' },
    ],
    recoveryLabel: 'After the event',
    recoveryHeading: 'Learn from every incident.',
    recoveryBody: ['The debrief links what happened to corrective actions, to improve the next round of preparedness.'],
    recoveryItems: ['Timeline and decisions kept', 'Recommendations and corrective actions', 'Updated version of the plan'],
    recoveryCta: 'See the debrief',
  },
  c: {
    heroName: 'HeroTechnical',
    editorialLabel: 'Documents',
    editorialHeading: 'Documents structured from the building.',
    editorialBody: ['A single description of the building feeds the documents: less re-entry, consistent versions.'],
    editorialItems: ['Procedures pre-selected for the building', 'Approval and bilingual PDF export', 'Version history'],
    deskAlt: 'A desk with binders of plans, an annotated floor plan and a laptop showing a building.',
    deskCaption: 'Plans and binders · demonstration image',
    indexLabel: 'Technical index',
    indexHeading: 'Three documents, one source of data.',
    indexList: 'Available documents',
    index: [
      { title: 'Emergency measures plan', text: 'Roles, procedures and measures to take.', meta: 'PMU' },
      { title: 'Fire safety plan', text: 'Prevention, evacuation and fire response.', meta: 'PSI' },
      { title: 'Business continuity plan', text: 'Keep critical operations running.', meta: 'PCA' },
    ],
    planLabel: 'Drawing sheet',
    planHeading: 'The plan stays the reference.',
    planBody: ['Documents point to the building plans: elevation, section, floor plans.'],
    planAlt: 'Blue drawing sheet of a demonstration building: elevation, cross-section, plans and axonometric view.',
    planCartouche: ['Sheet 01', 'Elevation · section · plans', 'Scale 1:200 · Demo'],
    proofLabel: 'Output',
    proofHeading: 'The same document, in both languages.',
    proofLead: 'Generated documents are bilingual, with the same level of detail in French and English.',
    proofTitle: 'Bilingual output example',
    proofDemo: 'Demo',
    proofNote: 'Demonstration excerpt.',
    proofLabelAria: 'Bilingual output example',
    proofPairs: [['Plan de mesures d’urgence', 'Emergency measures plan'], ['Version approuvée', 'Approved version'], ['Point de rassemblement', 'Assembly point'], ['Équipe d’évacuation', 'Evacuation team']],
    faqLabel: 'Questions',
    faqHeading: 'Frequently asked questions.',
    faqList: 'Frequently asked questions',
    faq: [
      { id: 'q1', question: 'What is the difference between an emergency measures plan, a fire safety plan and a business continuity plan, and which one should be produced first for an existing building?', answer: 'The emergency measures plan describes measures and roles, the fire safety plan covers fire safety, the continuity plan covers keeping operations running. The order depends on the obligations that apply to your organization; CORO structures all three from the same data. (Demonstration content.)' },
      { id: 'q2', question: 'Are documents available in French and English?', answer: 'Yes: the PDF export is bilingual. (Demonstration content.)' },
      { id: 'q3', question: 'Can the version history be kept?', answer: 'Yes: every approved version is kept with its date. (Demonstration content.)' },
    ],
  },
};

export const rhythmCopy: Record<Locale, RhythmCopy> = { fr, en };
