import { createHash } from 'crypto';

export const PROFESSIONAL_DIRECT_V1 = Object.freeze({
  code: 'professional-direct',
  version: 'v1',
  labelFr: 'CORO Professional — DIRECT — CAD',
  labelEn: 'CORO Professional — DIRECT — CAD',
  priceBook: Object.freeze({
    code: 'CORO_PROFESSIONAL_DIRECT_CAD',
    name: 'CORO Professional — DIRECT — CAD',
    audience: 'DIRECT' as const,
    currency: 'CAD',
  }),
  components: Object.freeze([
    Object.freeze({
      code: 'CORO_PROFESSIONAL_ANNUAL',
      nameFr: 'CORO Professional',
      nameEn: 'CORO Professional',
      pricingModel: 'CAPACITY_BAND' as const,
      chargeType: 'RECURRING' as const,
      revenueCategory: 'SAAS' as const,
      billingPeriod: 'YEAR' as const,
      metric: 'SITE' as const,
      displayOrder: 10,
      tiers: Object.freeze([
        [1, 11, 450000],
        [11, 31, 750000],
        [31, 46, 950000],
        [46, 61, 1150000],
        [61, 76, 1350000],
        [76, 101, 1550000],
        [101, 126, 1750000],
        [126, 151, 1900000],
        [151, 176, 2100000],
        [176, 201, 2250000],
      ] as const),
    }),
    Object.freeze({
      code: 'CORO_PROFESSIONAL_IMPLEMENTATION_STANDARD',
      nameFr: 'Implantation Standard',
      nameEn: 'Standard Implementation',
      pricingModel: 'FLAT' as const,
      chargeType: 'ONE_TIME' as const,
      revenueCategory: 'IMPLEMENTATION' as const,
      metric: 'FIXED' as const,
      amountMinor: '250000',
      displayOrder: 20,
    }),
    Object.freeze({
      code: 'CORO_PROFESSIONAL_IMPLEMENTATION_ADVANCED',
      nameFr: 'Implantation avancée',
      nameEn: 'Advanced Implementation',
      pricingModel: 'FLAT' as const,
      chargeType: 'ONE_TIME' as const,
      revenueCategory: 'IMPLEMENTATION' as const,
      metric: 'FIXED' as const,
      amountMinor: '500000',
      displayOrder: 30,
    }),
    Object.freeze({
      code: 'DOCUMENT_COMPLIANCE_DELIVERY_HOUR',
      nameFr: 'Service professionnel Delivery',
      nameEn: 'Delivery Professional Service',
      pricingModel: 'PER_UNIT' as const,
      chargeType: 'ONE_TIME' as const,
      revenueCategory: 'PROFESSIONAL_SERVICE' as const,
      metric: 'HOUR' as const,
      amountMinor: '17500',
      displayOrder: 40,
    }),
    Object.freeze({
      code: 'DOCUMENT_COMPLIANCE_SENIOR_REVIEW_HOUR',
      nameFr: 'Service professionnel senior / technique',
      nameEn: 'Senior / Technical Professional Service',
      pricingModel: 'PER_UNIT' as const,
      chargeType: 'ONE_TIME' as const,
      revenueCategory: 'PROFESSIONAL_SERVICE' as const,
      metric: 'HOUR' as const,
      amountMinor: '22500',
      displayOrder: 50,
    }),
  ]),
  cost: Object.freeze({
    code: 'CORO_PROFESSIONAL_DIRECT_COST',
    name: 'CORO Professional — DIRECT — coûts',
    currency: 'CAD',
    methodologyCode: 'direct-cost',
    methodologyVersion: 'v2',
    values: Object.freeze([
      Object.freeze({
        assumptionCode: 'LOADED_DIRECT_DELIVERY_COST',
        assumptionVersion: 'v1',
        scopeKey: 'ROLE:DELIVERY_PROFESSIONAL',
        valueType: 'MONEY' as const,
        moneyMinorValue: '5000',
        currency: 'CAD',
        unit: 'minor/hour',
      }),
      Object.freeze({
        assumptionCode: 'LOADED_DIRECT_DELIVERY_COST',
        assumptionVersion: 'v1',
        scopeKey: 'ROLE:SENIOR_REVIEWER',
        valueType: 'MONEY' as const,
        moneyMinorValue: '7000',
        currency: 'CAD',
        unit: 'minor/hour',
      }),
      Object.freeze({
        assumptionCode: 'STANDARD_DELIVERY_EFFORT',
        assumptionVersion: 'v1',
        scopeKey: 'COMPONENT:CORO_PROFESSIONAL_IMPLEMENTATION_STANDARD',
        valueType: 'DECIMAL' as const,
        decimalValue: '16',
        unit: 'hour',
      }),
      Object.freeze({
        assumptionCode: 'STANDARD_DELIVERY_EFFORT',
        assumptionVersion: 'v1',
        scopeKey: 'COMPONENT:CORO_PROFESSIONAL_IMPLEMENTATION_ADVANCED',
        valueType: 'DECIMAL' as const,
        decimalValue: '24',
        unit: 'hour',
      }),
      Object.freeze({
        assumptionCode: 'STANDARD_SENIOR_REVIEW_EFFORT',
        assumptionVersion: 'v1',
        scopeKey: 'COMPONENT:CORO_PROFESSIONAL_IMPLEMENTATION_ADVANCED',
        valueType: 'DECIMAL' as const,
        decimalValue: '4',
        unit: 'hour',
      }),
    ]),
  }),
  policies: Object.freeze({
    valueAnalysis: false,
    partner: false,
    sentinelle: false,
    population: false,
    incidentOps: false,
    standardAbove200: false,
    exactlyOneImplementation: true,
  }),
});

export const COMMERCIAL_CONFIGURATION_DEFINITIONS = Object.freeze([
  PROFESSIONAL_DIRECT_V1,
]);
export const stableHash = (value: unknown) =>
  createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const definitionFingerprint = (definition = PROFESSIONAL_DIRECT_V1) =>
  stableHash(definition);
