// ============================================================
// CORO — P015 : Découverte de colis suspect
// Toujours présent dans PMU et PSI
// ============================================================

import { ProcedureTemplate, COLORS, sid } from './types';

const CODE = 'P015';

export const P015_COLIS_SUSPECT: ProcedureTemplate = {
  id: 'p015_colis_suspect',
  code: CODE,
  titleFR: 'DÉCOUVERTE DE COLIS SUSPECT',
  titleEN: 'DISCOVERY OF A SUSPICIOUS PACKAGE',
  icon: '📦',
  headerColor: COLORS.dark,
  activationRule: 'always',
  documentTypes: ['PMU', 'PSI'],
  roleSections: [
    // ── Coordonnateur d'urgence ────────────────────────────
    {
      roleCode: 'ROLE-CU',
      roleLabelFR: 'Coordonnateur d\'urgence',
      roleLabelEN: 'Emergency Coordinator',
      headerColor: COLORS.dark,
      steps: [
        // ── Définition et reconnaissance ────────────────────
        {
          id: sid(CODE, 1),
          textFR: '**Définition et reconnaissance**',
          textEN: '**Definition and recognition**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 2),
          textFR: 'Considérer comme suspect toute enveloppe ou colis (valise, boîte, pot, etc.) dont l\'apparence ou le contexte soulève un doute',
          textEN: 'Consider suspicious any envelope or package (suitcase, box, jar, etc.) whose appearance or context raises doubt',
          isBold: false,
        },
        {
          id: sid(CODE, 3),
          textFR: 'Traiter toute situation avec prudence, sans présumer qu\'il s\'agit du seul colis potentiel',
          textEN: 'Handle every situation with caution, without assuming it is the only potential package',
          isBold: false,
        },
        {
          id: sid(CODE, 4),
          textFR: 'Caractéristiques d\'un colis suspect :',
          textEN: 'Characteristics of a suspicious package:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 5),
              textFR: 'Présence de poudre, liquide, fils métalliques apparents ou piles',
              textEN: 'Presence of powder, liquid, visible wires, or batteries',
              isList: true,
            },
            {
              id: sid(CODE, 6),
              textFR: 'Emballage décoloré, taché d\'huile, recouvert de cristaux, ayant des fuites ou suintant',
              textEN: 'Discolored packaging, oil-stained, covered in crystals, leaking, or seeping',
              isList: true,
            },
            {
              id: sid(CODE, 7),
              textFR: 'Odeur inhabituelle ou son anormal',
              textEN: 'Unusual odour or abnormal sound',
              isList: true,
            },
            {
              id: sid(CODE, 8),
              textFR: 'Affranchissement excessif, absence d\'adresse de retour ou fausse adresse',
              textEN: 'Excessive postage, missing or false return address',
              isList: true,
            },
            {
              id: sid(CODE, 9),
              textFR: 'Mentions spéciales inhabituelles (ex. : « urgent », « privé », « pas de rayons X »)',
              textEN: 'Unusual special markings (e.g., "urgent", "private", "no X-ray")',
              isList: true,
            },
            {
              id: sid(CODE, 10),
              textFR: 'Écriture irrégulière, fautes d\'orthographe, titre générique du destinataire (ex. : « Président »)',
              textEN: 'Irregular handwriting, spelling errors, generic recipient title (e.g., "President")',
              isList: true,
            },
            {
              id: sid(CODE, 11),
              textFR: 'Colis abandonné dans un endroit inhabituel (hall, toilette, cage d\'escalier)',
              textEN: 'Package abandoned in an unusual location (lobby, restroom, stairwell)',
              isList: true,
            },
          ],
        },
        // ── Détection ou signal d'un colis suspect ──────────
        {
          id: sid(CODE, 12),
          textFR: '**Détection ou signal d\'un colis suspect**',
          textEN: '**Detection or report of a suspicious package**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 13),
          textFR: 'Recevoir le signalement d\'un agent, gestionnaire ou occupant',
          textEN: 'Receive the report from an agent, manager, or occupant',
          isBold: false,
        },
        {
          id: sid(CODE, 14),
          textFR: '**Ne pas toucher, remuer, sentir ni déplacer le colis**',
          textEN: '**Do not touch, move, smell, or disturb the package**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 15),
          textFR: '**Ne pas utiliser de téléphone cellulaire ou radio à proximité du colis** — risque d\'activation',
          textEN: '**Do not use cell phones or radios near the package** — risk of activation',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 16),
          textFR: 'Noter :',
          textEN: 'Note:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 17),
              textFR: 'Localisation exacte',
              textEN: 'Exact location',
              isList: true,
            },
            {
              id: sid(CODE, 18),
              textFR: 'Description physique du colis',
              textEN: 'Physical description of the package',
              isList: true,
            },
            {
              id: sid(CODE, 19),
              textFR: 'Nom du découvreur',
              textEN: 'Name of the person who found it',
              isList: true,
            },
            {
              id: sid(CODE, 20),
              textFR: 'Heure approximative du dépôt (si connue)',
              textEN: 'Approximate time of deposit (if known)',
              isList: true,
            },
          ],
        },
        // ── Évaluation et premières mesures ─────────────────
        {
          id: sid(CODE, 21),
          textFR: '**Évaluation et premières mesures de sécurité**',
          textEN: '**Assessment and initial security measures**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 22),
          textFR: 'Utiliser les caméras de surveillance pour tenter d\'identifier qui a déposé l\'objet, depuis combien de temps et tout comportement suspect',
          textEN: 'Use surveillance cameras to try to identify who left the object, how long ago, and any suspicious behaviour',
          isBold: false,
        },
        {
          id: sid(CODE, 23),
          textFR: 'Définir un périmètre de sécurité autour du colis',
          textEN: 'Define a safety perimeter around the package',
          isBold: false,
        },
        {
          id: sid(CODE, 24),
          textFR: 'Demander à un agent de verrouiller les accès au secteur si sécuritaire',
          textEN: 'Ask an agent to lock access to the sector if safe to do so',
          isBold: false,
        },
        {
          id: sid(CODE, 25),
          textFR: 'Évacuer calmement uniquement la zone immédiate si nécessaire',
          textEN: 'Calmly evacuate only the immediate area if necessary',
          isBold: false,
        },
        // ── Avis aux autorités et communication interne ─────
        {
          id: sid(CODE, 26),
          textFR: '**Avis aux autorités et communication interne**',
          textEN: '**Notification to authorities and internal communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 27),
          textFR: 'Appeler immédiatement le 9-1-1 et transmettre :',
          textEN: 'Immediately call 9-1-1 and transmit:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 28),
              textFR: 'Adresse : [ADRESSE COMPLÈTE DU SITE]',
              textEN: 'Address: [COMPLETE SITE ADDRESS]',
              isList: true,
            },
            {
              id: sid(CODE, 29),
              textFR: 'Localisation précise du colis',
              textEN: 'Precise location of the package',
              isList: true,
            },
            {
              id: sid(CODE, 30),
              textFR: 'Périmètre sécurisé en place',
              textEN: 'Safety perimeter in place',
              isList: true,
            },
            {
              id: sid(CODE, 31),
              textFR: 'Demande d\'une équipe spécialisée',
              textEN: 'Request for a specialized team',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 32),
          textFR: 'Informer les gestionnaires via le groupe Teams :',
          textEN: 'Inform managers via the Teams group:',
          isBold: false,
        },
        {
          id: sid(CODE, 33),
          textFR: 'COLIS SUSPECT détecté au [lieu]. Secteur sécurisé. Merci de ne pas circuler près de cette zone. Plus d\'infos à suivre.',
          textEN: 'SUSPICIOUS PACKAGE detected at [location]. Sector secured. Please do not circulate near this area. More info to follow.',
          isBold: false,
          isRed: true,
        },
        // ── Soutien aux services d'urgence ──────────────────
        {
          id: sid(CODE, 34),
          textFR: '**Soutien aux services d\'urgence**',
          textEN: '**Support to emergency services**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 35),
          textFR: 'Déléguer un agent à l\'extérieur pour accueillir les policiers ou l\'escouade spécialisée',
          textEN: 'Delegate an agent outside to welcome police or the specialized squad',
          isBold: false,
        },
        {
          id: sid(CODE, 36),
          textFR: 'Fournir :',
          textEN: 'Provide:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 37),
              textFR: 'Historique de la détection',
              textEN: 'Detection history',
              isList: true,
            },
            {
              id: sid(CODE, 38),
              textFR: 'Clés et cartes d\'accès',
              textEN: 'Keys and access cards',
              isList: true,
            },
            {
              id: sid(CODE, 39),
              textFR: 'Images de caméras (si pertinent)',
              textEN: 'Camera footage (if relevant)',
              isList: true,
            },
            {
              id: sid(CODE, 40),
              textFR: 'Plan d\'accès au secteur',
              textEN: 'Sector access plan',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 41),
          textFR: 'Suivre les consignes policières sans les contredire',
          textEN: 'Follow police instructions without contradiction',
          isBold: false,
        },
        // ── Fin de l'intervention et reprise ────────────────
        {
          id: sid(CODE, 42),
          textFR: '**Fin de l\'intervention et reprise**',
          textEN: '**End of intervention and resumption**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 43),
          textFR: 'Attendre l\'autorisation du service de police pour lever le périmètre',
          textEN: 'Wait for police authorization to lift the perimeter',
          isBold: false,
        },
        {
          id: sid(CODE, 44),
          textFR: 'Informer les gestionnaires via Teams :',
          textEN: 'Inform managers via Teams:',
          isBold: false,
        },
        {
          id: sid(CODE, 45),
          textFR: 'Fin d\'intervention colis suspect. Reprise normale des opérations.',
          textEN: 'End of suspicious package intervention. Normal operations resuming.',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 46),
          textFR: 'Rédiger un rapport complet incluant :',
          textEN: 'Write a complete report including:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 47),
              textFR: 'Heure de signalement',
              textEN: 'Time of report',
              isList: true,
            },
            {
              id: sid(CODE, 48),
              textFR: 'Description du colis',
              textEN: 'Package description',
              isList: true,
            },
            {
              id: sid(CODE, 49),
              textFR: 'Actions entreprises',
              textEN: 'Actions taken',
              isList: true,
            },
            {
              id: sid(CODE, 50),
              textFR: 'Personnes informées',
              textEN: 'Persons notified',
              isList: true,
            },
            {
              id: sid(CODE, 51),
              textFR: 'Numéro d\'intervention du service de police',
              textEN: 'Police service intervention number',
              isList: true,
            },
            {
              id: sid(CODE, 52),
              textFR: 'Recommandations futures',
              textEN: 'Future recommendations',
              isList: true,
            },
          ],
        },
      ],
    },
    // ── Responsable de secteur ─────────────────────────────
    {
      roleCode: 'ROLE-RS',
      roleLabelFR: 'Responsable de secteur',
      roleLabelEN: 'Sector Supervisor',
      headerColor: COLORS.dark,
      steps: [
        {
          id: sid(CODE, 53),
          textFR: '**Réception de l\'avertissement**',
          textEN: '**Receiving the warning**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 54),
          textFR: 'Recevoir l\'avis du coordonnateur via Teams :',
          textEN: 'Receive notice from coordinator via Teams:',
          isBold: false,
        },
        {
          id: sid(CODE, 55),
          textFR: 'COLIS SUSPECT détecté au [lieu]. Secteur sécurisé. Merci de ne pas circuler près de cette zone. Plus d\'infos à suivre.',
          textEN: 'SUSPICIOUS PACKAGE detected at [location]. Sector secured. Please do not circulate near this area. More info to follow.',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 56),
          textFR: 'Accuser réception du message et vérifier si le secteur est concerné',
          textEN: 'Acknowledge the message and verify if the sector is affected',
          isBold: false,
        },
        {
          id: sid(CODE, 57),
          textFR: '**Mesures immédiates**',
          textEN: '**Immediate measures**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 58),
          textFR: 'Suspendre tout déplacement non essentiel vers la zone à risque',
          textEN: 'Suspend all non-essential movement toward the risk area',
          isBold: false,
        },
        {
          id: sid(CODE, 59),
          textFR: 'Éloigner calmement toute personne se trouvant près du colis ou du périmètre',
          textEN: 'Calmly move away anyone near the package or perimeter',
          isBold: false,
        },
        {
          id: sid(CODE, 60),
          textFR: '**Ne jamais manipuler l\'objet suspect**',
          textEN: '**Never handle the suspicious object**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 61),
          textFR: '**Collaboration et mise à jour**',
          textEN: '**Collaboration and updates**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 62),
          textFR: 'Rester disponible pour communication via Teams',
          textEN: 'Remain available for communication via Teams',
          isBold: false,
        },
        {
          id: sid(CODE, 63),
          textFR: 'Signaler immédiatement tout comportement suspect ou activité anormale',
          textEN: 'Immediately report any suspicious behaviour or abnormal activity',
          isBold: false,
        },
        {
          id: sid(CODE, 64),
          textFR: 'Ne pas évacuer sans ordre explicite du coordonnateur',
          textEN: 'Do not evacuate without explicit order from the coordinator',
          isBold: false,
        },
        {
          id: sid(CODE, 65),
          textFR: '**Après l\'intervention**',
          textEN: '**After the intervention**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 66),
          textFR: 'Attendre le message officiel de fin d\'incident via Teams :',
          textEN: 'Wait for the official end-of-incident message via Teams:',
          isBold: false,
        },
        {
          id: sid(CODE, 67),
          textFR: 'Fin d\'intervention colis suspect. Reprise normale des opérations.',
          textEN: 'End of suspicious package intervention. Normal operations resuming.',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 68),
          textFR: 'Rassurer les employés et rétablir les opérations',
          textEN: 'Reassure employees and restore operations',
          isBold: false,
        },
        {
          id: sid(CODE, 69),
          textFR: 'Fournir un bref compte rendu au coordonnateur si requis',
          textEN: 'Provide a brief report to the coordinator if required',
          isBold: false,
        },
      ],
    },
    // ── Équipe de première intervention ───────────────────
    {
      roleCode: 'ROLE-EPI',
      roleLabelFR: 'Équipe de première intervention',
      roleLabelEN: 'First Response Team',
      headerColor: COLORS.dark,
      steps: [
        {
          id: sid(CODE, 70),
          textFR: '**Réception de l\'alerte**',
          textEN: '**Receiving the alert**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 71),
          textFR: 'Recevoir l\'avis du coordonnateur d\'urgence concernant la détection d\'un colis suspect',
          textEN: 'Receive notice from the emergency coordinator regarding detection of a suspicious package',
          isBold: false,
        },
        {
          id: sid(CODE, 72),
          textFR: '**Ne pas approcher ni toucher l\'objet suspect**',
          textEN: '**Do not approach or touch the suspicious object**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 73),
          textFR: 'Se rendre à proximité uniquement sur ordre du coordonnateur et si la situation est sécuritaire',
          textEN: 'Approach only on coordinator\'s order and if the situation is safe',
          isBold: false,
        },
        {
          id: sid(CODE, 74),
          textFR: '**Sécurisation du périmètre**',
          textEN: '**Perimeter security**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 75),
          textFR: 'Éloigner toute personne de la zone et créer un périmètre de sécurité',
          textEN: 'Move all persons away from the area and create a safety perimeter',
          isBold: false,
        },
        {
          id: sid(CODE, 76),
          textFR: 'Utiliser des moyens physiques (ruban, cônes) si disponibles',
          textEN: 'Use physical means (tape, cones) if available',
          isBold: false,
        },
        {
          id: sid(CODE, 77),
          textFR: 'Refuser tout accès à la zone à toute personne non autorisée, y compris le personnel interne',
          textEN: 'Deny access to the area to any unauthorized person, including internal staff',
          isBold: false,
        },
        {
          id: sid(CODE, 78),
          textFR: '**Fouille de sécurité** (en l\'absence de localisation connue — sur ordre du coordonnateur seulement)',
          textEN: '**Security search** (when location is unknown — on coordinator\'s order only)',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 79),
          textFR: 'Former des équipes de deux personnes minimum et diviser la zone en sections',
          textEN: 'Form teams of at least two persons and divide the area into sections',
          isBold: false,
        },
        {
          id: sid(CODE, 80),
          textFR: 'Réaliser une fouille visuelle et auditive uniquement, sans toucher :',
          textEN: 'Conduct a visual and auditory search only, without touching:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 81),
              textFR: 'Plancher, sous les meubles, sur les meubles, plafond (si anomalies visibles)',
              textEN: 'Floor, under furniture, on furniture, ceiling (if visible anomalies)',
              isList: true,
            },
            {
              id: sid(CODE, 82),
              textFR: 'Tout contenant inhabituel ou objet déplacé',
              textEN: 'Any unusual container or displaced object',
              isList: true,
            },
            {
              id: sid(CODE, 83),
              textFR: 'Fils apparents, sons inhabituels, odeurs chimiques ou de brûlé',
              textEN: 'Visible wires, unusual sounds, chemical or burning odours',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 84),
          textFR: 'Rapporter immédiatement toute découverte suspecte au coordonnateur, sans toucher',
          textEN: 'Immediately report any suspicious finding to the coordinator, without touching',
          isBold: false,
        },
        {
          id: sid(CODE, 85),
          textFR: '**Arrivée des services d\'urgence**',
          textEN: '**Arrival of emergency services**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 86),
          textFR: 'Accueillir les policiers ou l\'escouade spécialisée sur demande du coordonnateur',
          textEN: 'Welcome police or specialized squad on coordinator\'s request',
          isBold: false,
        },
        {
          id: sid(CODE, 87),
          textFR: 'Fournir : historique du signalement, accès rapide à la zone, accès aux caméras de surveillance',
          textEN: 'Provide: report history, quick access to the area, access to surveillance cameras',
          isBold: false,
        },
        {
          id: sid(CODE, 88),
          textFR: 'Retirer les balises physiques uniquement sur ordre du coordonnateur ou de la police',
          textEN: 'Remove physical markers only on coordinator\'s or police order',
          isBold: false,
        },
      ],
    },
  ],
  referenceImages: [
    {
      id: 'p015_img_01',
      captionFR: 'Gestion de courrier suspect — Défense nationale Canada',
      captionEN: 'Managing Suspicious Mail — National Defence Canada',
      srcFR: '/procedures/p015_colis_suspect_fr.jpg',
      srcEN: '/procedures/p015_colis_suspect_en.jpg',
    },
  ],
};