// ============================================================
// CORO — P101 : Déclenchement de l'alerte incendie (Industriel)
// Activé si : is_industrial + double_signal
// ============================================================

import { ProcedureTemplate, COLORS, sid } from './types';

const CODE = 'P101';

export const P101_ALERTE_INCENDIE_IND: ProcedureTemplate = {
  id: 'p101_alerte_incendie_ind',
  code: CODE,
  titleFR: 'DÉCLENCHEMENT DE L\'ALERTE INCENDIE',
  titleEN: 'FIRE ALERT ACTIVATION',
  icon: '🔔',
  headerColor: COLORS.fireAlert,
  activationRule: 'is_industrial',
  documentTypes: ['PMU', 'PSI'],
  phase: 'alerte',
  roleSections: [
    // ── Coordonnateur d'urgence ────────────────────────────
    {
      roleCode: 'ROLE-CU',
      roleLabelFR: 'Coordonnateur d\'urgence',
      roleLabelEN: 'Emergency Coordinator',
      headerColor: COLORS.fireAlert,
      steps: [
        {
          id: sid(CODE, 1),
          textFR: '**Vérification initiale**',
          textEN: '**Initial verification**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 2),
          textFR: 'Consulter le panneau d\'alarme incendie pour identifier la zone déclenchée et confirmer la réception du signal',
          textEN: 'Consult the fire alarm panel to identify the triggered zone and confirm signal reception',
          isBold: false,
        },
        {
          id: sid(CODE, 3),
          textFR: 'Informer l\'équipe de première intervention du type de détection (fumée, chaleur, sprinkler, déversement) et de l\'emplacement précis',
          textEN: 'Inform the first response team of the detection type (smoke, heat, sprinkler, spill) and precise location',
          isBold: false,
        },
        {
          id: sid(CODE, 4),
          textFR: 'Enfiler votre dossard de coordonnateur pour être clairement identifiable',
          textEN: 'Put on your coordinator vest to be clearly identifiable',
          isBold: false,
        },
        {
          id: sid(CODE, 5),
          textFR: 'Vérifier les manches à air et le sens du vent en cas de fuite probable de gaz ou d\'ammoniac, et informer l\'équipe de première intervention',
          textEN: 'Check wind socks and wind direction in case of probable gas or ammonia leak, and inform the first response team',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 6),
          textFR: 'Sans retour de l\'équipe de première intervention dans un délai de 3 à 5 minutes, activer l\'alarme générale au panneau si cela est possible',
          textEN: 'Without feedback from the first response team within 3 to 5 minutes, activate the general alarm at the panel if possible',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 7),
          textFR: '**Communication initiale**',
          textEN: '**Initial communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 8),
          textFR: 'Contacter le 9-1-1 immédiatement et fournir :',
          textEN: 'Contact 9-1-1 immediately and provide:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 9),
              textFR: 'L\'adresse complète du bâtiment : [ADRESSE COMPLÈTE DU SITE]',
              textEN: 'The complete building address: [COMPLETE SITE ADDRESS]',
              isList: true,
            },
            {
              id: sid(CODE, 10),
              textFR: 'Le secteur concerné et le type d\'incident',
              textEN: 'The affected sector and incident type',
              isList: true,
            },
            {
              id: sid(CODE, 11),
              textFR: 'Les matières dangereuses impliquées, s\'il y a lieu',
              textEN: 'Hazardous materials involved, if applicable',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 12),
          textFR: '**Coordination de l\'intervention**',
          textEN: '**Intervention coordination**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 13),
          textFR: 'Recevoir et évaluer le rapport verbal de l\'équipe de première intervention',
          textEN: 'Receive and evaluate the verbal report from the first response team',
          isBold: false,
        },
        {
          id: sid(CODE, 14),
          textFR: 'Si l\'alerte est non fondée, laisser le service d\'incendie silencer et réarmer le panneau d\'alarme après vérification',
          textEN: 'If the alert is unfounded, allow the fire department to silence and reset the alarm panel after verification',
          isBold: false,
        },
        {
          id: sid(CODE, 15),
          textFR: 'Si l\'alerte est fondée, activer l\'alarme générale en insérant la clé dans la station manuelle d\'alarme incendie et lancer la procédure d\'alarme incendie',
          textEN: 'If the alert is confirmed, activate the general alarm by inserting the key into the manual fire alarm station and initiate the fire alarm procedure',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 16),
          textFR: '**Accueil des services d\'urgence**',
          textEN: '**Receiving emergency services**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 17),
          textFR: 'Accueillir et guider le service incendie dès leur arrivée',
          textEN: 'Welcome and guide the fire department upon their arrival',
          isBold: false,
        },
        {
          id: sid(CODE, 18),
          textFR: 'Fournir les informations suivantes :',
          textEN: 'Provide the following information:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 19),
              textFR: 'Plan du site et accès techniques',
              textEN: 'Site plan and technical access points',
              isList: true,
            },
            {
              id: sid(CODE, 20),
              textFR: 'Produits dangereux ou zones à risque',
              textEN: 'Hazardous products or risk areas',
              isList: true,
            },
            {
              id: sid(CODE, 21),
              textFR: 'Emplacements des vannes, coupe-gaz et postes de commande',
              textEN: 'Locations of valves, gas shutoffs, and control stations',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 22),
          textFR: 'Rester disponible pour toute coordination jusqu\'à la levée de l\'alerte',
          textEN: 'Remain available for all coordination until the alert is lifted',
          isBold: false,
        },
        {
          id: sid(CODE, 23),
          textFR: '**Clôture et suivi de l\'incident** *(Sans alarme / évacuation générale)*',
          textEN: '**Incident closure and follow-up** *(Without alarm / general evacuation)*',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 24),
          textFR: 'Participer au débriefing avec l\'équipe d\'urgence pour analyser la réponse et identifier les améliorations',
          textEN: 'Participate in the debriefing with the emergency team to analyze the response and identify improvements',
          isBold: false,
        },
        {
          id: sid(CODE, 25),
          textFR: 'Rédiger un rapport d\'incident incluant : le type d\'alarme, les mesures prises, les observations et les leçons apprises',
          textEN: 'Write an incident report including: alarm type, measures taken, observations, and lessons learned',
          isBold: false,
        },
        {
          id: sid(CODE, 26),
          textFR: 'Mettre à jour le PMU si des modifications aux procédures ou aux équipements sont nécessaires',
          textEN: 'Update the ERP if modifications to procedures or equipment are necessary',
          isBold: false,
        },
      ],
    },
    // ── Équipe de première intervention ───────────────────
    {
      roleCode: 'ROLE-EPI',
      roleLabelFR: 'Équipe de première intervention',
      roleLabelEN: 'First Response Team',
      headerColor: COLORS.fireAlert,
      steps: [
        {
          id: sid(CODE, 27),
          textFR: '**Alerte immédiate**',
          textEN: '**Immediate alert**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 28),
          textFR: 'Dès le retentissement d\'une alarme ou la réception d\'un avis d\'incident, cesser immédiatement vos activités et activer votre radio portative',
          textEN: 'Upon hearing an alarm or receiving an incident notice, immediately stop all activities and activate your portable radio',
          isBold: false,
        },
        {
          id: sid(CODE, 29),
          textFR: '**Prise d\'informations**',
          textEN: '**Gathering information**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 30),
          textFR: 'Obtenir les détails fournis par le coordonnateur d\'urgence (type d\'incident, localisation, risques potentiels) avant de vous rendre sur place',
          textEN: 'Obtain details from the emergency coordinator (incident type, location, potential risks) before proceeding on site',
          isBold: false,
        },
        {
          id: sid(CODE, 31),
          textFR: '**Préparation de l\'équipement**',
          textEN: '**Equipment preparation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 32),
          textFR: 'Se munir d\'un extincteur portatif, d\'un EPI approprié (gants, lunettes, casque, masque, etc.) et rendre les risques visibles avant toute approche',
          textEN: 'Equip yourself with a portable fire extinguisher, appropriate PPE (gloves, goggles, helmet, mask, etc.) and make risks visible before any approach',
          isBold: false,
        },
        {
          id: sid(CODE, 33),
          textFR: '**Accompagnement obligatoire**',
          textEN: '**Mandatory accompaniment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 34),
          textFR: 'Intervenir toujours en binôme — un second membre de l\'équipe d\'urgence doit vous accompagner pour assurer votre sécurité et une intervention efficace',
          textEN: 'Always intervene in pairs — a second emergency team member must accompany you to ensure your safety and an effective intervention',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 35),
          textFR: '**Communication constante**',
          textEN: '**Constant communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 36),
          textFR: 'Informer en temps réel le coordonnateur d\'urgence de votre constatation et de vos actions (incendie confirmé ou non) — maintenir une communication radio claire et continue',
          textEN: 'Inform the emergency coordinator in real time of your findings and actions (fire confirmed or not) — maintain clear and continuous radio communication',
          isBold: false,
        },
        {
          id: sid(CODE, 37),
          textFR: '**Évacuation préventive**',
          textEN: '**Preventive evacuation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 38),
          textFR: 'Évacuer toute personne présente dans la zone à risque et fermer les accès pour limiter l\'exposition — éloigner les témoins et sécuriser le périmètre immédiat',
          textEN: 'Evacuate all persons in the risk area and close access points to limit exposure — move witnesses away and secure the immediate perimeter',
          isBold: false,
        },
        {
          id: sid(CODE, 39),
          textFR: '**Évaluation initiale**',
          textEN: '**Initial assessment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 40),
          textFR: 'Identifier la nature du risque (incendie, fuite, déversement, explosion, etc.) sans vous exposer — n\'intervenir que si la situation est maîtrisable et sécuritaire',
          textEN: 'Identify the nature of the risk (fire, leak, spill, explosion, etc.) without exposing yourself — only intervene if the situation is manageable and safe',
          isBold: false,
        },
        {
          id: sid(CODE, 41),
          textFR: 'Si un début d\'incendie est confirmé :',
          textEN: 'If a fire is confirmed:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 42),
              textFR: 'Utiliser un extincteur approprié si les conditions sont sécuritaires',
              textEN: 'Use an appropriate extinguisher if conditions are safe',
              isList: true,
            },
            {
              id: sid(CODE, 43),
              textFR: 'Même si le feu est maîtrisé, évacuer les occupants du secteur touché',
              textEN: 'Even if the fire is controlled, evacuate occupants from the affected sector',
              isList: true,
            },
            {
              id: sid(CODE, 44),
              textFR: 'Informer le coordonnateur d\'urgence de la situation et des actions entreprises',
              textEN: 'Inform the emergency coordinator of the situation and actions taken',
              isList: true,
            },
            {
              id: sid(CODE, 45),
              textFR: 'Activer la station manuelle d\'alarme incendie pour déclencher l\'évacuation générale',
              textEN: 'Activate the manual fire alarm station to trigger general evacuation',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 46),
          textFR: 'Si l\'alerte est non fondée :',
          textEN: 'If the alert is unfounded:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 47),
              textFR: 'Confirmer qu\'aucun danger immédiat n\'a été constaté',
              textEN: 'Confirm that no immediate danger was found',
              isList: true,
            },
            {
              id: sid(CODE, 48),
              textFR: 'Demeurer sur place jusqu\'à l\'arrivée du service incendie ou de l\'équipe technique pour soutien et validation finale',
              textEN: 'Remain on site until the fire department or technical team arrives for support and final validation',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 49),
          textFR: '**Après l\'incident** *(sans alarme générale)*',
          textEN: '**After the incident** *(without general alarm)*',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 50),
          textFR: 'Participer à la séance de bilan post-incident avec l\'équipe d\'urgence et le coordonnateur d\'urgence',
          textEN: 'Participate in the post-incident debrief session with the emergency team and emergency coordinator',
          isBold: false,
        },
        {
          id: sid(CODE, 51),
          textFR: 'Décrire vos observations, les actions techniques entreprises et toute défaillance constatée sur les systèmes du bâtiment',
          textEN: 'Describe your observations, technical actions taken, and any system failures observed',
          isBold: false,
        },
        {
          id: sid(CODE, 52),
          textFR: 'Contribuer au rapport d\'incident pour appuyer les mesures correctives et d\'amélioration',
          textEN: 'Contribute to the incident report to support corrective and improvement measures',
          isBold: false,
        },
        {
          id: sid(CODE, 53),
          textFR: '**Équipement requis**',
          textEN: '**Required equipment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 54),
          textFR: 'Radio portative fonctionnelle',
          textEN: 'Functional portable radio',
          isBold: false,
        },
        {
          id: sid(CODE, 55),
          textFR: 'Extincteur portatif adapté au risque',
          textEN: 'Portable extinguisher adapted to the risk',
          isBold: false,
        },
        {
          id: sid(CODE, 56),
          textFR: 'Détecteur portatif (gaz, vapeurs, etc.) si disponible',
          textEN: 'Portable detector (gas, vapors, etc.) if available',
          isBold: false,
        },
        {
          id: sid(CODE, 57),
          textFR: 'Équipements de protection individuelle (casque, gants, visière, bottes, masque respiratoire selon le risque)',
          textEN: 'Personal protective equipment (helmet, gloves, face shield, boots, respiratory mask depending on risk)',
          isBold: false,
        },
        {
          id: sid(CODE, 58),
          textFR: 'Trousseau de clés d\'urgence ou carte d\'accès sécurisée',
          textEN: 'Emergency key set or secure access card',
          isBold: false,
        },
      ],
    },
    // ── Responsable mécanique ──────────────────────────────
    {
      roleCode: 'ROLE-RM',
      roleLabelFR: 'Responsable mécanique du bâtiment',
      roleLabelEN: 'Building Mechanical Supervisor',
      headerColor: COLORS.fireAlert,
      steps: [
        {
          id: sid(CODE, 59),
          textFR: '**Rapport immédiat au poste de commandement**',
          textEN: '**Immediate report to the command post**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 60),
          textFR: 'Dès le déclenchement d\'une alerte, communiquer rapidement avec le poste de commandement, soit en personne, par radio portative ou tout autre moyen de communication fiable',
          textEN: 'Upon alert activation, quickly communicate with the command post, either in person, by portable radio, or any other reliable communication means',
          isBold: false,
        },
        {
          id: sid(CODE, 61),
          textFR: 'Maintenir une liaison constante avec le coordonnateur d\'urgence afin d\'assurer le suivi technique en temps réel',
          textEN: 'Maintain constant communication with the emergency coordinator to ensure real-time technical monitoring',
          isBold: false,
        },
        {
          id: sid(CODE, 62),
          textFR: '**Écoute active des directives**',
          textEN: '**Active listening for directives**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 63),
          textFR: 'Être attentif aux consignes du coordonnateur d\'urgence et prêt à intervenir selon les besoins — en cas d\'alarme incendie, appliquer immédiatement les procédures prévues à la section ALARME',
          textEN: 'Be attentive to the emergency coordinator\'s instructions and ready to intervene as needed — in case of fire alarm, immediately apply the procedures in the ALARM section',
          isBold: false,
        },
        {
          id: sid(CODE, 64),
          textFR: '**Préparation à l\'intervention technique**',
          textEN: '**Technical intervention preparation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 65),
          textFR: 'Se préparer à fournir toute information utile sur les systèmes mécaniques, électriques et électromécaniques du bâtiment (ventilation, génératrice, chauffage, ascenseurs, pompes, etc.)',
          textEN: 'Prepare to provide useful information on the building\'s mechanical, electrical, and electromechanical systems (ventilation, generator, heating, elevators, pumps, etc.)',
          isBold: false,
        },
        {
          id: sid(CODE, 66),
          textFR: 'Rassembler les schémas, plans techniques ou rapports nécessaires pour appuyer la décision opérationnelle',
          textEN: 'Gather diagrams, technical plans, or reports needed to support operational decisions',
          isBold: false,
        },
        {
          id: sid(CODE, 67),
          textFR: '**Surveillance des systèmes critiques**',
          textEN: '**Critical systems monitoring**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 68),
          textFR: 'Surveiller les équipements essentiels (HVAC, génératrices, systèmes de surpression, alimentation de secours)',
          textEN: 'Monitor essential equipment (HVAC, generators, pressurization systems, emergency power supply)',
          isBold: false,
        },
        {
          id: sid(CODE, 69),
          textFR: 'Intervenir uniquement si votre sécurité est assurée et si la situation ne présente aucun risque pour votre santé',
          textEN: 'Intervene only if your safety is assured and the situation presents no health risk',
          isBold: false,
        },
        {
          id: sid(CODE, 70),
          textFR: '**Collaboration avec les secours**',
          textEN: '**Collaboration with emergency services**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 71),
          textFR: 'Soutenir le coordonnateur d\'urgence et les services d\'incendie en fournissant les renseignements techniques sur les systèmes et les accès (vannes, alimentations, commandes)',
          textEN: 'Support the emergency coordinator and fire services by providing technical information on systems and access points (valves, power supplies, controls)',
          isBold: false,
        },
        {
          id: sid(CODE, 72),
          textFR: '**Maintien de la sécurité**',
          textEN: '**Safety maintenance**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 73),
          textFR: 'S\'assurer que toutes les actions techniques entreprises respectent les procédures internes, les normes de sécurité et ne compromettent pas l\'intégrité du personnel ou des installations',
          textEN: 'Ensure all technical actions comply with internal procedures, safety standards, and do not compromise the integrity of personnel or facilities',
          isBold: false,
        },
        {
          id: sid(CODE, 74),
          textFR: '**Réactivité en cas d\'évolution**',
          textEN: '**Reactivity in case of escalation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 75),
          textFR: 'Rester prêt à ajuster vos actions selon les nouvelles directives émises pendant la progression de l\'incident',
          textEN: 'Be ready to adjust your actions according to new directives issued during the progression of the incident',
          isBold: false,
        },
        {
          id: sid(CODE, 76),
          textFR: 'En cas de passage d\'une alerte à une alarme incendie, appliquer les procédures correspondantes à la section ALARME',
          textEN: 'In case of escalation from alert to fire alarm, apply the procedures in the ALARM section',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 77),
          textFR: '**Bilan post-événement**',
          textEN: '**Post-event assessment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 78),
          textFR: 'Participer à la séance de bilan post-incident avec l\'équipe d\'urgence et le coordonnateur d\'urgence',
          textEN: 'Participate in the post-incident debrief with the emergency team and emergency coordinator',
          isBold: false,
        },
        {
          id: sid(CODE, 79),
          textFR: 'Décrire vos observations, les actions techniques entreprises et toute défaillance constatée sur les systèmes du bâtiment',
          textEN: 'Describe your observations, technical actions, and any system failures observed',
          isBold: false,
        },
        {
          id: sid(CODE, 80),
          textFR: 'Contribuer au rapport d\'incident pour appuyer les mesures correctives et d\'amélioration',
          textEN: 'Contribute to the incident report to support corrective and improvement measures',
          isBold: false,
        },
      ],
    },
    // ── Responsable du point de rassemblement ──────────────
    {
      roleCode: 'ROLE-RPR',
      roleLabelFR: 'Responsable du point de rassemblement',
      roleLabelEN: 'Assembly Point Supervisor',
      headerColor: COLORS.fireAlert,
      steps: [
        {
          id: sid(CODE, 81),
          textFR: '**Communication initiale**',
          textEN: '**Initial communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 82),
          textFR: 'Dès le déclenchement d\'une alerte, communiquer immédiatement avec le poste de commandement, soit en personne, soit par radio portative ou tout autre moyen de communication fiable',
          textEN: 'Upon alert activation, immediately communicate with the command post, either in person, by portable radio, or any other reliable communication means',
          isBold: false,
        },
        {
          id: sid(CODE, 83),
          textFR: 'Confirmer votre rôle, votre position et votre disponibilité',
          textEN: 'Confirm your role, position, and availability',
          isBold: false,
        },
        {
          id: sid(CODE, 84),
          textFR: '**Préparation du matériel**',
          textEN: '**Material preparation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 85),
          textFR: 'Rassembler l\'équipement nécessaire :',
          textEN: 'Gather necessary equipment:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 86),
              textFR: 'Dossard ou brassard d\'identification visible',
              textEN: 'Visible identification vest or armband',
              isList: true,
            },
            {
              id: sid(CODE, 87),
              textFR: 'Registre des secteurs d\'évacuation et stylo pour le suivi des occupants',
              textEN: 'Evacuation sector register and pen for occupant tracking',
              isList: true,
            },
            {
              id: sid(CODE, 88),
              textFR: 'Radio portative pour la communication avec le coordonnateur d\'urgence',
              textEN: 'Portable radio for communication with the emergency coordinator',
              isList: true,
            },
            {
              id: sid(CODE, 89),
              textFR: 'Trousse de premiers soins ou défibrillateur (si disponible)',
              textEN: 'First aid kit or defibrillator (if available)',
              isList: true,
            },
            {
              id: sid(CODE, 90),
              textFR: 'Plan du site ou carte d\'évacuation pour appuyer la coordination',
              textEN: 'Site plan or evacuation map to support coordination',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 91),
          textFR: 'Si l\'incident implique un risque de matières dangereuses, vérifier les manches à air pour confirmer le sens du vent et informer le coordonnateur d\'urgence avant de positionner les occupants',
          textEN: 'If the incident involves hazardous materials risk, check wind socks to confirm wind direction and inform the emergency coordinator before positioning occupants',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 92),
          textFR: '**Attente des instructions officielles**',
          textEN: '**Awaiting official instructions**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 93),
          textFR: 'Rester attentif aux directives du coordonnateur d\'urgence concernant la nécessité d\'une évacuation, le choix du point de rassemblement et la logistique d\'accueil des occupants',
          textEN: 'Stay attentive to the emergency coordinator\'s directives regarding evacuation necessity, assembly point choice, and occupant reception logistics',
          isBold: false,
        },
        {
          id: sid(CODE, 94),
          textFR: '**Préparation du site**',
          textEN: '**Site preparation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 95),
          textFR: 'S\'assurer que le point de rassemblement est dégagé, sécuritaire et accessible',
          textEN: 'Ensure the assembly point is clear, safe, and accessible',
          isBold: false,
        },
        {
          id: sid(CODE, 96),
          textFR: 'Si nécessaire, préparer un point de repli secondaire en cas de conditions défavorables (vents, fumées, matières dangereuses)',
          textEN: 'If necessary, prepare a secondary fallback point in case of unfavorable conditions (wind, smoke, hazardous materials)',
          isBold: false,
        },
        {
          id: sid(CODE, 97),
          textFR: '**Coordination de l\'évacuation**',
          textEN: '**Evacuation coordination**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 98),
          textFR: 'Si le signal d\'évacuation est donné, organiser la disposition des groupes selon les secteurs d\'origine',
          textEN: 'If the evacuation signal is given, organize group placement by sector of origin',
          isBold: false,
        },
        {
          id: sid(CODE, 99),
          textFR: 'Superviser la circulation vers le point de rassemblement et assurer un contrôle visuel de la foule sans gêner les opérations de secours',
          textEN: 'Supervise movement toward the assembly point and maintain visual crowd control without hindering rescue operations',
          isBold: false,
        },
        {
          id: sid(CODE, 100),
          textFR: '**Surveillance continue**',
          textEN: '**Continuous surveillance**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 101),
          textFR: 'Surveiller en permanence la situation autour du point de rassemblement',
          textEN: 'Continuously monitor the situation around the assembly point',
          isBold: false,
        },
        {
          id: sid(CODE, 102),
          textFR: 'Rester prêt à déplacer les occupants si la situation évolue (fumée, fuite, explosion, etc.)',
          textEN: 'Be ready to move occupants if the situation evolves (smoke, leak, explosion, etc.)',
          isBold: false,
        },
        {
          id: sid(CODE, 103),
          textFR: '**Communication constante**',
          textEN: '**Constant communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 104),
          textFR: 'Maintenir le contact avec le coordonnateur d\'urgence et transmettre : l\'état d\'avancement de l\'évacuation, le nombre approximatif d\'occupants présents, toute anomalie, blessure ou absence signalée',
          textEN: 'Maintain contact with the emergency coordinator and transmit: evacuation progress status, approximate number of occupants present, any anomaly, injury, or reported absence',
          isBold: false,
        },
        {
          id: sid(CODE, 105),
          textFR: '**Bilan et compte rendu**',
          textEN: '**Assessment and report**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 106),
          textFR: 'Participer à la séance de bilan post-incident avec le coordonnateur d\'urgence et l\'équipe d\'intervention',
          textEN: 'Participate in the post-incident debrief session with the emergency coordinator and response team',
          isBold: false,
        },
        {
          id: sid(CODE, 107),
          textFR: 'Présenter vos observations sur la gestion du rassemblement, les difficultés rencontrées et les points d\'amélioration identifiés',
          textEN: 'Present your observations on assembly management, difficulties encountered, and identified improvement points',
          isBold: false,
        },
        {
          id: sid(CODE, 108),
          textFR: '**Mise à jour du registre**',
          textEN: '**Register update**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 109),
          textFR: 'Compléter ou corriger le registre de présence selon les retours des responsables de secteur ou des superviseurs d\'évacuation',
          textEN: 'Complete or correct the attendance register based on feedback from sector supervisors or evacuation supervisors',
          isBold: false,
        },
        {
          id: sid(CODE, 110),
          textFR: 'Noter toute personne manquante, blessée ou prise en charge par les secours',
          textEN: 'Note any missing, injured, or emergency-assisted persons',
          isBold: false,
        },
      ],
    },
    // ── Responsable de secteur ─────────────────────────────
    {
      roleCode: 'ROLE-RS',
      roleLabelFR: 'Responsable de secteur',
      roleLabelEN: 'Sector Supervisor',
      headerColor: COLORS.fireAlert,
      steps: [
        {
          id: sid(CODE, 111),
          textFR: '**Informer et encadrer les occupants**',
          textEN: '**Inform and manage occupants**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 112),
          textFR: 'Annoncer clairement l\'alerte incendie ou la situation d\'urgence à tous les occupants de votre secteur',
          textEN: 'Clearly announce the fire alert or emergency situation to all occupants in your sector',
          isBold: false,
        },
        {
          id: sid(CODE, 113),
          textFR: 'Demander l\'arrêt immédiat des activités et la descente sécuritaire des équipements roulants',
          textEN: 'Request immediate activity stop and safe lowering of rolling equipment',
          isBold: false,
        },
        {
          id: sid(CODE, 114),
          textFR: 'Rappeler aux occupants de demeurer calmes, attentifs et prêts à suivre les consignes d\'évacuation',
          textEN: 'Remind occupants to remain calm, attentive, and ready to follow evacuation instructions',
          isBold: false,
        },
        {
          id: sid(CODE, 115),
          textFR: 'Permettre leur de récupérer leur manteau si cela est possible sans délai ni risque',
          textEN: 'Allow them to retrieve their coat if possible without delay or risk',
          isBold: false,
        },
        {
          id: sid(CODE, 116),
          textFR: '**Préparer à une évacuation éventuelle**',
          textEN: '**Prepare for possible evacuation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 117),
          textFR: 'S\'assurer que tous connaissent l\'emplacement des sorties de secours',
          textEN: 'Ensure all occupants know the location of emergency exits',
          isBold: false,
        },
        {
          id: sid(CODE, 118),
          textFR: 'Vérifier que les voies d\'évacuation sont dégagées, éclairées et accessibles',
          textEN: 'Verify that evacuation routes are clear, lit, and accessible',
          isBold: false,
        },
        {
          id: sid(CODE, 119),
          textFR: 'Confirmer la disponibilité des personnes désignées pour accompagner les individus à mobilité réduite',
          textEN: 'Confirm availability of persons designated to assist individuals with reduced mobility',
          isBold: false,
        },
        {
          id: sid(CODE, 120),
          textFR: '**Observer et signaler**',
          textEN: '**Observe and report**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 121),
          textFR: 'Surveiller activement l\'évolution de la situation dans votre secteur',
          textEN: 'Actively monitor the situation\'s evolution in your sector',
          isBold: false,
        },
        {
          id: sid(CODE, 122),
          textFR: 'Être prêt à ordonner l\'évacuation sur signal sonore ou à la directive du coordonnateur d\'urgence',
          textEN: 'Be ready to order evacuation upon audible signal or emergency coordinator\'s directive',
          isBold: false,
        },
        {
          id: sid(CODE, 123),
          textFR: 'Signaler sans délai tout incident, obstacle ou anomalie observé (fumée, bruit, odeur, déversement, etc.)',
          textEN: 'Immediately report any observed incident, obstacle, or anomaly (smoke, noise, odour, spill, etc.)',
          isBold: false,
        },
        {
          id: sid(CODE, 124),
          textFR: '**Maintenir la communication**',
          textEN: '**Maintain communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 125),
          textFR: 'Rester en liaison constante avec le poste de commandement à l\'aide de votre radio portative',
          textEN: 'Stay in constant contact with the command post using your portable radio',
          isBold: false,
        },
        {
          id: sid(CODE, 126),
          textFR: 'Transmettre les informations essentielles : état du secteur, nombre de personnes présentes, difficultés observées',
          textEN: 'Transmit essential information: sector status, number of persons present, observed difficulties',
          isBold: false,
        },
        {
          id: sid(CODE, 127),
          textFR: 'Confirmer toute action entreprise, notamment le début ou la fin de l\'évacuation',
          textEN: 'Confirm all actions taken, including the start or end of evacuation',
          isBold: false,
        },
        {
          id: sid(CODE, 128),
          textFR: '**Assurer la sécurité et le calme**',
          textEN: '**Ensure safety and calm**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 129),
          textFR: 'Veiller à ce que les occupants demeurent calmes et suivent les consignes sans précipitation',
          textEN: 'Ensure occupants remain calm and follow instructions without rushing',
          isBold: false,
        },
        {
          id: sid(CODE, 130),
          textFR: 'Préparer les équipements ou machines à un éventuel arrêt d\'urgence afin d\'éviter tout sur-accident',
          textEN: 'Prepare equipment or machines for a possible emergency stop to prevent secondary accidents',
          isBold: false,
        },
        {
          id: sid(CODE, 131),
          textFR: 'Recenser les personnes nécessitant une aide particulière pour l\'évacuation',
          textEN: 'Identify persons requiring special assistance for evacuation',
          isBold: false,
        },
        {
          id: sid(CODE, 132),
          textFR: '**Préparer la direction d\'évacuation**',
          textEN: '**Prepare evacuation direction**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 133),
          textFR: 'Dès le déclenchement du signal d\'alarme incendie, guider les occupants vers les issues désignées (voir section ALARME)',
          textEN: 'Upon fire alarm signal activation, guide occupants toward designated exits (see ALARM section)',
          isBold: false,
        },
        {
          id: sid(CODE, 134),
          textFR: '**Bilan et retour d\'expérience**',
          textEN: '**Assessment and feedback**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 135),
          textFR: 'Participer au bilan post-incident avec le coordonnateur d\'urgence et l\'équipe d\'intervention',
          textEN: 'Participate in the post-incident debrief with the emergency coordinator and response team',
          isBold: false,
        },
        {
          id: sid(CODE, 136),
          textFR: 'Fournir un retour sur : les délais d\'évacuation observés, les obstacles rencontrés, la conformité des issues, les comportements notables des occupants',
          textEN: 'Provide feedback on: observed evacuation times, obstacles encountered, exit compliance, notable occupant behaviours',
          isBold: false,
        },
        {
          id: sid(CODE, 137),
          textFR: 'Contribuer à la mise à jour du plan d\'évacuation et des registres d\'intervention',
          textEN: 'Contribute to updating the evacuation plan and intervention registers',
          isBold: false,
        },
      ],
    },
    // ── Chercheur(s) ───────────────────────────────────────
    {
      roleCode: 'ROLE-CHE',
      roleLabelFR: 'Chercheur(s)',
      roleLabelEN: 'Searcher(s)',
      headerColor: COLORS.fireAlert,
      steps: [
        {
          id: sid(CODE, 138),
          textFR: '**Préparation à la recherche**',
          textEN: '**Search preparation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 139),
          textFR: 'Dès le déclenchement d\'une alerte, se préparer à effectuer une inspection rapide et méthodique de la zone assignée',
          textEN: 'Upon alert activation, prepare to conduct a rapid and methodical inspection of the assigned area',
          isBold: false,
        },
        {
          id: sid(CODE, 140),
          textFR: 'S\'assurer d\'avoir votre radio portative, une lampe de poche et un dossard visible',
          textEN: 'Ensure you have your portable radio, a flashlight, and a visible vest',
          isBold: false,
        },
        {
          id: sid(CODE, 141),
          textFR: 'Agir uniquement lorsque la zone est jugée sécuritaire',
          textEN: 'Act only when the area is deemed safe',
          isBold: false,
        },
        {
          id: sid(CODE, 142),
          textFR: '**Inspection des espaces**',
          textEN: '**Space inspection**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 143),
          textFR: 'Inspecter en priorité les bureaux, ateliers, sanitaires, vestiaires et locaux techniques où des personnes pourraient se trouver',
          textEN: 'Prioritize inspection of offices, workshops, restrooms, locker rooms, and technical rooms where persons might be found',
          isBold: false,
        },
        {
          id: sid(CODE, 144),
          textFR: 'Rassembler les occupants dans un espace commun sécurisé à proximité, sans déclencher d\'évacuation prématurée',
          textEN: 'Gather occupants in a nearby secured common area, without triggering premature evacuation',
          isBold: false,
        },
        {
          id: sid(CODE, 145),
          textFR: '**Communication avec les occupants**',
          textEN: '**Communication with occupants**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 146),
          textFR: 'Informer calmement les occupants de la situation et de la nécessité de demeurer attentifs aux instructions officielles',
          textEN: 'Calmly inform occupants of the situation and the need to remain attentive to official instructions',
          isBold: false,
        },
        {
          id: sid(CODE, 147),
          textFR: 'Encourager la préparation sans provoquer de mouvement de panique',
          textEN: 'Encourage preparation without causing panic movement',
          isBold: false,
        },
        {
          id: sid(CODE, 148),
          textFR: '**Rapport immédiat au responsable de secteur**',
          textEN: '**Immediate report to sector supervisor**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 149),
          textFR: 'Dès que votre inspection est terminée, ou si vous observez un danger (fumée, fuite, bruit anormal, effondrement partiel, etc.), vous rapporter immédiatement au responsable de secteur',
          textEN: 'Once your inspection is complete, or if you observe a danger (smoke, leak, abnormal noise, partial collapse, etc.), immediately report to the sector supervisor',
          isBold: false,
        },
        {
          id: sid(CODE, 150),
          textFR: 'Fournir un rapport clair et concis indiquant :',
          textEN: 'Provide a clear and concise report indicating:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 151),
              textFR: 'Les zones inspectées et sécurisées',
              textEN: 'Inspected and secured areas',
              isList: true,
            },
            {
              id: sid(CODE, 152),
              textFR: 'Les personnes localisées et celles nécessitant une assistance',
              textEN: 'Located persons and those requiring assistance',
              isList: true,
            },
            {
              id: sid(CODE, 153),
              textFR: 'Tout risque potentiel observé dans votre périmètre',
              textEN: 'Any potential risk observed in your perimeter',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 154),
          textFR: '**Maintien de la position**',
          textEN: '**Maintaining position**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 155),
          textFR: 'Rester dans votre zone ou dans un endroit sûr, prêt à assister le responsable de secteur — ne pas initier d\'évacuation sans instruction officielle',
          textEN: 'Stay in your zone or a safe location, ready to assist the sector supervisor — do not initiate evacuation without official instruction',
          isBold: false,
        },
        {
          id: sid(CODE, 156),
          textFR: 'En cas de déclenchement du signal d\'évacuation, appliquer les consignes prévues à la section ALARME',
          textEN: 'Upon evacuation signal activation, apply the instructions in the ALARM section',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 157),
          textFR: '**Appui à l\'évacuation**',
          textEN: '**Evacuation support**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 158),
          textFR: 'Si l\'ordre d\'évacuation est donné, guider les occupants vers les sorties sécuritaires en vous assurant qu\'aucune personne ne demeure dans les locaux',
          textEN: 'If the evacuation order is given, guide occupants to safe exits ensuring no person remains in the premises',
          isBold: false,
        },
        {
          id: sid(CODE, 159),
          textFR: 'Fermer les portes derrière vous sans les verrouiller et rejoindre le point de rassemblement',
          textEN: 'Close doors behind you without locking them and proceed to the assembly point',
          isBold: false,
        },
        {
          id: sid(CODE, 160),
          textFR: '**Débriefing et amélioration continue**',
          textEN: '**Debriefing and continuous improvement**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 161),
          textFR: 'Participer au bilan post-incident avec votre responsable de secteur',
          textEN: 'Participate in the post-incident debrief with your sector supervisor',
          isBold: false,
        },
        {
          id: sid(CODE, 162),
          textFR: 'Signaler les difficultés rencontrées, les anomalies techniques ou comportementales observées, ainsi que les propositions d\'amélioration',
          textEN: 'Report difficulties encountered, technical or behavioural anomalies observed, and improvement proposals',
          isBold: false,
        },
      ],
    },
  ],
};