// ============================================================
// CORO — P104 : Fuite d'ammoniac (Industriel)
// Activé si : is_industrial + has_ammonia
// ============================================================

import { ProcedureTemplate, COLORS, sid } from './types';

const CODE = 'P104';

export const P104_FUITE_AMMONIAC_IND: ProcedureTemplate = {
  id: 'p104_fuite_ammoniac_ind',
  code: CODE,
  titleFR: 'FUITE D\'AMMONIAC',
  titleEN: 'AMMONIA LEAK',
  icon: '☣️',
  headerColor: COLORS.purple,
  activationRule: 'is_industrial',
  documentTypes: ['PMU', 'PSI'],
  roleSections: [
    // ── Coordonnateur d'urgence ────────────────────────────
    {
      roleCode: 'ROLE-CU',
      roleLabelFR: 'Coordonnateur d\'urgence',
      roleLabelEN: 'Emergency Coordinator',
      headerColor: COLORS.purple,
      steps: [
        {
          id: sid(CODE, 1),
          textFR: '**Signalement de la fuite**',
          textEN: '**Leak reporting**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 2),
          textFR: 'Dès qu\'une alarme de détection d\'ammoniac se déclenche ou qu\'une odeur piquante caractéristique est perçue, ordonner l\'alerte immédiate',
          textEN: 'As soon as an ammonia detection alarm activates or a characteristic pungent odour is detected, order immediate alert',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 3),
          textFR: 'Activer visuellement les stroboscopes et voyants d\'alerte sans utiliser d\'intercom ou de radio à proximité de la fuite',
          textEN: 'Visually activate strobes and alert indicators without using intercom or radio near the leak',
          isBold: false,
        },
        {
          id: sid(CODE, 4),
          textFR: 'S\'assurer que le personnel commence à évacuer la zone touchée sans délai',
          textEN: 'Ensure personnel begins evacuating the affected area without delay',
          isBold: false,
        },
        {
          id: sid(CODE, 5),
          textFR: '**Confirmation et évaluation initiale**',
          textEN: '**Confirmation and initial assessment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 6),
          textFR: 'Collaborer avec le responsable de la maintenance et les opérateurs qualifiés pour confirmer la nature de la fuite (gaz liquide, vapeur, tuyauterie, soupape)',
          textEN: 'Collaborate with the maintenance supervisor and qualified operators to confirm the nature of the leak (liquid gas, vapor, piping, valve)',
          isBold: false,
        },
        {
          id: sid(CODE, 7),
          textFR: 'Ne pas s\'approcher de la source tant que la concentration n\'est pas connue',
          textEN: 'Do not approach the source until the concentration is known',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 8),
          textFR: 'Vérifier l\'activation du système d\'alarme spécifique "ammoniac" (stroboscopes bleus)',
          textEN: 'Verify activation of the specific "ammonia" alarm system (blue strobes)',
          isBold: false,
        },
        {
          id: sid(CODE, 9),
          textFR: '**Observation environnementale**',
          textEN: '**Environmental observation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 10),
          textFR: 'Vérifier la direction des vents dominants afin d\'adapter les points de rassemblement et les voies d\'évacuation',
          textEN: 'Check prevailing wind direction to adapt assembly points and evacuation routes',
          isBold: false,
        },
        {
          id: sid(CODE, 11),
          textFR: 'Interdire tout déplacement vers la direction du vent',
          textEN: 'Prohibit any movement in the wind direction',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 12),
          textFR: '**Seuils de concentration et évacuation**',
          textEN: '**Concentration thresholds and evacuation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 13),
          textFR: 'À 25 ppm : évacuer immédiatement la zone locale concernée (valeur d\'exposition à court terme — CNESST) — s\'assurer que les responsables de secteur guident calmement le personnel vers les sorties',
          textEN: 'At 25 ppm: immediately evacuate the affected local area (short-term exposure value — CNESST) — ensure sector supervisors calmly guide personnel to exits',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 14),
          textFR: 'À 35 ppm ou plus : déclencher une évacuation générale du bâtiment et des zones adjacentes — déplacer les points de rassemblement à l\'opposé du vent',
          textEN: 'At 35 ppm or more: trigger general evacuation of the building and adjacent areas — move assembly points upwind',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 15),
          textFR: '**Communication interne prioritaire**',
          textEN: '**Priority internal communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 16),
          textFR: 'Informer rapidement : le responsable de la maintenance, les responsables des points de rassemblement, le coordonnateur d\'urgence adjoint et la sécurité industrielle',
          textEN: 'Quickly inform: the maintenance supervisor, assembly point supervisors, the deputy emergency coordinator, and industrial security',
          isBold: false,
        },
        {
          id: sid(CODE, 17),
          textFR: '**Utilisation des EPI et intervention technique**',
          textEN: '**PPE use and technical intervention**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 18),
          textFR: 'Si les conditions le permettent, autoriser les opérateurs formés et équipés d\'EPI adaptés (SCBA, combinaison chimique, gants butyle) à fermer la vanne d\'alimentation ou isoler la source',
          textEN: 'If conditions permit, authorize trained operators equipped with appropriate PPE (SCBA, chemical suit, butyl gloves) to close the supply valve or isolate the source',
          isBold: false,
        },
        {
          id: sid(CODE, 19),
          textFR: 'Ne pas tenter d\'intervention sans formation en espace confiné ou sans détection confirmée — si >250 ppm, vêtement entièrement encapsulé + SCBA obligatoires',
          textEN: 'Do not attempt intervention without confined space training or without confirmed detection — if >250 ppm, fully encapsulated suit + SCBA required',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 20),
          textFR: '**Contact avec les services d\'urgence (9-1-1)**',
          textEN: '**Contact with emergency services (9-1-1)**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 21),
          textFR: 'Fournir les informations suivantes :',
          textEN: 'Provide the following information:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 22),
              textFR: 'Adresse exacte du site et zone affectée (local technique, salle des machines, etc.)',
              textEN: 'Exact site address and affected area (technical room, machine room, etc.)',
              isList: true,
            },
            {
              id: sid(CODE, 23),
              textFR: 'Type d\'alarme ou de capteur ayant détecté la fuite (25, 35, 100 ppm)',
              textEN: 'Type of alarm or sensor that detected the leak (25, 35, 100 ppm)',
              isList: true,
            },
            {
              id: sid(CODE, 24),
              textFR: 'Nombre d\'employés exposés ou manquants',
              textEN: 'Number of exposed or missing employees',
              isList: true,
            },
            {
              id: sid(CODE, 25),
              textFR: 'Symptômes observés : toux, irritation, nausées, perte de conscience',
              textEN: 'Observed symptoms: cough, irritation, nausea, loss of consciousness',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 26),
          textFR: '**Coordination avec le fournisseur et les autorités**',
          textEN: '**Coordination with supplier and authorities**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 27),
          textFR: 'Fournisseur d\'ammoniac : contacter l\'entreprise contractuelle (transport ou entretien) pour assistance technique et validation de la neutralisation',
          textEN: 'Ammonia supplier: contact the contractual company (transport or maintenance) for technical assistance and neutralization validation',
          isBold: false,
        },
        {
          id: sid(CODE, 28),
          textFR: 'Environnement (MELCCFP) : signaler toute contamination (égouts, air, sols, eaux)',
          textEN: 'Environment (MELCCFP): report any contamination (sewers, air, soil, water)',
          isBold: false,
        },
        {
          id: sid(CODE, 29),
          textFR: 'CNESST : déclarer tout accident de travail ou exposition chimique',
          textEN: 'CNESST: declare any workplace accident or chemical exposure',
          isBold: false,
        },
        {
          id: sid(CODE, 30),
          textFR: 'Maintenir un contact constant avec les pompiers pour leur fournir les plans techniques, schémas de tuyauterie et fiches signalétiques (FDS)',
          textEN: 'Maintain constant contact with firefighters to provide technical plans, piping diagrams, and safety data sheets (SDS)',
          isBold: false,
        },
        {
          id: sid(CODE, 31),
          textFR: '**Gestion de la ventilation**',
          textEN: '**Ventilation management**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 32),
          textFR: 'Demander à l\'équipe technique de gérer la ventilation pour évacuer les vapeurs d\'ammoniac tout en évitant la dispersion vers les zones propres',
          textEN: 'Ask the technical team to manage ventilation to evacuate ammonia vapors while avoiding dispersion to clean areas',
          isBold: false,
        },
        {
          id: sid(CODE, 33),
          textFR: 'Si la fuite est contenue dans un local fermé, enclencher la ventilation par extraction selon les procédures internes',
          textEN: 'If the leak is contained in a closed room, activate extraction ventilation according to internal procedures',
          isBold: false,
        },
        {
          id: sid(CODE, 34),
          textFR: '**Neutralisation et nettoyage**',
          textEN: '**Neutralization and cleanup**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 35),
          textFR: 'Confier la neutralisation à des spécialistes certifiés (solution acide diluée, ventilation assistée)',
          textEN: 'Entrust neutralization to certified specialists (diluted acid solution, assisted ventilation)',
          isBold: false,
        },
        {
          id: sid(CODE, 36),
          textFR: 'S\'assurer qu\'une équipe de décontamination soit mobilisée pour le nettoyage, le rinçage et la vérification de la concentration résiduelle (< 25 ppm)',
          textEN: 'Ensure a decontamination team is mobilized for cleaning, rinsing, and verification of residual concentration (< 25 ppm)',
          isBold: false,
        },
        {
          id: sid(CODE, 37),
          textFR: '**Réintégration sécurisée**',
          textEN: '**Secured re-entry**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 38),
          textFR: 'Vérifier que les concentrations d\'ammoniac dans l\'air sont inférieures à 25 ppm (valeur d\'exposition à court terme — CNESST) avant d\'autoriser la reprise des activités',
          textEN: 'Verify ammonia concentrations in the air are below 25 ppm (short-term exposure value — CNESST) before authorizing resumption of activities',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 39),
          textFR: 'Attendre l\'autorisation écrite du service incendie avant d\'autoriser le retour du personnel',
          textEN: 'Wait for written authorization from the fire department before authorizing personnel return',
          isBold: false,
        },
        {
          id: sid(CODE, 40),
          textFR: '**Inspection technique**',
          textEN: '**Technical inspection**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 41),
          textFR: 'Demander une inspection complète des équipements par une firme spécialisée : systèmes de réfrigération, soupapes, joints, capteurs, compresseurs — documenter toute réparation ou remplacement',
          textEN: 'Request a complete equipment inspection by a specialized firm: refrigeration systems, valves, seals, sensors, compressors — document all repairs or replacements',
          isBold: false,
        },
        {
          id: sid(CODE, 42),
          textFR: '**Suivi médical**',
          textEN: '**Medical follow-up**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 43),
          textFR: 'Organiser un examen médical immédiat pour tout employé potentiellement exposé (tests respiratoires, oculaires, cutanés) — conserver les rapports dans les dossiers de santé-sécurité',
          textEN: 'Organize immediate medical examination for any potentially exposed employee (respiratory, ocular, cutaneous tests) — keep reports in health and safety files',
          isBold: false,
        },
        {
          id: sid(CODE, 44),
          textFR: '**Rapport d\'incident**',
          textEN: '**Incident report**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 45),
          textFR: 'Rédiger un rapport détaillé décrivant : chronologie des événements, causes probables de la fuite, mesures d\'urgence exécutées, actions correctives et recommandations',
          textEN: 'Write a detailed report describing: event timeline, probable causes of the leak, emergency measures executed, corrective actions and recommendations',
          isBold: false,
        },
        {
          id: sid(CODE, 46),
          textFR: '**Révision du PMU**',
          textEN: '**ERP revision**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 47),
          textFR: 'Intégrer l\'incident dans le registre des événements majeurs — analyser la performance de la détection, de la communication et de la coordination interservices',
          textEN: 'Integrate the incident into the major events register — analyze detection performance, communication, and inter-service coordination',
          isBold: false,
        },
        {
          id: sid(CODE, 48),
          textFR: '**Formation et sensibilisation**',
          textEN: '**Training and awareness**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 49),
          textFR: 'Organiser un retour d\'expérience avec le personnel impliqué — renforcer la formation annuelle sur les fuites d\'ammoniac et manipulations sécuritaires — effectuer un exercice de simulation dans les 3 mois suivant l\'incident',
          textEN: 'Organize a lessons-learned session with involved personnel — strengthen annual training on ammonia leaks and safe handling — conduct a simulation exercise within 3 months of the incident',
          isBold: false,
        },
      ],
    },
    // ── Responsable de la maintenance ──────────────────────
    {
      roleCode: 'ROLE-RM',
      roleLabelFR: 'Responsable de la maintenance',
      roleLabelEN: 'Maintenance Supervisor',
      headerColor: COLORS.purple,
      steps: [
        {
          id: sid(CODE, 50),
          textFR: '**Réception du signal d\'alarme**',
          textEN: '**Alarm signal reception**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 51),
          textFR: 'Dès la réception de l\'alarme provenant du détecteur ammoniac ou du coordonnateur d\'urgence :',
          textEN: 'Upon receiving the alarm from the ammonia detector or emergency coordinator:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 52),
              textFR: 'Prendre connaissance du type de signal (audible, stroboscopique, ou alarme de détection automatique)',
              textEN: 'Acknowledge the type of signal (audible, strobe, or automatic detection alarm)',
              isList: true,
            },
            {
              id: sid(CODE, 53),
              textFR: 'Noter les informations initiales : secteur, date, heure, lecture estimée de PPM',
              textEN: 'Note initial information: sector, date, time, estimated PPM reading',
              isList: true,
            },
            {
              id: sid(CODE, 54),
              textFR: 'Communiquer immédiatement avec le coordonnateur d\'urgence pour confirmer la situation et obtenir les directives de niveau d\'intervention',
              textEN: 'Immediately communicate with the emergency coordinator to confirm the situation and obtain intervention level directives',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 55),
          textFR: '**Vérification initiale à distance**',
          textEN: '**Initial remote verification**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 56),
          textFR: 'Se diriger vers la salle mécanique ou la zone identifiée en respectant la distance de sécurité indiquée par le capteur',
          textEN: 'Proceed to the mechanical room or identified area while respecting the safety distance indicated by the sensor',
          isBold: false,
        },
        {
          id: sid(CODE, 57),
          textFR: 'Avant toute approche :',
          textEN: 'Before any approach:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 58),
              textFR: 'Utiliser un détecteur portable pour confirmer la concentration (si l\'équipement est calibré et les conditions le permettent)',
              textEN: 'Use a portable detector to confirm concentration (if equipment is calibrated and conditions permit)',
              isList: true,
            },
            {
              id: sid(CODE, 59),
              textFR: 'Évaluer visuellement la présence de vapeurs visibles, de bruits anormaux (sifflement, fuite sous pression) ou d\'odeurs fortes',
              textEN: 'Visually assess presence of visible vapors, abnormal sounds (hissing, pressurized leak) or strong odors',
              isList: true,
            },
            {
              id: sid(CODE, 60),
              textFR: 'Ne pas pénétrer dans la salle si la lecture dépasse 35 ppm ou si la visibilité est compromise',
              textEN: 'Do not enter the room if the reading exceeds 35 ppm or if visibility is compromised',
              isList: true,
              isRed: true,
            },
          ],
        },
        {
          id: sid(CODE, 61),
          textFR: '**Transmission d\'informations**',
          textEN: '**Information transmission**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 62),
          textFR: 'Transmettre immédiatement au coordonnateur d\'urgence :',
          textEN: 'Immediately transmit to the emergency coordinator:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 63),
              textFR: 'Les lectures de concentration mesurées (PPM)',
              textEN: 'Measured concentration readings (PPM)',
              isList: true,
            },
            {
              id: sid(CODE, 64),
              textFR: 'Les observations visuelles (fuite apparente, givre, condensation, bruit)',
              textEN: 'Visual observations (apparent leak, frost, condensation, noise)',
              isList: true,
            },
            {
              id: sid(CODE, 65),
              textFR: 'Toute indication de danger immédiat (présence de pression, température anormale)',
              textEN: 'Any indication of immediate danger (pressure presence, abnormal temperature)',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 66),
          textFR: '**Évaluation des seuils critiques**',
          textEN: '**Critical threshold assessment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 67),
          textFR: 'Si la lecture est ≥ 25 ppm, signaler la nécessité d\'évacuer le personnel du secteur',
          textEN: 'If the reading is ≥ 25 ppm, report the need to evacuate sector personnel',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 68),
          textFR: 'Si la lecture est ≥ 35 ppm, demander au coordonnateur d\'urgence de déclencher l\'évacuation générale du bâtiment',
          textEN: 'If the reading is ≥ 35 ppm, ask the emergency coordinator to trigger general building evacuation',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 69),
          textFR: '**Appel à la firme d\'entretien**',
          textEN: '**Call to maintenance firm**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 70),
          textFR: 'Contacter sans délai la firme d\'entretien spécialisée pour le système d\'ammoniac',
          textEN: 'Immediately contact the specialized maintenance firm for the ammonia system',
          isBold: false,
        },
        {
          id: sid(CODE, 71),
          textFR: 'Fournir un rapport d\'alerte structuré incluant :',
          textEN: 'Provide a structured alert report including:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 72),
              textFR: 'Nature et emplacement présumés de la fuite',
              textEN: 'Presumed nature and location of the leak',
              isList: true,
            },
            {
              id: sid(CODE, 73),
              textFR: 'Conditions atmosphériques internes (PPM, visibilité, bruit, température)',
              textEN: 'Internal atmospheric conditions (PPM, visibility, noise, temperature)',
              isList: true,
            },
            {
              id: sid(CODE, 74),
              textFR: 'Mesures de sécurité déjà appliquées (ventilation, isolement électrique, verrouillage d\'accès)',
              textEN: 'Safety measures already applied (ventilation, electrical isolation, access lockout)',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 75),
          textFR: '**Préparation à l\'intervention**',
          textEN: '**Intervention preparation**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 76),
          textFR: 'Préparer le plan d\'accès sécurisé à la salle technique pour le technicien externe',
          textEN: 'Prepare the secure access plan to the technical room for the external technician',
          isBold: false,
        },
        {
          id: sid(CODE, 77),
          textFR: 'Rassembler et remettre les documents suivants :',
          textEN: 'Gather and hand over the following documents:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 78),
              textFR: 'Schéma des conduites d\'ammoniac et vannes d\'isolement',
              textEN: 'Ammonia pipe diagram and isolation valves',
              isList: true,
            },
            {
              id: sid(CODE, 79),
              textFR: 'Fiche de données de sécurité (FDS)',
              textEN: 'Safety data sheet (SDS)',
              isList: true,
            },
            {
              id: sid(CODE, 80),
              textFR: 'Dernier rapport d\'inspection ou d\'entretien préventif',
              textEN: 'Last inspection or preventive maintenance report',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 81),
          textFR: '**Communication continue**',
          textEN: '**Continuous communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 82),
          textFR: 'Maintenir un contact constant avec le coordonnateur d\'urgence, en le tenant informé : de l\'évolution des niveaux de PPM (toutes les 5 à 10 minutes), de l\'arrivée du technicien externe et de l\'heure prévue d\'intervention, de toute complication observée (nouvelle fuite, propagation, panne de ventilation)',
          textEN: 'Maintain constant contact with the emergency coordinator, keeping them informed: of PPM level evolution (every 5 to 10 minutes), of the external technician\'s arrival and expected intervention time, of any observed complication (new leak, propagation, ventilation failure)',
          isBold: false,
        },
        {
          id: sid(CODE, 83),
          textFR: '**Assistance au technicien externe**',
          textEN: '**External technician assistance**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 84),
          textFR: 'À l\'arrivée du technicien spécialisé : lui fournir un briefing complet sur la situation (PPM, secteur, progression de la fuite), lui donner accès à la zone concernée et assurer la présence d\'un agent de sécurité pour contrôler les entrées',
          textEN: 'Upon specialized technician arrival: provide a complete briefing on the situation (PPM, sector, leak progression), grant access to the affected area and ensure a security agent is present to control entries',
          isBold: false,
        },
        {
          id: sid(CODE, 85),
          textFR: 'Rester disponible pour l\'assister, sans intervenir directement sur le système à moins d\'être formé et équipé',
          textEN: 'Remain available to assist, without directly intervening on the system unless trained and equipped',
          isBold: false,
        },
        {
          id: sid(CODE, 86),
          textFR: '**Sécurité du périmètre**',
          textEN: '**Perimeter security**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 87),
          textFR: 'S\'assurer que le périmètre de sécurité autour de la salle d\'ammoniac reste dégagé',
          textEN: 'Ensure the security perimeter around the ammonia room remains clear',
          isBold: false,
        },
        {
          id: sid(CODE, 88),
          textFR: 'Interdire toute présence non essentielle, même après stabilisation de la situation',
          textEN: 'Prohibit any non-essential presence, even after situation stabilization',
          isBold: false,
        },
        {
          id: sid(CODE, 89),
          textFR: 'Vérifier que les voies d\'accès pompiers demeurent libres et que la ventilation est fonctionnelle',
          textEN: 'Verify firefighter access routes remain clear and ventilation is functional',
          isBold: false,
        },
        {
          id: sid(CODE, 90),
          textFR: '**Protection personnelle**',
          textEN: '**Personal protection**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 91),
          textFR: 'Ne jamais intervenir sans EPI complet (masque respiratoire SCBA, combinaison étanche, gants butyle, lunettes et bottes)',
          textEN: 'Never intervene without full PPE (SCBA respiratory mask, sealed suit, butyl gloves, goggles and boots)',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 92),
          textFR: 'Toute personne non équipée doit se maintenir en dehors du périmètre défini',
          textEN: 'Any unequipped person must remain outside the defined perimeter',
          isBold: false,
        },
        {
          id: sid(CODE, 93),
          textFR: '**Rapport et vérification finale**',
          textEN: '**Report and final verification**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 94),
          textFR: 'Une fois la situation stabilisée : informer le coordonnateur d\'urgence de la fin de l\'intervention et de la remise en état de sécurité, collaborer à la rédaction du rapport d\'incident (observations, mesures, niveaux mesurés, actions correctives), préparer un suivi post-incident avec la firme d\'entretien pour valider la remise en marche sécuritaire et éviter toute récurrence',
          textEN: 'Once situation stabilized: inform the emergency coordinator of intervention completion and safety restoration, collaborate on incident report writing (observations, measures, measured levels, corrective actions), prepare post-incident follow-up with maintenance firm to validate safe restart and prevent recurrence',
          isBold: false,
        },
        {
          id: sid(CODE, 95),
          textFR: '**Retour d\'expérience (RÉX)**',
          textEN: '**Lessons learned (RÉX)**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 96),
          textFR: 'Participer à la réunion post-incident pour documenter : les délais d\'intervention et les communications interservices, les défaillances techniques observées (capteurs, soupapes, alarmes), les améliorations à apporter au plan d\'entretien préventif',
          textEN: 'Participate in post-incident meeting to document: intervention times and inter-service communications, observed technical failures (sensors, valves, alarms), improvements to preventive maintenance plan',
          isBold: false,
        },
      ],
    },
    // ── Responsable du point de rassemblement ──────────────
    {
      roleCode: 'ROLE-RPR',
      roleLabelFR: 'Responsable du point de rassemblement',
      roleLabelEN: 'Assembly Point Supervisor',
      headerColor: COLORS.purple,
      steps: [
        {
          id: sid(CODE, 97),
          textFR: '**Communication initiale**',
          textEN: '**Initial communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 98),
          textFR: 'Dès le déclenchement de l\'alerte ammoniac, communiquer immédiatement avec le coordonnateur d\'urgence afin de : confirmer le point de rassemblement à activer selon la direction du vent, recevoir les instructions sur les zones à éviter et les itinéraires sécuritaires, confirmer le mode de communication (radio, téléphone d\'urgence, messagerie interne)',
          textEN: 'Upon ammonia alert activation, immediately communicate with the emergency coordinator to: confirm the assembly point to activate based on wind direction, receive instructions on areas to avoid and safe routes, confirm communication mode (radio, emergency phone, internal messaging)',
          isBold: false,
        },
        {
          id: sid(CODE, 99),
          textFR: '**Équipement requis**',
          textEN: '**Required equipment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 100),
          textFR: 'Enfiler le dossard d\'identification RPR',
          textEN: 'Put on the RPR identification vest',
          isBold: false,
        },
        {
          id: sid(CODE, 101),
          textFR: 'Se munir du registre des secteurs d\'évacuation et d\'un stylo ou tablette de suivi',
          textEN: 'Equip yourself with the evacuation sector register and a pen or tracking tablet',
          isBold: false,
        },
        {
          id: sid(CODE, 102),
          textFR: 'S\'assurer de disposer d\'un récepteur radio ou d\'un téléphone de communication d\'urgence pleinement fonctionnel',
          textEN: 'Ensure you have a fully functional emergency radio receiver or communication phone',
          isBold: false,
        },
        {
          id: sid(CODE, 103),
          textFR: 'Si possible, porter un EPI léger (gants, lunettes, masque filtrant ammoniaque type ABEK)',
          textEN: 'If possible, wear light PPE (gloves, goggles, ABEK-type ammonia filter mask)',
          isBold: false,
        },
        {
          id: sid(CODE, 104),
          textFR: '**Déplacement rapide et sécurisé**',
          textEN: '**Rapid and secured movement**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 105),
          textFR: 'Se diriger sans délai vers le point de rassemblement désigné en amont (côté opposé au vent dominant)',
          textEN: 'Proceed without delay to the designated upwind assembly point (opposite side from prevailing wind)',
          isBold: false,
        },
        {
          id: sid(CODE, 106),
          textFR: 'Surveiller les conditions atmosphériques :',
          textEN: 'Monitor atmospheric conditions:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 107),
              textFR: 'Si le vent change de direction, aviser le coordonnateur d\'urgence pour relocaliser le point de rassemblement si nécessaire',
              textEN: 'If wind changes direction, notify the emergency coordinator to relocate the assembly point if necessary',
              isList: true,
            },
            {
              id: sid(CODE, 108),
              textFR: 'Éviter toute zone basse où le gaz pourrait se concentrer (fossés, sous-sols, stationnements souterrains)',
              textEN: 'Avoid any low areas where gas could concentrate (ditches, basements, underground parking)',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 109),
          textFR: '**Établissement du périmètre**',
          textEN: '**Perimeter establishment**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 110),
          textFR: 'Délimiter clairement le périmètre du point de rassemblement à l\'aide de cônes, rubans ou barrières mobiles',
          textEN: 'Clearly delineate the assembly point perimeter using cones, tape, or mobile barriers',
          isBold: false,
        },
        {
          id: sid(CODE, 111),
          textFR: 'Organiser la zone de manière à : séparer les groupes d\'évacuation selon leur secteur d\'origine, garder un couloir d\'accès libre pour les premiers répondants et la circulation d\'urgence, empêcher tout retour vers le bâtiment avant autorisation',
          textEN: 'Organize the area to: separate evacuation groups by sector of origin, keep a clear access corridor for first responders and emergency traffic, prevent any return to the building before authorization',
          isBold: false,
        },
        {
          id: sid(CODE, 112),
          textFR: '**Accueil et direction**',
          textEN: '**Reception and direction**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 113),
          textFR: 'Accueillir les évacués dès leur arrivée et les inciter à demeurer calmes, regroupés et en amont du vent',
          textEN: 'Welcome evacuees upon arrival and encourage them to remain calm, grouped, and upwind',
          isBold: false,
        },
        {
          id: sid(CODE, 114),
          textFR: 'Rappeler les consignes de sécurité : ne pas fumer, ne pas utiliser de téléphone portable à proximité, attendre les instructions officielles avant tout déplacement',
          textEN: 'Remind safety instructions: no smoking, no cell phone use nearby, wait for official instructions before any movement',
          isBold: false,
        },
        {
          id: sid(CODE, 115),
          textFR: '**Collecte d\'informations**',
          textEN: '**Information collection**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 116),
          textFR: 'Collaborer avec les responsables de secteur pour recueillir les informations essentielles :',
          textEN: 'Collaborate with sector supervisors to gather essential information:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 117),
              textFR: 'Secteurs évacués et confirmation des zones visitées',
              textEN: 'Evacuated sectors and confirmation of visited areas',
              isList: true,
            },
            {
              id: sid(CODE, 118),
              textFR: 'Personnes manquantes, blessées ou exposées à l\'ammoniac',
              textEN: 'Missing, injured, or ammonia-exposed persons',
              isList: true,
            },
            {
              id: sid(CODE, 119),
              textFR: 'Secteurs non visités ou inaccessibles',
              textEN: 'Unvisited or inaccessible sectors',
              isList: true,
            },
            {
              id: sid(CODE, 120),
              textFR: 'Observations particulières (odeurs, visibilité, vent, symptômes)',
              textEN: 'Particular observations (odors, visibility, wind, symptoms)',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 121),
          textFR: '**Communication continue**',
          textEN: '**Continuous communication**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 122),
          textFR: 'Maintenir un lien radio constant avec le coordonnateur d\'urgence :',
          textEN: 'Maintain constant radio contact with the emergency coordinator:',
          isBold: false,
          subSteps: [
            {
              id: sid(CODE, 123),
              textFR: 'Transmettre les mises à jour sur le nombre d\'évacués présents',
              textEN: 'Transmit updates on the number of evacuees present',
              isList: true,
            },
            {
              id: sid(CODE, 124),
              textFR: 'Signaler toute personne nécessitant des soins médicaux ou présentant des signes d\'exposition (irritation, toux, brûlure oculaire)',
              textEN: 'Report any person requiring medical care or showing exposure signs (irritation, cough, eye burning)',
              isList: true,
            },
            {
              id: sid(CODE, 125),
              textFR: 'Indiquer tout changement dans la direction du vent ou l\'état de la zone',
              textEN: 'Indicate any change in wind direction or zone status',
              isList: true,
            },
          ],
        },
        {
          id: sid(CODE, 126),
          textFR: '**Sécurité du site**',
          textEN: '**Site security**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 127),
          textFR: 'Surveiller le périmètre pour éviter que quiconque ne retourne vers le bâtiment',
          textEN: 'Monitor the perimeter to prevent anyone from returning to the building',
          isBold: false,
        },
        {
          id: sid(CODE, 128),
          textFR: 'Orienter les intervenants d\'urgence vers le point d\'accès convenu avec le coordonnateur',
          textEN: 'Direct emergency responders to the access point agreed upon with the coordinator',
          isBold: false,
        },
        {
          id: sid(CODE, 129),
          textFR: 'En cas de propagation du nuage d\'ammoniac vers le point de rassemblement : diriger calmement le groupe vers le site de repli secondaire (préétabli selon le PMU), communiquer immédiatement la relocalisation au coordonnateur',
          textEN: 'If the ammonia cloud spreads toward the assembly point: calmly direct the group to the secondary fallback site (pre-established per ERP), immediately communicate relocation to the coordinator',
          isBold: false,
          isRed: true,
        },
        {
          id: sid(CODE, 130),
          textFR: '**Soutien aux premiers répondants**',
          textEN: '**Support to first responders**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 131),
          textFR: 'Fournir aux services d\'urgence ou à la firme d\'entretien : le registre des évacuations, les secteurs encore à vérifier, toute observation de symptômes ou d\'exposition',
          textEN: 'Provide emergency services or maintenance firm with: the evacuation register, sectors still to be verified, any symptom or exposure observations',
          isBold: false,
        },
        {
          id: sid(CODE, 132),
          textFR: '**Collaboration pour la réintégration**',
          textEN: '**Collaboration for re-entry**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 133),
          textFR: 'Collaborer avec le coordonnateur d\'urgence pour gérer la réintégration progressive : l\'accès ne doit être permis qu\'après validation des niveaux de PPM ≤ 25 ppm et confirmation du service d\'incendie, s\'assurer que les occupants regagnent le bâtiment par secteurs contrôlés',
          textEN: 'Collaborate with the emergency coordinator to manage progressive re-entry: access must only be permitted after validation of PPM levels ≤ 25 ppm and fire department confirmation, ensure occupants return to the building by controlled sectors',
          isBold: false,
        },
        {
          id: sid(CODE, 134),
          textFR: '**Bilan post-incident**',
          textEN: '**Post-incident debrief**',
          isBold: true,
          isRed: true,
        },
        {
          id: sid(CODE, 135),
          textFR: 'Participer à la séance de débriefing pour : identifier les forces et faiblesses de la gestion du rassemblement, évaluer la clarté des communications, la réactivité et la coordination interservices, proposer des améliorations concrètes pour les prochaines interventions (signalisation, fiches de suivi, cartographie du vent)',
          textEN: 'Participate in the debriefing session to: identify strengths and weaknesses of assembly management, evaluate communication clarity, reactivity and inter-service coordination, propose concrete improvements for future interventions (signage, tracking sheets, wind mapping)',
          isBold: false,
        },
      ],
    },
  ],
};