import { ProcedureTemplate, COLORS, sid } from './types';
const CODE = 'P118';
export const P118_ALARME_CO2_OCC: ProcedureTemplate = {
  id: 'p118_alarme_co2_occ', code: CODE,
  titleFR: 'ALARME DE DIOXYDE DE CARBONE (CO₂) — OCCUPANTS',
  titleEN: 'CARBON DIOXIDE (CO₂) ALARM — OCCUPANTS',
  icon: '🌫️', headerColor: COLORS.dark,
  activationRule: 'is_industrial', documentTypes: ['PMU', 'PSI'],
  roleSections: [{
    roleCode: 'ROLE-OCC', roleLabelFR: 'Occupants / Travailleurs', roleLabelEN: 'Occupants / Workers',
    headerColor: COLORS.dark,
    steps: [
      { id: sid(CODE,1), textFR: 'Cesser immédiatement toute activité dès que l\'alarme sonore ou le stroboscope se déclenche', textEN: 'Immediately stop all activity as soon as the audible alarm or strobe activates', isBold: false },
      { id: sid(CODE,2), textFR: 'Évacuer calmement la zone sans tenter de récupérer ses effets personnels — le dioxyde de carbone peut s\'accumuler au ras du sol et déplacer l\'oxygène vital, rendant la respiration difficile', textEN: 'Calmly evacuate the area without attempting to retrieve personal belongings — carbon dioxide can accumulate at ground level and displace vital oxygen, making breathing difficult', isBold: false, isRed: true },
      { id: sid(CODE,3), textFR: 'Se diriger rapidement vers les issues de secours désignées lors des exercices d\'évacuation — choisir la sortie la plus proche située à l\'écart du point de fuite ou de la zone basse où le gaz pourrait s\'accumuler', textEN: 'Quickly proceed to emergency exits designated during evacuation drills — choose the nearest exit away from the leak point or low area where gas could accumulate', isBold: false },
      { id: sid(CODE,4), textFR: 'Ne jamais revenir dans la zone affectée avant d\'avoir reçu l\'autorisation du service d\'incendie ou du coordonnateur d\'urgence', textEN: 'Never return to the affected area before receiving authorization from the fire department or emergency coordinator', isBold: false, isRed: true },
      { id: sid(CODE,5), textFR: 'Évacuer calmement et éviter de courir pour limiter l\'essoufflement et le risque d\'inhalation', textEN: 'Evacuate calmly and avoid running to limit shortness of breath and inhalation risk', isBold: false },
      { id: sid(CODE,6), textFR: 'Aider les autres si la situation est sécuritaire — si un collègue montre des signes de désorientaton ou de malaise (vertiges, essoufflement, confusion), l\'aider à sortir sans compromettre sa propre sécurité', textEN: 'Help others if the situation is safe — if a colleague shows signs of disorientation or discomfort (dizziness, shortness of breath, confusion), help them out without compromising your own safety', isBold: false },
      { id: sid(CODE,7), textFR: 'Signaler immédiatement toute personne manquante ou en difficulté au responsable de l\'évacuation dès l\'arrivée au point de rassemblement', textEN: 'Immediately report any missing or struggling person to the evacuation supervisor upon arrival at the assembly point', isBold: false },
      { id: sid(CODE,8), textFR: 'Se rendre directement au point de rassemblement désigné à l\'extérieur du bâtiment, hors du sens du vent, dans une zone dégagée et bien ventilée — les superviseurs ou chefs d\'équipe doivent effectuer un appel nominal pour confirmer la présence de tous les employés', textEN: 'Proceed directly to the designated assembly point outside the building, upwind, in a clear and well-ventilated area — supervisors or team leaders must conduct a roll call to confirm all employees are present', isBold: false },
      { id: sid(CODE,9), textFR: 'Informer les responsables de toute personne absente ou blessée', textEN: 'Inform supervisors of any absent or injured person', isBold: false },
      { id: sid(CODE,10), textFR: 'Attendre les instructions officielles avant de retourner dans le bâtiment — ne pas quitter le point de rassemblement tant que les autorités n\'ont pas confirmé que la concentration de CO₂ est revenue à un niveau sécuritaire', textEN: 'Wait for official instructions before returning to the building — do not leave the assembly point until authorities confirm CO₂ concentration has returned to a safe level', isBold: false, isRed: true },
      { id: sid(CODE,11), textFR: 'Demander une assistance médicale immédiate si des symptômes d\'exposition sont ressentis (maux de tête, vertiges, nausées, essoufflement)', textEN: 'Request immediate medical assistance if exposure symptoms are felt (headache, dizziness, nausea, shortness of breath)', isBold: false },
      { id: sid(CODE,12), textFR: 'Si des symptômes persistent dans les heures qui suivent (fatigue, maux de tête, confusion), consulter un professionnel de la santé et signaler la situation à son responsable', textEN: 'If symptoms persist in the following hours (fatigue, headache, confusion), consult a health professional and report the situation to your supervisor', isBold: false },
      { id: sid(CODE,13), textFR: 'Participer à la rédaction du rapport d\'incident afin d\'améliorer les procédures futures', textEN: 'Participate in writing the incident report to improve future procedures', isBold: false },
      { id: sid(CODE,14), textFR: '⚠️ Le dioxyde de carbone (CO₂) est un gaz incolore, inodore et insipide — à forte concentration, il entraîne des symptômes graves tels que maux de tête, vertiges, nausées, confusion et, à des niveaux encore plus élevés, perte de conscience et décès — toute alarme de CO₂ doit être traitée comme une urgence majeure', textEN: '⚠️ Carbon dioxide (CO₂) is a colorless, odorless, tasteless gas — at high concentration, it causes serious symptoms such as headache, dizziness, nausea, confusion, and at even higher levels, loss of consciousness and death — any CO₂ alarm must be treated as a major emergency', isBold: false, isRed: true },
    ],
  }],
};