'use client';
import { useEffect, useState } from 'react';
import { Archive, Pencil, RotateCcw, Trash2 } from 'lucide-react';
import AppLayout from '@/components/layout/AppLayout';
import api from '@/lib/api';
import { useAuthStore } from '@/stores/auth.store';
import ActivityTypeTaskLists from './ActivityTypeTaskLists';
import { activityTypePayload, activityTypeState, colorPresentation, EMPTY_ACTIVITY_TYPE_FORM, formatDefaultDuration,
  ICON_OPTIONS, iconPresentation, COLOR_OPTIONS, type ActivityTypeForm } from './activityTypePresentation';

type Item={id:string;nameFR:string;nameEN?:string;visualToken:string;iconKey?:string;defaultDurationMinutes?:number;clientBookableDefault:boolean;isSystem:boolean;isActive:boolean;displayOrder:number};
function serverMessage(error:unknown,fallback:string){const message=(error as {response?:{data?:{message?:string|string[]}}})?.response?.data?.message;return Array.isArray(message)?message.join(' '):message||fallback;}

function TypeForm({form,editing,busy,onChange,onSave,onCancel}:{form:ActivityTypeForm;editing:boolean;busy:boolean;onChange:(form:ActivityTypeForm)=>void;onSave:()=>void;onCancel:()=>void}){
 const field='block text-xs font-semibold uppercase tracking-wide mb-1.5 text-[#6C757D]';
 const control='w-full min-h-10 rounded-md border border-[#CED4DA] bg-white px-3 py-2 text-sm text-[#2C3E50] focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[#2980B9]';
 return <section className="mb-8 rounded-lg border border-[#DEE2E6] bg-white p-4 sm:p-6" aria-labelledby="activity-type-form-title"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-widest text-[#ADB5BD]">Type personnalisé</p><h2 id="activity-type-form-title" className="mt-1 text-lg font-bold text-[#2C3E50]">{editing?'Modifier le type':'Ajouter un type personnalisé'}</h2><p className="mt-1 text-sm text-[#6C757D]">{editing?'Mettez à jour les informations du type sélectionné.':'Créez un type propre aux activités de votre organisation.'}</p></div>
 <div className="grid grid-cols-1 gap-4 md:grid-cols-2"><label><span className={field}>Nom français *</span><input className={control} value={form.nameFR} onChange={e=>onChange({...form,nameFR:e.target.value})} required/></label><label><span className={field}>Nom anglais</span><input className={control} value={form.nameEN} onChange={e=>onChange({...form,nameEN:e.target.value})}/></label><label><span className={field}>Couleur *</span><select className={control} value={form.visualToken} onChange={e=>onChange({...form,visualToken:e.target.value})}>{COLOR_OPTIONS.map(o=><option key={o.value} value={o.value}>● {o.label}</option>)}</select></label><label><span className={field}>Icône</span><select className={control} value={form.iconKey} onChange={e=>onChange({...form,iconKey:e.target.value})}>{ICON_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.glyph} {o.label}</option>)}</select></label><label><span className={field}>Durée par défaut</span><span className="flex items-center gap-2"><input className={control} type="number" min="1" max="1440" placeholder="120" value={form.defaultDurationMinutes} onChange={e=>onChange({...form,defaultDurationMinutes:e.target.value})}/><span className="text-sm text-[#6C757D]">minutes</span></span></label><label><span className={field}>Ordre</span><input className={control} type="number" min="0" max="100000" placeholder="130" value={form.displayOrder} onChange={e=>onChange({...form,displayOrder:e.target.value})}/></label></div>
 <label className="mt-5 flex items-start gap-3 text-sm text-[#2C3E50]"><input className="mt-0.5 h-4 w-4 accent-[#C0392B]" type="checkbox" checked={form.clientBookableDefault} onChange={e=>onChange({...form,clientBookableDefault:e.target.checked})}/><span><strong className="block font-semibold">Réservable par le client par défaut</strong><span className="text-[#6C757D]">Ce choix initialise les nouvelles activités de ce type.</span></span></label>
 <div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row"><button type="button" disabled={busy||!form.nameFR.trim()} onClick={onSave} className="rounded-md bg-[#C0392B] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#A93226] focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[#2980B9] disabled:opacity-50">{busy?'Enregistrement…':editing?'Enregistrer les modifications':'Ajouter le type'}</button>{editing&&<button type="button" onClick={onCancel} className="rounded-md border border-[#CED4DA] px-4 py-2.5 text-sm font-semibold text-[#45515C] hover:bg-[#F8F9FA] focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[#2980B9]">Annuler</button>}</div></section>;
}

function TypeCard({item,role,onEdit,onAction}:{item:Item;role:string;onEdit:(item:Item)=>void;onAction:(path:string,method?:'post'|'delete')=>void}){
 const color=colorPresentation(item.visualToken),icon=iconPresentation(item.iconKey),state=activityTypeState(item.isActive),focus='focus-visible:outline focus-visible:outline-3 focus-visible:outline-offset-2 focus-visible:outline-[#2980B9]';
 return <article className={`relative overflow-hidden rounded-lg border p-4 pl-5 sm:p-5 sm:pl-6 ${item.isActive?'border-[#DEE2E6] bg-white':'border-[#D8DDE1] bg-[#F5F6F7] opacity-80'}`}><span className="absolute inset-y-0 left-0 w-1.5" style={{backgroundColor:color.color}} aria-hidden="true"/><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="flex min-w-0 flex-1 gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border bg-white text-lg" style={{borderColor:color.color,color:color.color}} aria-hidden="true">{icon.glyph}</span><div className="min-w-0"><h3 className="font-bold text-[#2C3E50]">{item.nameFR}</h3>{item.nameEN&&<p className="text-xs text-[#7A8691]">{item.nameEN}</p>}<p className="mt-1 text-sm text-[#5D6D7E]">{formatDefaultDuration(item.defaultDurationMinutes)} · {item.clientBookableDefault?'Réservable par le client':'Non réservable'} · <strong className={item.isActive?'text-[#277245]':'text-[#6C757D]'}>{item.isActive?'Actif':'Archivé'}</strong></p><p className="mt-1 text-xs text-[#7A8691]">{icon.label} · {color.label}<span className="ml-2">Ordre {item.displayOrder}</span></p></div></div>
 {!item.isSystem&&<div className="flex flex-wrap gap-2 text-sm"><button aria-label={`Modifier ${item.nameFR}`} onClick={()=>onEdit(item)} className={`inline-flex items-center gap-1.5 rounded border border-[#CED4DA] px-3 py-2 font-medium text-[#2C3E50] hover:bg-[#F8F9FA] ${focus}`}><Pencil size={14}/>Modifier</button>{item.isActive?<button aria-label={`${state.action} ${item.nameFR}`} onClick={()=>onAction(`/activity-types/${item.id}/archive`)} className={`inline-flex items-center gap-1.5 rounded border border-[#CED4DA] px-3 py-2 font-medium text-[#45515C] hover:bg-[#F8F9FA] ${focus}`}><Archive size={14}/>{state.action}</button>:<button aria-label={`${state.action} ${item.nameFR}`} onClick={()=>onAction(`/activity-types/${item.id}/restore`)} className={`inline-flex items-center gap-1.5 rounded border border-[#9CC8AA] px-3 py-2 font-medium text-[#277245] hover:bg-[#F0F8F2] ${focus}`}><RotateCcw size={14}/>{state.action}</button>}<button aria-label={`Supprimer définitivement ${item.nameFR}`} onClick={()=>onAction(`/activity-types/${item.id}`,'delete')} className={`inline-flex items-center gap-1.5 rounded border border-[#D9A39E] px-3 py-2 font-semibold text-[#A93226] hover:bg-[#FFF5F4] ${focus}`}><Trash2 size={14}/>Supprimer</button></div>}</div><ActivityTypeTaskLists activityTypeId={item.id} role={role} isSystem={item.isSystem}/></article>;
}

export default function ActivityTypesSettings(){
 const role=useAuthStore(state=>state.user?.role||'');
 const [items,setItems]=useState<Item[]>([]),[form,setForm]=useState<ActivityTypeForm>(EMPTY_ACTIVITY_TYPE_FORM),[editing,setEditing]=useState<Item|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async()=>setItems((await api.get('/activity-types?includeArchived=true')).data);
 useEffect(()=>{load().catch(()=>setError('Impossible de charger le catalogue.')).finally(()=>setLoading(false));},[]);
 const cancel=()=>{setEditing(null);setForm(EMPTY_ACTIVITY_TYPE_FORM);setError('');};
 const save=async()=>{setBusy(true);setError('');try{const payload=activityTypePayload(form);editing?await api.put(`/activity-types/${editing.id}`,payload):await api.post('/activity-types',payload);cancel();await load();}catch(error){setError(serverMessage(error,'Vérifiez les champs du type.'));}finally{setBusy(false);}};
 const edit=(item:Item)=>{setEditing(item);setError('');setForm({nameFR:item.nameFR,nameEN:item.nameEN||'',visualToken:item.visualToken,iconKey:item.iconKey||'OTHER',defaultDurationMinutes:item.defaultDurationMinutes?.toString()||'',clientBookableDefault:item.clientBookableDefault,displayOrder:item.displayOrder.toString()});window.scrollTo({top:0,behavior:'smooth'});};
 const action=async(path:string,method:'post'|'delete'='post')=>{if(method==='delete'&&!window.confirm('Supprimer définitivement ce type personnalisé?'))return;setError('');try{await api[method](path);if(editing&&path.includes(editing.id))cancel();await load();}catch(error){setError(serverMessage(error,"Ce type est utilisé; archivez-le pour préserver l'historique."));}};
 const system=items.filter(x=>x.isSystem),custom=items.filter(x=>!x.isSystem);
 return <AppLayout><main className="mx-auto w-full max-w-6xl px-3 py-4 sm:px-6 sm:py-6"><header className="mb-7"><p className="mb-1 text-xs font-bold uppercase tracking-widest text-[#ADB5BD]">Paramètres</p><h1 className="text-2xl font-black text-[#2C3E50]">Types d’activités</h1><div className="mt-2 h-1 w-16 bg-[#C0392B]"/><p className="mt-4 max-w-3xl text-sm leading-6 text-[#5D6D7E]">Configurez les types d’activités utilisés par votre organisation. Les types CORO sont fournis par défaut et ne peuvent pas être modifiés.</p></header>{error&&<div role="alert" className="mb-5 rounded-md border border-[#E5ADA8] bg-[#FCEFED] p-3 text-sm text-[#922B21]">{error}</div>}<TypeForm form={form} editing={!!editing} busy={busy} onChange={setForm} onSave={save} onCancel={cancel}/>
 {loading?<p className="py-12 text-center text-sm text-[#7A8691]">Chargement du catalogue…</p>:<><section className="mb-8" aria-labelledby="system-types"><div className="mb-3 flex items-baseline justify-between gap-3"><h2 id="system-types" className="text-sm font-black uppercase tracking-widest text-[#2C3E50]">Types CORO</h2><span className="text-sm text-[#7A8691]">{system.length} type{system.length===1?'':'s'} CORO</span></div><div className="grid gap-3">{system.map(x=><TypeCard key={x.id} item={x} role={role} onEdit={edit} onAction={action}/>)}</div></section><section aria-labelledby="custom-types"><div className="mb-3 flex items-baseline justify-between gap-3"><h2 id="custom-types" className="text-sm font-black uppercase tracking-widest text-[#2C3E50]">Types personnalisés</h2><span className="text-sm text-[#7A8691]">{custom.length} type{custom.length===1?'':'s'} personnalisé{custom.length===1?'':'s'}</span></div>{custom.length?<div className="grid gap-3">{custom.map(x=><TypeCard key={x.id} item={x} role={role} onEdit={edit} onAction={action}/>)}</div>:<div className="rounded-lg border border-dashed border-[#CED4DA] bg-[#F8F9FA] px-5 py-9 text-center"><p className="font-semibold text-[#45515C]">Aucun type personnalisé.</p><p className="mt-1 text-sm text-[#7A8691]">Ajoutez un type adapté aux activités de votre organisation.</p></div>}</section></>}
 </main></AppLayout>;
}
