'use client';
import { useEffect, useState } from 'react';
import AppLayout from '@/components/layout/AppLayout';
import api from '@/lib/api';
type Item={id:string;nameFR:string;nameEN?:string;visualToken:string;iconKey?:string;defaultDurationMinutes?:number;clientBookableDefault:boolean;isSystem:boolean;isActive:boolean;displayOrder:number};
const tokens=['BLUE','CYAN','VIOLET','SLATE','INDIGO','NAVY','ORANGE','GREEN','AMBER','ROSE','NEUTRAL'];
const empty={nameFR:'',nameEN:'',visualToken:'BLUE',iconKey:'OTHER',defaultDurationMinutes:'',clientBookableDefault:false,displayOrder:''};
export default function ActivityTypesSettings(){
 const [items,setItems]=useState<Item[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<Item|null>(null),[error,setError]=useState('');
 const load=async()=>setItems((await api.get('/activity-types?includeArchived=true')).data); useEffect(()=>{load().catch(()=>setError('Impossible de charger le catalogue.'));},[]);
 const save=async()=>{const payload={...form,nameFR:form.nameFR.trim(),defaultDurationMinutes:form.defaultDurationMinutes?Number(form.defaultDurationMinutes):undefined,displayOrder:form.displayOrder?Number(form.displayOrder):undefined};try{editing?await api.put(`/activity-types/${editing.id}`,payload):await api.post('/activity-types',payload);setEditing(null);setForm(empty);await load();}catch{setError('Vérifiez les champs du type.');}};
 const edit=(x:Item)=>{setEditing(x);setForm({nameFR:x.nameFR,nameEN:x.nameEN||'',visualToken:x.visualToken,iconKey:x.iconKey||'OTHER',defaultDurationMinutes:x.defaultDurationMinutes?.toString()||'',clientBookableDefault:x.clientBookableDefault,displayOrder:x.displayOrder.toString()});};
 const action=async(path:string,method:'post'|'delete'='post')=>{try{await api[method](path);await load();}catch{setError("Ce type est utilisé; archivez-le pour préserver l'historique.");}};
 return <AppLayout><div className="max-w-5xl mx-auto p-4"><h1 className="text-2xl font-bold mb-2">Types d’activités</h1><p className="text-sm text-gray-600 mb-6">Les types CORO sont en lecture seule. L’ordre est déterminé par le numéro, puis le nom.</p>{error&&<p role="alert" className="text-red-700 mb-3">{error}</p>}
 <section className="border rounded p-4 mb-6"><h2 className="font-semibold mb-3">{editing?'Modifier le type personnalisé':'Ajouter un type personnalisé'}</h2><div className="grid md:grid-cols-3 gap-3"><input aria-label="Nom français" placeholder="Nom français *" value={form.nameFR} onChange={e=>setForm({...form,nameFR:e.target.value})} className="border rounded p-2"/><input aria-label="Nom anglais" placeholder="Nom anglais" value={form.nameEN} onChange={e=>setForm({...form,nameEN:e.target.value})} className="border rounded p-2"/><select aria-label="Couleur" value={form.visualToken} onChange={e=>setForm({...form,visualToken:e.target.value})} className="border rounded p-2">{tokens.map(x=><option key={x}>{x}</option>)}</select><input aria-label="Durée par défaut" type="number" min="1" max="1440" placeholder="Durée (minutes)" value={form.defaultDurationMinutes} onChange={e=>setForm({...form,defaultDurationMinutes:e.target.value})} className="border rounded p-2"/><input aria-label="Ordre" type="number" min="0" max="100000" placeholder="Ordre" value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:e.target.value})} className="border rounded p-2"/><label className="flex items-center gap-2"><input type="checkbox" checked={form.clientBookableDefault} onChange={e=>setForm({...form,clientBookableDefault:e.target.checked})}/> Réservable client par défaut</label></div><div className="mt-3 flex gap-2"><button disabled={!form.nameFR.trim()} onClick={save} className="bg-blue-700 text-white rounded px-4 py-2 disabled:opacity-50">Enregistrer</button>{editing&&<button onClick={()=>{setEditing(null);setForm(empty)}} className="border rounded px-4">Annuler</button>}</div></section>
 {['Types CORO','Types personnalisés'].map((title,group)=><section key={title} className="mb-6"><h2 className="font-semibold mb-2">{title}</h2><div className="grid gap-2">{items.filter(x=>x.isSystem===!group).map(x=><div key={x.id} className="border rounded p-3 flex flex-wrap items-center gap-3"><strong className="grow">{x.nameFR}</strong><span>{x.defaultDurationMinutes?`${x.defaultDurationMinutes} min`:'Durée libre'}</span><span>{x.clientBookableDefault?'Réservable':'Non réservable'}</span><span>{x.isActive?'Actif':'Archivé'}</span><span>Ordre {x.displayOrder}</span>{!x.isSystem&&<><button onClick={()=>edit(x)} className="underline">Modifier</button>{x.isActive?<button onClick={()=>action(`/activity-types/${x.id}/archive`)} className="underline">Archiver</button>:<button onClick={()=>action(`/activity-types/${x.id}/restore`)} className="underline">Réactiver</button>}<button onClick={()=>action(`/activity-types/${x.id}`,'delete')} className="text-red-700 underline">Supprimer</button></>}</div>)}</div></section>)}</div></AppLayout>;
}
