-- CreateTable
CREATE TABLE "PcaConfig" (
    "id" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "planName" TEXT,
    "effectiveDate" TIMESTAMP(3),
    "scope" TEXT,
    "pcaBuildingIds" TEXT[],
    "sector" TEXT,
    "employeeCount" INTEGER,
    "operatingHours" TEXT,
    "regulatoryReqs" TEXT[],
    "coordinatorFirstName" TEXT,
    "coordinatorLastName" TEXT,
    "coordinatorTitle" TEXT,
    "coordinatorEmail" TEXT,
    "coordinatorPhone" TEXT,
    "substituteFirstName" TEXT,
    "substituteLastName" TEXT,
    "substituteEmail" TEXT,
    "substitutePhone" TEXT,
    "cellMembers" JSONB,
    "spokesperson" TEXT,
    "socialMediaMonitor" TEXT,
    "riskScenarios" JSONB,
    "criticalServices" JSONB,
    "teleworkPossible" TEXT,
    "alternativeSite" BOOLEAN,
    "alternativeSiteAddress" TEXT,
    "sharingAgreement" BOOLEAN,
    "itRedundancy" BOOLEAN,
    "offSiteBackup" BOOLEAN,
    "backupFrequency" TEXT,
    "crossTraining" BOOLEAN,
    "processDocumented" BOOLEAN,
    "tempStaffAccess" BOOLEAN,
    "alternativeSuppliers" BOOLEAN,
    "safetyStock" BOOLEAN,
    "safetyStockDuration" TEXT,
    "generator" BOOLEAN,
    "ups" BOOLEAN,
    "insuranceBI" BOOLEAN,
    "insuranceProperty" BOOLEAN,
    "insuranceCyber" BOOLEAN,
    "insuranceLastReview" TIMESTAMP(3),
    "internalChannel" TEXT,
    "massAlertSystem" BOOLEAN,
    "externalChannel" TEXT,
    "priorityClients" TEXT,
    "authoritiesToNotify" TEXT[],
    "mediaContact" TEXT,
    "activationCriteria" TEXT,
    "coordinationLocation" TEXT,
    "emergencyBridge" TEXT,
    "linkedPmuId" TEXT,
    "resumptionSequence" JSONB,
    "exerciseFormative" TEXT,
    "exerciseTable" TEXT,
    "exerciseSimulation" TEXT,
    "exerciseIT" TEXT,
    "planOwner" TEXT,
    "reviewFrequency" TEXT,
    "nextReviewDate" TIMESTAMP(3),

    CONSTRAINT "PcaConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PcaConfig_projectId_key" ON "PcaConfig"("projectId");

-- AddForeignKey
ALTER TABLE "PcaConfig" ADD CONSTRAINT "PcaConfig_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
