import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { RulesEngineService, BuildingConfig } from './rules-engine.service';

@Injectable()
export class ConfiguratorService {
  constructor(
    private prisma: PrismaService,
    private rulesEngine: RulesEngineService,
  ) {}

  async analyzeBuilding(config: BuildingConfig) {
    return this.rulesEngine.analyzeConfiguration(config);
  }

  async saveConfiguration(projectId: string, config: BuildingConfig) {
    const analysis = this.rulesEngine.analyzeConfiguration(config);
    await this.prisma.project.update({
      where: { id: projectId },
      data: { status: 'IN_PROGRESS', progress: 25, configData: config as any },
    });
    return { projectId, config, analysis, savedAt: new Date() };
  }

  async getConfiguration(projectId: string) {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      select: { configData: true },
    });
    return project?.configData || {};
  }

  async getQuestions() {
    return {
      sections: [
        {
  id: 'infos_document',
  title: 'Infos du document',
  icon: '📄',
  fields: [
    {
      key: 'province',
      label: 'Province',
      type: 'select',
      options: ['Quebec', 'Ontario', 'Alberta'],
    },
    {
      key: 'responsableNom',
      label: 'Nom du responsable du plan',
      type: 'text',
    },
    {
      key: 'responsableTitre',
      label: 'Titre / Poste du responsable',
      type: 'text',
    },
    {
      key: 'dateReleve',
      label: 'Date du releve technique',
      type: 'date',
    },
    {
      key: 'ville',
      label: 'Ville du batiment',
      type: 'text',
    },
    {
      key: 'reglementMunicipal',
      label: 'Reglement municipal applicable (si connu)',
      type: 'text',
    },
    {
      key: 'typeDocument',
      label: 'Type de document',
      type: 'select',
      options: ['PMU', 'PSI', 'PCA', 'PGC', 'PRA', 'PUE'],
    },
    {
      key: 'anneDocument',
      label: 'Annee du document',
      type: 'number',
    },
    {
      key: 'versionDocument',
      label: 'Version du document',
      type: 'select',
      options: ['Creation initiale', 'Mise a jour annuelle', 'Mise a jour suite a incident', 'Mise a jour suite a renovation', 'Mise a jour suite a changement occupation'],
    },
  ],
},
        {
          id: 'description',
          title: 'Description generale',
          icon: '🏢',
          fields: [
            { key: 'buildingType', label: 'Type de batiment', type: 'select',
              options: ['Tour a bureaux', 'Immeuble residentiel', 'Industriel', 'Commercial', 'Institutionnel', 'Hotel', 'Centre commercial', 'Autre'] },
            { key: 'usagePrincipal', label: 'Usage principal (classification)', type: 'select',
              options: [
                'A1 - Etablissements de reunion - Spectacle',
                'A2 - Etablissements de reunion - Education, culte, divertissement, restauration',
                'A3 - Etablissements de reunion de type arena',
                'A4 - Etablissements de reunion en plein air',
                'B1 - Etablissements de detention',
                'B2 - Etablissements de traitement',
                'B3 - Etablissements de soins',
                'C - Etablissements d habitation',
                'D - Etablissements d affaires',
                'E - Etablissements commerciaux',
                'F1 - Etablissement industriel a risques tres eleves',
                'F2 - Etablissement industriel a risques moyens',
                'F3 - Etablissement industriel a risques faibles',
              ] },
            { key: 'usageSecondaire', label: 'Usage secondaire (si applicable)', type: 'select',
              options: ['Aucun', 'A1 - Etablissements de reunion - Spectacle', 'A2 - Etablissements de reunion - Education, culte, divertissement, restauration', 'A3 - Etablissements de reunion de type arena', 'A4 - Etablissements de reunion en plein air', 'B1 - Etablissements de detention', 'B2 - Etablissements de traitement', 'B3 - Etablissements de soins', 'C - Etablissements d habitation', 'D - Etablissements d affaires', 'E - Etablissements commerciaux', 'F1 - Etablissement industriel a risques tres eleves', 'F2 - Etablissement industriel a risques moyens', 'F3 - Etablissement industriel a risques faibles'] },
            { key: 'floors', label: 'Nombre d etages', type: 'number' },
            { key: 'basements', label: 'Nombre de sous-sols', type: 'number' },
            { key: 'superficie', label: 'Superficie du batiment (pi2)', type: 'number' },
            { key: 'anneeConstruction', label: 'Annee de construction', type: 'select', options: Array.from({length: 125}, (_, i) => String(2025 - i)) },
            { key: 'derniereRenovation', label: 'Annee derniere renovation majeure', type: 'select', options: ['Aucune', ...Array.from({length: 35}, (_, i) => String(2026 - i))] },
            { key: 'typeConstructionEtages', label: 'Type de construction — Etages superieurs', type: 'select',
              options: ['Incombustible - Beton', 'Incombustible - Acier', 'Bois', 'Mixte', 'Autre'] },
            { key: 'typeConstructionToit', label: 'Type de construction — Toit', type: 'select',
              options: ['Incombustible - Beton', 'Incombustible - Acier', 'Bois', 'Mixte', 'Autre'] },
            { key: 'accesSousSol', label: 'Acces aux sous-sols', type: 'checkbox_group',
              checkboxOptions: ['Escaliers', 'Ascenseurs', 'Rampe', 'Acces restreint', 'Autre'] },
            { key: 'accesSousSolDetails', label: 'Details acces sous-sol (optionnel)', type: 'text' },
            { key: 'accesEtages', label: 'Acces aux etages', type: 'checkbox_group',
              checkboxOptions: ['Escaliers', 'Ascenseurs', 'Escaliers pressurises', 'Autre'] },
            { key: 'accesEtagesDetails', label: 'Details acces etages (optionnel)', type: 'text' },
            { key: 'treizeEtage', label: 'Le batiment a un 13e etage', type: 'boolean' },
            { key: 'infosBatiment', label: 'Informations supplementaires sur le batiment (optionnel)', type: 'text' },
            { key: 'hauteurBatiment', label: 'Batiment a grande hauteur (+ de 18m)', type: 'boolean' },
            { key: 'multiLocataires', label: 'Multi-locataires', type: 'boolean' },
            { key: 'nbLocataires', label: 'Nombre de locataires', type: 'number' },
            {
              key: 'quartsOccupation',
              label: 'Quarts de travail et occupation (ajouter chaque quart)',
              type: 'dynamic_list',
              schema: [
                { key: 'nomQuart', label: 'Nom du quart', type: 'select', options: ['Jour', 'Soir', 'Nuit', 'Autre'] },
                { key: 'heureDebut', label: 'Heure de début', type: 'time' },
                { key: 'heureFin', label: 'Heure de fin', type: 'time' },
                { key: 'occupantsSemaine', label: 'Occupants — Semaine', type: 'number' },
                { key: 'occupantsSamedi', label: 'Occupants — Samedi', type: 'number' },
                { key: 'occupantsDimanche', label: 'Occupants — Dimanche', type: 'number' },
              ],
            },
            { key: 'lieuSommeil', label: 'Lieu de sommeil (hotel, residence)', type: 'boolean' },
            { key: 'securite24h', label: 'Securite 24h/7', type: 'boolean' },
            { key: 'agentSecurite', label: 'Agent de securite sur place', type: 'boolean' },
            { key: 'posteSurveillance', label: 'Poste de securite', type: 'boolean' },
            { key: 'personnelHandicap', label: 'Personnes necessitant aide evacuation (PPNAE)', type: 'boolean' },
            { key: 'controleAcces', label: 'Systeme de controle d acces', type: 'boolean' },
            { key: 'cameras', label: 'Cameras de surveillance (CCTV)', type: 'boolean' },
          ],
        },
        {
          id: 'certifications',
          title: 'Certifications du batiment',
          icon: '🏆',
          fields: [
            { key: 'certBOMA', label: 'Certification BOMA BEST', type: 'boolean' },
            { key: 'certBOMANiveau', label: 'Niveau BOMA BEST', type: 'select',
              options: ['De base', 'Bronze', 'Argent', 'Or', 'Platine'] },
            { key: 'certLEED', label: 'Certification LEED', type: 'boolean' },
            { key: 'certLEEDNiveau', label: 'Niveau LEED', type: 'select',
              options: ['Certifie', 'Argent', 'Or', 'Platine'] },
            { key: 'certISO22301', label: 'ISO 22301 (Continuite des affaires)', type: 'boolean' },
            { key: 'certISO31000', label: 'ISO 31000 (Gestion des risques)', type: 'boolean' },
            { key: 'certEnergyStar', label: 'Energy Star', type: 'boolean' },
            { key: 'autresCertifications', label: 'Autres certifications (decrire)', type: 'text' },
          ],
        },
        {
          id: 'emplacements',
          title: 'Emplacements strategiques',
          icon: '📍',
          fields: [
            { key: 'posteCommandement', label: 'Poste de commandement (lieu)', type: 'text' },
            { key: 'pointRassemblement', label: 'Point de rassemblement principal (lieu)', type: 'text' },
            { key: 'pointRassemblement2', label: 'Point de rassemblement secondaire (lieu)', type: 'text' },
            { key: 'lieuAccueilTemporaire', label: 'Lieu d accueil temporaire (lieu)', type: 'text' },
            { key: 'zoneConfinement', label: 'Zone de confinement - BOMA (lieu)', type: 'text' },
            { key: 'zoneRafraichissement', label: 'Zone de rafraichissement - BOMA (lieu)', type: 'text' },
            { key: 'boiteClePompier', label: 'Boite a cles pompier (lieu)', type: 'text' },
            { key: 'trousseClesPompier', label: 'Trousseau de cles pompier present', type: 'boolean' },
            { key: 'trousseClesPompierLieu', label: 'Localisation du trousseau de cles pompier', type: 'text' },
            { key: 'lieuDocument', label: 'Lieu ou est conserve le document (PMU/PSI/etc.)', type: 'text' },
          ],
        },
        {
          id: 'alarme',
          title: 'Alarme incendie',
          icon: '🚨',
          fields: [
            { key: 'panneauAlarme', label: 'Panneau alarme incendie present', type: 'boolean' },
            { key: 'panneauType', label: 'Type de signal', type: 'select', options: ['SIMPLE', 'DOUBLE', 'AUCUN'] },
            { key: 'heuresFonctionnement', label: 'Heures de fonctionnement double signal', type: 'text' },
            { key: 'panneauMarque', label: 'Marque du panneau', type: 'text' },
            { key: 'panneauModele', label: 'Modele du panneau', type: 'text' },
            { key: 'panneauLocalisation', label: 'Emplacement du panneau', type: 'text' },
            { key: 'panneauAnnonciateurDistance', label: 'Panneau annonciateur present', type: 'boolean' },
            { key: 'panneauAnnonciateurLieu', label: 'Emplacement panneau annonciateur', type: 'text' },
            { key: 'teleSurveillance', label: 'Centrale de telesurveillance', type: 'boolean' },
            { key: 'centraleSurveillance', label: 'Nom de la centrale de surveillance', type: 'text' },
            { key: 'centraleTelephone', label: 'Numero de telephone de la centrale', type: 'text' },
            { key: 'centraleCodeClient', label: 'Code client de la centrale', type: 'text' },
            { key: 'telephonePompier', label: 'Telephone pompier present', type: 'boolean' },
            { key: 'stationManuelle', label: 'Stations manuelles d alarme presentes', type: 'boolean' },
            { key: 'detecteurFumee', label: 'Detecteurs de fumee', type: 'boolean' },
            { key: 'detecteurChaleur', label: 'Detecteurs de chaleur', type: 'boolean' },
            { key: 'detecteurDebitGicleurs', label: 'Detecteurs de debit gicleurs', type: 'boolean' },
            { key: 'rappelAscenseurs', label: 'Relais : Rappel automatique ascenseurs', type: 'boolean' },
            { key: 'arretVentilation', label: 'Relais : Arret automatique ventilation', type: 'boolean' },
            { key: 'desenfumageAutomatique', label: 'Relais : Desenfumage automatique', type: 'boolean' },
            { key: 'deverrouillagePorces', label: 'Relais : Deverrouillage acces controle', type: 'boolean' },
            { key: 'fermeturePortesCoupeFeu', label: 'Relais : Fermeture portes coupe-feu', type: 'boolean' },
          ],
        },
        {
          id: 'communication',
          title: 'Communication',
          icon: '📢',
          fields: [
            { key: 'systemePhonic', label: 'Systeme de communication phonique present', type: 'boolean' },
            { key: 'systemePhonicType', label: 'Type systeme phonique', type: 'select',
              options: ['Manuel', 'Automatise', 'Hybride'] },
            { key: 'messagesAutomatises', label: 'Messages automatises programmes', type: 'boolean' },
            { key: 'radiosCommunication', label: 'Radios de communication disponibles', type: 'boolean' },
            { key: 'nbRadios', label: 'Nombre de radios', type: 'number' },
            { key: 'intercomUrgence', label: 'Intercom urgence present', type: 'boolean' },
          ],
        },
        {
          id: 'gicleurs',
          title: 'Gicleurs et protection eau',
          icon: '💧',
          fields: [
            { key: 'gicleurs', label: 'Reseau de gicleurs present', type: 'boolean' },
            {
              key: 'gicleursSystemes',
              label: 'Systemes de gicleurs (ajouter chaque type de reseau)',
              type: 'dynamic_list',
              schema: [
                { key: 'type', label: 'Type de reseau', type: 'select',
                  options: ['Sous eau', 'Sous air', 'Pre-action', 'Diluvien', 'Brouillard d eau', 'Autre'] },
                { key: 'lieu', label: 'Secteurs / lieux desservis (un par ligne ou separes par virgule)', type: 'text' },
                { key: 'complet', label: 'Systeme complet (tout le batiment)', type: 'boolean' },
              ],
            },
            { key: 'salleGicleurs', label: 'Localisation salle gicleurs', type: 'text' },
            { key: 'pompeIncendie', label: 'Pompe incendie presente', type: 'boolean' },
            { key: 'pompeIncendieLieu', label: 'Localisation pompe incendie', type: 'text' },
            { key: 'gapmUsgpm', label: 'GAPM / USGPM de la pompe', type: 'text' },
            { key: 'boyauIncendie', label: 'Boyaux incendie presents', type: 'boolean' },
            { key: 'boyauCabinet', label: 'Cabinet boyau incendie present', type: 'boolean' },
            { key: 'priseRefoulement', label: 'Prise de refoulement presente', type: 'boolean' },
            { key: 'raccordPompier', label: 'Raccord pompier exterieur present', type: 'boolean' },
            { key: 'raccordPompierLieu', label: 'Localisation raccord pompier', type: 'text' },
            { key: 'bornesFontaine', label: 'Bornes-fontaines a proximite', type: 'boolean' },
            { key: 'bornesFontaineLieu', label: 'Localisation bornes-fontaines', type: 'text' },
            { key: 'vannesIsolement', label: 'Vannes d isolement de zone presentes', type: 'boolean' },
            { key: 'vannesIsolementLieu', label: 'Localisation vannes d isolement', type: 'text' },
            { key: 'valve2_5', label: 'Valve 2 1/2 presente', type: 'boolean' },
            { key: 'valve2_5Lieu', label: 'Localisation valve 2 1/2', type: 'text' },
            { key: 'valve1_5', label: 'Valve 1 1/2 presente', type: 'boolean' },
            { key: 'valve1_5Lieu', label: 'Localisation valve 1 1/2', type: 'text' },
          ],
        },
        {
          id: 'extincteurs',
          title: 'Extincteurs et suppression',
          icon: '🧯',
          fields: [
            { key: 'extincteurPortatif', label: 'Extincteurs portatifs presents', type: 'boolean' },
            {
              key: 'extincteursList',
              label: 'Extincteurs portatifs (ajouter chaque type et localisation)',
              type: 'dynamic_list',
              schema: [
                { key: 'type', label: 'Type d extincteur', type: 'select',
                  options: ['ABC poudre', 'CO2', 'Eau', 'Classe K (cuisine)', 'Halotron', 'Eau avec additif', 'Autre'] },
                { key: 'lieu', label: 'Localisation', type: 'text' },
              ],
            },
            { key: 'systemeExtinctionFixe', label: 'Systeme d extinction fixe present (cuisine)', type: 'boolean' },
            { key: 'systemeExtinctionFixeLieu', label: 'Localisation systeme extinction fixe', type: 'text' },
            { key: 'systemePreAction', label: 'Systeme pre-action present', type: 'boolean' },
            { key: 'systemePreActionLieu', label: 'Localisation systeme pre-action', type: 'text' },
            { key: 'systemeHalogen', label: 'Systeme halon / halogenure present', type: 'boolean' },
            { key: 'systemeHalogenLieu', label: 'Localisation systeme halon', type: 'text' },
            { key: 'systemeCO2', label: 'Systeme CO2 fixe present', type: 'boolean' },
            { key: 'systemeCO2Lieu', label: 'Localisation systeme CO2', type: 'text' },
          ],
        },
        {
          id: 'mecanique',
          title: 'Systemes mecaniques',
          icon: '⚙️',
          fields: [
            { key: 'ascenseurs', label: 'Ascenseurs presents', type: 'boolean' },
            { key: 'nbAscenseurs', label: 'Nombre d ascenseurs', type: 'number' },
            { key: 'typeAscenseur', label: 'Type d ascenseurs', type: 'select',
              options: ['Hydraulique', 'Cable (traction)', 'MRL (sans salle machines)', 'Monte-charge', 'Mixte'] },
            { key: 'salleAscenseur', label: 'Localisation salle mecanique ascenseur', type: 'text' },
            { key: 'ascenseurPompier', label: 'Ascenseur designe pompier', type: 'boolean' },
            { key: 'ascenseurPompierLequel', label: 'Quel ascenseur est designe pompier (numero ou description)', type: 'text' },
            { key: 'rappelAscenseursLieu', label: 'Localisation panneau controle rappel ascenseurs', type: 'text' },
            { key: 'telephoneAscenseurs', label: 'Telephone dans tous les ascenseurs', type: 'boolean' },
            { key: 'fonctionneSecours', label: 'Ascenseurs fonctionnent sur alimentation secours', type: 'boolean' },
            { key: 'escaliersPressurises', label: 'Escaliers pressurises', type: 'boolean' },
            { key: 'nbEscaliers', label: 'Nombre d escaliers', type: 'number' },
            { key: 'toitVerrouille', label: 'Toit verrouille', type: 'boolean' },
            { key: 'accesToit', label: 'Acces au toit (par ou)', type: 'text' },
            { key: 'separationCoupeFeu', label: 'Separation coupe-feu presente', type: 'boolean' },
            { key: 'separationCoupeFeuLieu', label: 'Emplacement separation coupe-feu', type: 'text' },
            { key: 'emplacementBac', label: 'Emplacement du bac a dechets', type: 'text' },
            { key: 'compacteur', label: 'Compacteur present', type: 'boolean' },
            { key: 'compacteurGicleurs', label: 'Gicleurs dans le compacteur', type: 'boolean' },
            { key: 'compacteurGicleursType', label: 'Type de gicleurs compacteur', type: 'text' },
            { key: 'compacteurVanneIsolement', label: 'Emplacement vanne isolement gicleur compacteur', type: 'text' },
            { key: 'chuteADechets', label: 'Chute a dechets presente', type: 'boolean' },
            { key: 'cvac', label: 'Systeme CVAC present', type: 'boolean' },
            { key: 'cvacType', label: 'Type CVAC', type: 'select',
              options: ['Centralise', 'Decentralise', 'Mixte (centralise + decentralise)'] },
            { key: 'cvacLocalisation', label: 'Localisation systeme(s) CVAC', type: 'text' },
            { key: 'typeChautfage', label: 'Type de chauffage', type: 'select',
              options: ['Gaz naturel', 'Electrique', 'Mazout', 'Vapeur', 'Geothermique', 'Autre'] },
            { key: 'typeRefroidissement', label: 'Type de refroidissement', type: 'select',
              options: ['Central', 'Unitaire', 'VRF/VRV', 'Autre', 'Aucun'] },
            { key: 'desenfumage', label: 'Systeme de desenfumage present', type: 'boolean' },
            { key: 'desenfumageLieu', label: 'Localisation systeme desenfumage', type: 'text' },
            { key: 'salleElectrique', label: 'Localisation salle electrique principale', type: 'text' },
            { key: 'generatrice', label: 'Generatrice presente', type: 'boolean' },
            { key: 'nbGeneratrices', label: 'Nombre de generatrices', type: 'number' },
            { key: 'generatriceNom', label: 'Marque / modele generatrice', type: 'text' },
            { key: 'generatriceLieu', label: 'Localisation generatrice', type: 'text' },
            { key: 'generatriceCarburant', label: 'Type de carburant generatrice', type: 'select',
              options: ['Diesel', 'Gaz naturel', 'Propane', 'Essence', 'Autre'] },
            { key: 'autonomieGeneratrice', label: 'Autonomie generatrice (heures)', type: 'number' },
            { key: 'capaciteReservoir', label: 'Capacite reservoir principal (litres)', type: 'number' },
            { key: 'reservoirsAuxiliaires', label: 'Reservoirs auxiliaires presents', type: 'boolean' },
            { key: 'reservoirsAuxiliairesLieu', label: 'Emplacement reservoirs auxiliaires', type: 'text' },
            { key: 'reservoirsAuxiliairesCapacite', label: 'Capacite reservoirs auxiliaires (litres)', type: 'text' },
            { key: 'autonomieTotale', label: 'Autonomie totale (heures)', type: 'number' },
            {
              key: 'generatriceEquipements',
              label: 'Equipements alimentes par la generatrice',
              type: 'checkbox_group',
              checkboxOptions: [
                'Alarme incendie', 'Eclairage d urgence', 'Communication phonique',
                'Ascenseurs', 'Telephone pompier', 'Pompe incendie', 'Lumieres',
                'Ventilation fumee', 'CVAC', 'Serveurs / TI', 'Refrigeration',
                'Congelation', 'Systeme de securite', 'Autre',
              ],
            },
            {
              key: 'generatriceEquipementsPersonnalises',
              label: 'Autres equipements alimentes par la generatrice (ajouter)',
              type: 'dynamic_list',
              schema: [
                { key: 'nom', label: 'Nom de l equipement', type: 'text' },
              ],
            },
            { key: 'gazNaturel', label: 'Gaz naturel present', type: 'boolean' },
            { key: 'gazNaturelLieu', label: 'Localisation entree de gaz', type: 'text' },
            { key: 'propane', label: 'Propane present', type: 'boolean' },
            { key: 'propaneLieu', label: 'Localisation reservoir propane', type: 'text' },
            { key: 'vannesArretSalleGicleurs', label: 'Vanne d arret - Salle de gicleurs (localisation)', type: 'text' },
            { key: 'vannesArretGazNaturel', label: 'Vanne d arret - Entree de gaz naturel (localisation)', type: 'text' },
            { key: 'vannesArretEauDomestique', label: 'Vanne d arret - Arrivee eau domestique (localisation)', type: 'text' },
            { key: 'vannesArretSalleElectrique', label: 'Vanne d arret - Salle electrique (localisation)', type: 'text' },
          ],
        },
        {
          id: 'detecteurs',
          title: 'Detecteurs de gaz',
          icon: '🔬',
          fields: [
            { key: 'detecteurCO', label: 'Detecteur CO (monoxyde de carbone)', type: 'boolean' },
            { key: 'detecteurCOSeuil1', label: 'Seuil alarme minimal CO (ppm)', type: 'number' },
            { key: 'detecteurCOSeuil2', label: 'Seuil alarme maximal CO (ppm)', type: 'number' },
            { key: 'detecteurCOLieu', label: 'Localisation detecteur CO', type: 'text' },
            { key: 'detecteurGazNaturel', label: 'Detecteur gaz naturel (CH4)', type: 'boolean' },
            { key: 'detecteurGazNaturelLieu', label: 'Localisation detecteur gaz naturel', type: 'text' },
            { key: 'detecteurPropane', label: 'Detecteur propane (C3H8)', type: 'boolean' },
            { key: 'detecteurAmmoniac', label: 'Detecteur ammoniac (NH3)', type: 'boolean' },
            { key: 'detecteurAmmoniacSeuil1', label: 'Seuil alarme minimal NH3 (ppm)', type: 'number' },
            { key: 'detecteurAmmoniacSeuil2', label: 'Seuil alarme maximal NH3 (ppm)', type: 'number' },
            { key: 'detecteurFreon', label: 'Detecteur freon / refrigerant', type: 'boolean' },
            { key: 'detecteurO2', label: 'Detecteur oxygene (O2)', type: 'boolean' },
            { key: 'detecteurFM200', label: 'Detecteur FM200', type: 'boolean' },
            { key: 'detecteurCO2', label: 'Detecteur CO2', type: 'boolean' },
          ],
        },
        {
          id: 'matieres',
          title: 'Matieres dangereuses',
          icon: '⚠️',
          fields: [
            { key: 'matieresDangereuses', label: 'Matieres dangereuses presentes dans le batiment', type: 'boolean' },
            {
              key: 'matieresList',
              label: 'Liste des matieres dangereuses (ajouter chaque matiere)',
              type: 'dynamic_list',
              schema: [
                { key: 'nom', label: 'Nom du produit', type: 'text' },
                { key: 'numeroUN', label: 'Numero UN (ex: UN1202)', type: 'text' },
                { key: 'quantiteEmplacement', label: 'Quantite et emplacement', type: 'text' },
                { key: 'tmd', label: 'Soumis au TMD', type: 'boolean' },
                { key: 'simdut', label: 'Soumis au SIMDUT', type: 'boolean' },
              ],
            },
            { key: 'ammoniac', label: 'Ammoniac (NH3) present - CRITIQUE', type: 'boolean' },
            { key: 'batteriesLithium', label: 'Batteries lithium-ion presentes', type: 'boolean' },
            { key: 'trousseDeversement', label: 'Trousse de deversement presente', type: 'boolean' },
            {
              key: 'trousseDeversementListe',
              label: 'Emplacements des trousses de deversement (ajouter)',
              type: 'dynamic_list',
              schema: [
                { key: 'lieu', label: 'Emplacement', type: 'text' },
              ],
            },
          ],
        },
        {
          id: 'premiers_soins',
          title: 'Equipements premiers soins',
          icon: '🏥',
          fields: [
            {
              key: 'equipementsSoins',
              label: 'Equipements de premiers soins (ajouter chaque equipement)',
              type: 'dynamic_list',
              schema: [
                { key: 'type', label: 'Type d equipement', type: 'select',
                  options: ['Trousse de premiers soins', 'Defibrillateur (DEA)', 'Douche oculaire', 'Douche d urgence corps', 'Civiere', 'Oxygene medical', 'Autre'] },
                { key: 'lieu', label: 'Localisation', type: 'text' },
                { key: 'quantite', label: 'Quantite', type: 'number' },
              ],
            },
          ],
        },
        {
          id: 'industriel',
          title: 'Specifique industriel',
          icon: '🏭',
          fields: [
            { key: 'espaceClos', label: 'Espaces clos presents', type: 'boolean' },
            { key: 'espaceClosLieu', label: 'Localisation espaces clos', type: 'text' },
            { key: 'chariotsElevateurs', label: 'Chariots elevateurs presents', type: 'boolean' },
            { key: 'chariotsElevateursBatterie', label: 'Chariots sur batterie (recharge)', type: 'boolean' },
            { key: 'chariotsElevateursLieu', label: 'Zone recharge chariots', type: 'text' },
            { key: 'palettiers', label: 'Palettiers / racks d entreposage', type: 'boolean' },
            { key: 'mezzanine', label: 'Mezzanine presente', type: 'boolean' },
            { key: 'mezzanineLieu', label: 'Localisation mezzanine', type: 'text' },
            { key: 'travailChaud', label: 'Travaux a chaud effectues', type: 'boolean' },
            { key: 'procesDangereux', label: 'Procedes dangereux presents', type: 'boolean' },
            { key: 'procesDangereuxDesc', label: 'Description procedes dangereux', type: 'text' },
            { key: 'systemeCadenassage', label: 'Programme de cadenassage en place', type: 'boolean' },
          ],
        },
        {
          id: 'historique',
          title: 'Historique des mises a jour',
          icon: '📅',
          fields: [
            {
              key: 'historiqueList',
              label: 'Journal des modifications du document (ajouter chaque mise a jour)',
              type: 'dynamic_list',
              schema: [
                { key: 'date', label: 'Date du releve / de la mise a jour', type: 'date' },
                { key: 'type', label: 'Type de mise a jour', type: 'select',
                  options: ['Creation initiale', 'Mise a jour annuelle', 'Mise a jour suite a incident', 'Mise a jour suite a renovation', 'Mise a jour suite a changement occupation'] },
                { key: 'responsable', label: 'Personne responsable', type: 'text' },
              ],
            },
          ],
        },
        ],
    };
  }
}