import type { Metadata } from 'next';
import { Mail, MapPin, Phone } from 'lucide-react';
import DemoForm from '@/app/DemoForm';
import { SiteFooter } from '@/components/site/SiteFooter';
import { SiteHeader } from '@/components/site/SiteHeader';
import { Container } from '@/components/ui/Container';
import { Section } from '@/components/ui/Section';
import { localeFromSearchParams } from '@/lib/site/locale';
import { buildPageMetadata } from '@/lib/site/seo';
import styles from '../institutional.module.css';
type Props={searchParams?:Promise<Record<string,string|string[]|undefined>>};
const copy={fr:{title:'Contactez CORO',description:'Communiquez avec CORO pour poser une question, discuter de vos besoins ou demander une démonstration.',h1:'Parlons de vos besoins.',intro:'Vous souhaitez découvrir CORO, discuter d’un besoin précis ou demander une démonstration? Écrivez-nous ou utilisez le formulaire.',form:'Demander une démonstration',formText:'Présentez-nous brièvement votre organisation et votre besoin.',email:'Courriel',phone:'Téléphone',address:'Adresse'},en:{title:'Contact CORO',description:'Contact CORO to ask a question, discuss your needs or request a platform demonstration.',h1:'Let’s discuss your needs.',intro:'Would you like to discover CORO, discuss a specific need or request a demonstration? Email us or use the form.',form:'Request a demonstration',formText:'Tell us briefly about your organization and your needs.',email:'Email',phone:'Phone',address:'Address'}} as const;
export async function generateMetadata({searchParams}:Props):Promise<Metadata>{const locale=localeFromSearchParams((await searchParams)??{});return buildPageMetadata({path:'/contact',locale,title:copy[locale].title,description:copy[locale].description});}
export default async function Page({searchParams}:Props){const locale=localeFromSearchParams((await searchParams)??{}),t=copy[locale];return <div className={styles.pageShell}><SiteHeader locale={locale} pathname="/contact"/><main id="main-content"><section className={`${styles.hero} ${styles.contactHero}`}><Container><p className={styles.eyebrow}>Contact</p><h1>{t.h1}</h1><p className={styles.heroText}>{t.intro}</p></Container></section><Section className={styles.contactSection}><Container className={styles.contactGrid}><div className={styles.contactPanel}><p className={styles.eyebrow}>CORO</p><h2>{locale==='fr'?'Communiquez avec nous':'Contact us'}</h2><p className={styles.contactLead}>{locale==='fr'?'Choisissez le moyen qui vous convient pour amorcer la conversation.':'Choose the channel that works for you to start the conversation.'}</p><ul className={styles.contactList}><li><Mail aria-hidden="true"/><div><span>{t.email}</span><a href="mailto:info@getcoro.io">info@getcoro.io</a></div></li><li><Phone aria-hidden="true"/><div><span>{t.phone}</span><a href="tel:+15147917871">+1 (514) 791-7871</a></div></li><li><MapPin aria-hidden="true"/><div><span>{t.address}</span><strong><span>2879, boul. Pierre-Bernard</span><span>Montréal (Québec) <span className={styles.nowrap}>H1L 4R2</span></span><span>Canada</span></strong></div></li></ul></div><section className={styles.formPanel} aria-labelledby="form-title"><h2 id="form-title">{t.form}</h2><p>{t.formText}</p><DemoForm lang={locale}/></section></Container></Section></main><SiteFooter locale={locale} pathname="/contact"/></div>}
