CREATE TYPE "EntitlementSource" AS ENUM ('CONTRACT','DISTRIBUTION','MANUAL_OVERRIDE','TRIAL','INTERNAL');
CREATE TYPE "EntitlementLifecycle" AS ENUM ('GRANTED','SUSPENDED','REVOKED');
CREATE TYPE "EntitlementLimitType" AS ENUM ('SEATS','CLIENTS','SITES','USAGE');

CREATE UNIQUE INDEX "Client_id_organizationId_key" ON "Client"("id","organizationId");
CREATE UNIQUE INDEX "Building_id_clientId_organizationId_key" ON "Building"("id","clientId","organizationId");
CREATE UNIQUE INDEX "OrganizationContract_id_organizationId_key" ON "OrganizationContract"("id","organizationId");
CREATE UNIQUE INDEX "OrganizationContractRevision_id_contractId_key" ON "OrganizationContractRevision"("id","contractId");
CREATE UNIQUE INDEX "ContractPriceSnapshotLine_id_contractRevisionId_key" ON "ContractPriceSnapshotLine"("id","contractRevisionId");

CREATE TABLE "CapabilityEntitlement" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"capabilityId" TEXT NOT NULL,"scope" "CommercialScope" NOT NULL,"clientId" TEXT,"buildingId" TEXT,"source" "EntitlementSource" NOT NULL,"parentEntitlementId" TEXT,"sourceContractId" TEXT,"sourceContractRevisionId" TEXT,"sourceSnapshotLineId" TEXT,"provenanceReason" TEXT,"lockVersion" INTEGER NOT NULL DEFAULT 0,"createdByUserId" TEXT,"createdByDisplayName" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT "CapabilityEntitlement_target_check" CHECK (("scope"='ORGANIZATION' AND "clientId" IS NULL AND "buildingId" IS NULL) OR ("scope"='CLIENT' AND "clientId" IS NOT NULL AND "buildingId" IS NULL) OR ("scope"='SITE' AND "clientId" IS NOT NULL AND "buildingId" IS NOT NULL)),
CONSTRAINT "CapabilityEntitlement_provenance_check" CHECK (("source"='CONTRACT' AND "parentEntitlementId" IS NULL AND "sourceContractId" IS NOT NULL AND "sourceContractRevisionId" IS NOT NULL AND ("sourceSnapshotLineId" IS NOT NULL OR NULLIF(BTRIM("provenanceReason"),'') IS NOT NULL)) OR ("source"='DISTRIBUTION' AND "parentEntitlementId" IS NOT NULL AND "sourceContractId" IS NULL AND "sourceContractRevisionId" IS NULL AND "sourceSnapshotLineId" IS NULL) OR ("source" IN ('MANUAL_OVERRIDE','TRIAL','INTERNAL') AND "parentEntitlementId" IS NULL AND "sourceContractId" IS NULL AND "sourceContractRevisionId" IS NULL AND "sourceSnapshotLineId" IS NULL AND NULLIF(BTRIM("provenanceReason"),'') IS NOT NULL)));
CREATE TABLE "CapabilityEntitlementRevision" ("id" TEXT PRIMARY KEY,"entitlementId" TEXT NOT NULL,"versionNumber" INTEGER NOT NULL,"lifecycle" "EntitlementLifecycle" NOT NULL,"enabled" BOOLEAN NOT NULL,"distributable" BOOLEAN NOT NULL,"decisionAt" TIMESTAMP(3) NOT NULL,"effectiveFrom" TIMESTAMP(3) NOT NULL,"effectiveUntil" TIMESTAMP(3),"reason" TEXT NOT NULL,"createdByUserId" TEXT,"createdByDisplayName" TEXT,"recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CapabilityEntitlementRevision_dates_check" CHECK ("effectiveUntil" IS NULL OR "effectiveUntil">"effectiveFrom"),CONSTRAINT "CapabilityEntitlementRevision_reason_check" CHECK (NULLIF(BTRIM("reason"),'') IS NOT NULL));
CREATE TABLE "CapabilityEntitlementLimit" ("id" TEXT PRIMARY KEY,"entitlementRevisionId" TEXT NOT NULL,"type" "EntitlementLimitType" NOT NULL,"metricCode" TEXT NOT NULL DEFAULT 'DEFAULT',"quantity" DECIMAL(20,6),"unlimited" BOOLEAN NOT NULL DEFAULT false,"periodStart" TIMESTAMP(3),"periodEnd" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CapabilityEntitlementLimit_value_check" CHECK (("unlimited" AND "quantity" IS NULL) OR (NOT "unlimited" AND "quantity" IS NOT NULL AND "quantity">=0)),CONSTRAINT "CapabilityEntitlementLimit_period_check" CHECK ("periodEnd" IS NULL OR ("periodStart" IS NOT NULL AND "periodEnd">"periodStart")));

CREATE UNIQUE INDEX "CapabilityEntitlement_id_organizationId_capabilityId_key" ON "CapabilityEntitlement"("id","organizationId","capabilityId");
CREATE INDEX "CapabilityEntitlement_organizationId_capabilityId_scope_idx" ON "CapabilityEntitlement"("organizationId","capabilityId","scope"); CREATE INDEX "CapabilityEntitlement_clientId_capabilityId_idx" ON "CapabilityEntitlement"("clientId","capabilityId"); CREATE INDEX "CapabilityEntitlement_buildingId_capabilityId_idx" ON "CapabilityEntitlement"("buildingId","capabilityId"); CREATE INDEX "CapabilityEntitlement_parentEntitlementId_idx" ON "CapabilityEntitlement"("parentEntitlementId"); CREATE INDEX "CapabilityEntitlement_sourceContractId_idx" ON "CapabilityEntitlement"("sourceContractId"); CREATE INDEX "CapabilityEntitlement_sourceContractRevisionId_idx" ON "CapabilityEntitlement"("sourceContractRevisionId"); CREATE INDEX "CapabilityEntitlement_sourceSnapshotLineId_idx" ON "CapabilityEntitlement"("sourceSnapshotLineId"); CREATE INDEX "CapabilityEntitlement_source_createdAt_idx" ON "CapabilityEntitlement"("source","createdAt");
CREATE UNIQUE INDEX "CapabilityEntitlementRevision_entitlementId_versionNumber_key" ON "CapabilityEntitlementRevision"("entitlementId","versionNumber"); CREATE INDEX "CapabilityEntitlementRevision_entitlementId_effectiveFrom_v_idx" ON "CapabilityEntitlementRevision"("entitlementId","effectiveFrom","versionNumber"); CREATE INDEX "CapabilityEntitlementRevision_entitlementId_recordedAt_idx" ON "CapabilityEntitlementRevision"("entitlementId","recordedAt"); CREATE INDEX "CapabilityEntitlementRevision_lifecycle_effectiveFrom_effec_idx" ON "CapabilityEntitlementRevision"("lifecycle","effectiveFrom","effectiveUntil");
CREATE UNIQUE INDEX "CapabilityEntitlementLimit_entitlementRevisionId_type_metri_key" ON "CapabilityEntitlementLimit"("entitlementRevisionId","type","metricCode"); CREATE INDEX "CapabilityEntitlementLimit_type_metricCode_idx" ON "CapabilityEntitlementLimit"("type","metricCode");

ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_capabilityId_fkey" FOREIGN KEY ("capabilityId") REFERENCES "CommercialCapability"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_clientId_organizationId_fkey" FOREIGN KEY ("clientId","organizationId") REFERENCES "Client"("id","organizationId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_buildingId_clientId_organizationId_fkey" FOREIGN KEY ("buildingId","clientId","organizationId") REFERENCES "Building"("id","clientId","organizationId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_parentEntitlementId_organizationId_c_fkey" FOREIGN KEY ("parentEntitlementId","organizationId","capabilityId") REFERENCES "CapabilityEntitlement"("id","organizationId","capabilityId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_sourceContractId_organizationId_fkey" FOREIGN KEY ("sourceContractId","organizationId") REFERENCES "OrganizationContract"("id","organizationId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_sourceContractRevisionId_sourceContr_fkey" FOREIGN KEY ("sourceContractRevisionId","sourceContractId") REFERENCES "OrganizationContractRevision"("id","contractId") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_sourceSnapshotLineId_sourceContractR_fkey" FOREIGN KEY ("sourceSnapshotLineId","sourceContractRevisionId") REFERENCES "ContractPriceSnapshotLine"("id","contractRevisionId") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CapabilityEntitlement" ADD CONSTRAINT "CapabilityEntitlement_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlementRevision" ADD CONSTRAINT "CapabilityEntitlementRevision_entitlementId_fkey" FOREIGN KEY ("entitlementId") REFERENCES "CapabilityEntitlement"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlementRevision" ADD CONSTRAINT "CapabilityEntitlementRevision_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "CapabilityEntitlementLimit" ADD CONSTRAINT "CapabilityEntitlementLimit_entitlementRevisionId_fkey" FOREIGN KEY ("entitlementRevisionId") REFERENCES "CapabilityEntitlementRevision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE FUNCTION protect_entitlement_identity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Capability entitlements cannot be deleted'; END IF; IF (to_jsonb(NEW)-'lockVersion') IS DISTINCT FROM (to_jsonb(OLD)-'lockVersion') THEN RAISE EXCEPTION 'Entitlement identity and provenance are immutable'; END IF; IF NEW."lockVersion"<>OLD."lockVersion"+1 THEN RAISE EXCEPTION 'Invalid entitlement lockVersion'; END IF; RETURN NEW; END $$;
CREATE TRIGGER capability_entitlement_immutable BEFORE UPDATE OR DELETE ON "CapabilityEntitlement" FOR EACH ROW EXECUTE FUNCTION protect_entitlement_identity();
CREATE FUNCTION protect_entitlement_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Entitlement history is append-only'; END $$;
CREATE TRIGGER capability_entitlement_revision_append_only BEFORE UPDATE OR DELETE ON "CapabilityEntitlementRevision" FOR EACH ROW EXECUTE FUNCTION protect_entitlement_append_only(); CREATE TRIGGER capability_entitlement_limit_immutable BEFORE UPDATE OR DELETE ON "CapabilityEntitlementLimit" FOR EACH ROW EXECUTE FUNCTION protect_entitlement_append_only();
CREATE FUNCTION validate_entitlement_limit_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS (SELECT 1 FROM "CapabilityEntitlementRevision" WHERE "id"=NEW."entitlementRevisionId" AND xmin::text::bigint=txid_current()) THEN RAISE EXCEPTION 'Entitlement limits must be created with their revision'; END IF; RETURN NEW; END $$;
CREATE TRIGGER capability_entitlement_limit_same_transaction BEFORE INSERT ON "CapabilityEntitlementLimit" FOR EACH ROW EXECUTE FUNCTION validate_entitlement_limit_insert();

CREATE FUNCTION validate_entitlement_grant() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE available BOOLEAN; life "CapabilityLifecycle"; policy "CapabilityScopeStatus"; rel "CommercialRelationship"; pscope "CommercialScope"; rstatus "ContractRevisionStatus"; scap TEXT; BEGIN SELECT "isAvailable","lifecycle" INTO available,life FROM "CommercialCapability" WHERE "id"=NEW."capabilityId"; IF NOT available OR life='RETIRED' THEN RAISE EXCEPTION 'Capability unavailable for new entitlement'; END IF; SELECT "status" INTO policy FROM "CapabilityScopePolicy" WHERE "capabilityId"=NEW."capabilityId" AND "scope"=NEW."scope"; IF policy IS DISTINCT FROM 'ALLOWED' THEN RAISE EXCEPTION 'Capability scope is not allowed'; END IF; IF NEW."source"='CONTRACT' THEN SELECT "status" INTO rstatus FROM "OrganizationContractRevision" WHERE "id"=NEW."sourceContractRevisionId"; IF rstatus IS DISTINCT FROM 'SIGNED' THEN RAISE EXCEPTION 'Contract revision must be signed'; END IF; IF NEW."sourceSnapshotLineId" IS NOT NULL THEN SELECT "capabilityId" INTO scap FROM "ContractPriceSnapshotLine" WHERE "id"=NEW."sourceSnapshotLineId"; IF scap IS DISTINCT FROM NEW."capabilityId" THEN RAISE EXCEPTION 'Snapshot capability mismatch'; END IF; END IF; ELSIF NEW."source"='DISTRIBUTION' THEN SELECT e."scope",o."commercialRelationship" INTO pscope,rel FROM "CapabilityEntitlement" e JOIN "Organization" o ON o."id"=e."organizationId" WHERE e."id"=NEW."parentEntitlementId"; IF pscope IS DISTINCT FROM 'ORGANIZATION' OR rel IS DISTINCT FROM 'PARTNER' THEN RAISE EXCEPTION 'Distribution requires Partner organization entitlement'; END IF; ELSIF NEW."source"='INTERNAL' THEN SELECT "commercialRelationship" INTO rel FROM "Organization" WHERE "id"=NEW."organizationId"; IF rel IS DISTINCT FROM 'INTERNAL' THEN RAISE EXCEPTION 'Internal entitlement requires INTERNAL organization'; END IF; END IF; RETURN NEW; END $$;
CREATE TRIGGER capability_entitlement_validate BEFORE INSERT ON "CapabilityEntitlement" FOR EACH ROW EXECUTE FUNCTION validate_entitlement_grant();
CREATE FUNCTION validate_entitlement_revision() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE escope "CommercialScope"; rel "CommercialRelationship"; revoked BOOLEAN; BEGIN SELECT e."scope",o."commercialRelationship" INTO escope,rel FROM "CapabilityEntitlement" e JOIN "Organization" o ON o."id"=e."organizationId" WHERE e."id"=NEW."entitlementId"; IF NEW."distributable" AND (escope<>'ORGANIZATION' OR rel IS DISTINCT FROM 'PARTNER') THEN RAISE EXCEPTION 'Distributable requires Partner organization entitlement'; END IF; SELECT EXISTS(SELECT 1 FROM "CapabilityEntitlementRevision" WHERE "entitlementId"=NEW."entitlementId" AND "lifecycle"='REVOKED') INTO revoked; IF revoked THEN RAISE EXCEPTION 'Revoked entitlement cannot receive revisions'; END IF; RETURN NEW; END $$;
CREATE TRIGGER capability_entitlement_revision_validate BEFORE INSERT ON "CapabilityEntitlementRevision" FOR EACH ROW EXECUTE FUNCTION validate_entitlement_revision();
