import type { Locale } from '@/lib/site/locale';

type Pair = readonly [source: string, destination: string];
type LifecycleStage = { readonly phase: string; readonly title: string; readonly text: string; readonly capabilities: readonly string[] };
export type AboutContent = {
  readonly metadata: { readonly title: string; readonly description: string };
  readonly hero: { readonly eyebrow: string; readonly title: string; readonly intro: string; readonly detail: string; readonly signature: string; readonly primary: string; readonly secondary: string };
  readonly why: { readonly eyebrow: string; readonly title: string; readonly paragraphs: readonly string[]; readonly sequence: readonly string[]; readonly conclusion: string };
  readonly evolution: { readonly eyebrow: string; readonly title: string; readonly text: string; readonly path: readonly string[]; readonly note: string };
  readonly identity: { readonly eyebrow: string; readonly title: string; readonly cards: readonly { readonly code: 'CO' | 'RO'; readonly title: string; readonly text: string }[]; readonly conclusion: string };
  readonly vision: { readonly eyebrow: string; readonly title: string; readonly text: string; readonly detail: string };
  readonly continuum: { readonly eyebrow: string; readonly title: string; readonly steps: readonly string[] };
  readonly data: { readonly eyebrow: string; readonly title: string; readonly text: string; readonly flows: readonly Pair[] };
  readonly lifecycle: { readonly eyebrow: string; readonly title: string; readonly note: string; readonly stages: readonly LifecycleStage[] };
  readonly human: { readonly eyebrow: string; readonly title: string; readonly text: string; readonly responsibility: string };
  readonly network: { readonly eyebrow: string; readonly title: string; readonly text: string; readonly levels: readonly string[]; readonly note: string };
  readonly canada: { readonly eyebrow: string; readonly title: string; readonly text: string; readonly caution: string };
  readonly cta: { readonly title: string; readonly text: string; readonly primary: string; readonly secondary: string };
};

const fr: AboutContent = {
  metadata: { title: 'CORO · Conformité opérationnelle et résilience organisationnelle', description: 'Découvrez CORO, la plateforme canadienne qui relie conformité opérationnelle, résilience organisationnelle et mesures d’urgence dans un même écosystème.' },
  hero: { eyebrow: 'À propos de CORO', title: 'Conçue par le terrain.\nPensée pour les professionnels.', intro: 'CORO — Conformité Opérationnelle et Résilience Organisationnelle — est une plateforme canadienne conçue pour relier, dans un même environnement numérique, les bâtiments, les personnes, les plans, les procédures, les systèmes et les incidents.', detail: 'Son objectif est de créer une continuité entre la préparation, la connaissance de l’environnement, la décision, l’intervention, la preuve et l’amélioration continue — tout en maintenant l’expertise humaine au centre des décisions.', signature: 'Résilience · Conformité · Action', primary: 'Découvrir la vision', secondary: 'Demander une démo' },
  why: { eyebrow: 'Pourquoi CORO', title: 'Une plateforme née d’un besoin concret', paragraphs: ['Dans les mesures d’urgence, la sécurité incendie, la continuité et la résilience organisationnelle, l’information existe souvent, mais demeure fragmentée entre les plans, les procédures, les plans techniques, les contacts, l’occupation, les exercices, les incidents, les actions correctives, les données du bâtiment et les systèmes.', 'Lorsqu’un événement survient, posséder un document n’est pas suffisant. L’information doit soutenir une action coordonnée au moment où elle compte.'], sequence: ['Retrouver', 'Comprendre', 'Mobiliser', 'Appliquer', 'Coordonner', 'Prouver', 'Apprendre'], conclusion: 'CORO est née de cette réalité.' },
  evolution: { eyebrow: 'Notre évolution', title: 'Du document à la résilience opérationnelle', text: 'CORO a d’abord été conçue pour structurer et moderniser la production documentaire. Sa trajectoire s’étend progressivement vers un environnement capable d’accompagner une organisation avant, pendant et après un événement.', path: ['Documents', 'Bâtiments', 'Personnes', 'Occupation', 'Exercices', 'Incidents', 'Connaissance', 'Opérations', 'Amélioration'], note: 'Cette trajectoire réunit des capacités actuelles, en développement et envisagées; elle ne signifie pas que chaque capacité est déjà disponible.' },
  identity: { eyebrow: 'Pourquoi le nom CORO', title: 'Conformité Opérationnelle + Résilience Organisationnelle', cards: [{ code: 'CO', title: 'Conformité Opérationnelle', text: 'Plans, exigences, procédures, responsabilités, qualifications, preuves, traçabilité, maintien à jour et actions correctives. La conformité ne consiste pas uniquement à posséder un document : l’information nécessaire doit pouvoir soutenir les opérations.' }, { code: 'RO', title: 'Résilience Organisationnelle', text: 'La capacité de connaître son environnement, anticiper, préparer, détecter, décider, agir, protéger, apprendre et améliorer lorsque les conditions changent.' }], conclusion: 'CORO relie les deux. Une organisation réellement résiliente ne se limite pas à démontrer sa conformité; une conformité réellement opérationnelle doit soutenir l’action lorsque la situation l’exige.' },
  vision: { eyebrow: 'Notre vision', title: 'Le système d’exploitation de la résilience organisationnelle', text: 'Cette expression décrit la vision cible de CORO, et non une affirmation que toutes les capacités sont entièrement réalisées aujourd’hui.', detail: 'CORO vise à devenir un environnement connecté où les mêmes informations servent à préparer, comprendre, décider, intervenir, prouver et améliorer — plutôt qu’une collection d’outils indépendants.' },
  continuum: { eyebrow: 'Continuum CORO', title: 'Une continuité avant, pendant et après l’événement', steps: ['Connaître', 'Anticiper', 'Détecter', 'Décider', 'Agir', 'Protéger', 'Prouver', 'Apprendre', 'Améliorer'] },
  data: { eyebrow: 'Notre principe', title: 'Même donnée. Plusieurs usages. Une continuité opérationnelle.', text: 'CORO vise progressivement à permettre qu’une information structurée serve à plusieurs moments du cycle opérationnel, sans promettre une automatisation complète de chaque relation.', flows: [['Bâtiment', 'Document'], ['Procédure', 'Intervention'], ['Occupation', 'Évacuation'], ['Incident', 'REX'], ['REX', 'Action corrective'], ['Action corrective', 'Amélioration']] },
  lifecycle: { eyebrow: 'Avant · Pendant · Après', title: 'Un écosystème pensé dans le temps', note: 'Ces ensembles représentent l’écosystème et sa trajectoire. Ils regroupent des capacités existantes, en développement et futures, sans constituer une annonce de disponibilité.', stages: [{ phase: 'Avant', title: 'Préparer et comprendre', text: 'Structurer la connaissance et la préparation.', capabilities: ['Documents', 'Knowledge', 'Projects', 'Résilience', 'Exercices', 'Sentinelle'] }, { phase: 'Pendant', title: 'Comprendre et agir', text: 'Mettre le contexte utile au service de la décision et de l’intervention.', capabilities: ['Sentinelle', 'Incident', 'Ops', 'AI', 'Building Bridge', 'QR Intervention'] }, { phase: 'Après', title: 'Prouver et améliorer', text: 'Conserver la trace, apprendre et suivre l’amélioration.', capabilities: ['Journal', 'Rapports', 'REX', 'Actions correctives', 'Performance', 'Indice CORO', 'Network'] }] },
  human: { eyebrow: 'L’humain au centre', title: 'L’intelligence augmente la capacité. Elle ne remplace pas la responsabilité.', text: 'CORO peut progressivement aider à structurer, rechercher et contextualiser l’information, soutenir une recommandation et orchestrer certaines tâches.', responsibility: 'Les décisions sensibles demeurent sous contrôle humain. La plateforme soutient les coordonnateurs, conseillers, gestionnaires, équipes d’urgence et intervenants sans se substituer à leur jugement.' },
  network: { eyebrow: 'Du bâtiment au réseau', title: 'Bâtiment → Portefeuille → Organisation', text: 'CORO est conçue pour comprendre un bâtiment dans son contexte, puis permettre progressivement une vue consolidée de l’état documentaire, de la préparation, de l’occupation, des incidents, des actions ouvertes, des indicateurs et des tendances.', levels: ['Bâtiment', 'Portefeuille', 'Organisation'], note: 'Dans cette vision, CORO Network représente un pilotage transversal entre bâtiments, portefeuilles et organisations — pas simplement une carte multi-sites.' },
  canada: { eyebrow: 'Une plateforme canadienne', title: 'Conçue au Canada. Pensée pour les réalités du terrain.', text: 'CORO est développée au Canada à partir d’une expérience concrète en mesures d’urgence, sécurité incendie, continuité et résilience organisationnelle.', caution: 'Elle vise à soutenir les réalités opérationnelles et l’intégration progressive des exigences applicables. CORO ne rend pas une organisation automatiquement conforme.' },
  cta: { title: 'Construisons une résilience qui fonctionne dans la réalité.', text: 'Découvrez comment CORO peut relier la préparation, l’information et l’action dans votre organisation.', primary: 'Demander une démo', secondary: 'Découvrir la plateforme' },
};

const en: AboutContent = {
  metadata: { title: 'CORO · Operational Compliance and Organizational Resilience', description: 'Discover CORO, the Canadian platform connecting operational compliance, organizational resilience and emergency management in one ecosystem.' },
  hero: { eyebrow: 'About CORO', title: 'Built from the field.\nDesigned for professionals.', intro: 'CORO takes its name from the French concepts “Conformité Opérationnelle” and “Résilience Organisationnelle” — Operational Compliance and Organizational Resilience. It connects buildings, people, plans, procedures, systems and incidents in one Canadian digital environment.', detail: 'Its purpose is to create continuity between preparedness, situational knowledge, decision-making, response, evidence and continuous improvement — while keeping human expertise at the center of every decision.', signature: 'Resilience · Compliance · Action', primary: 'Explore the vision', secondary: 'Request a demo' },
  why: { eyebrow: 'Why CORO', title: 'A platform born from a concrete need', paragraphs: ['Across emergency management, fire safety, continuity and organizational resilience, information often exists but remains fragmented across plans, procedures, technical drawings, contacts, occupancy, exercises, incidents, corrective actions, building data and operational systems.', 'When an event occurs, having a document is not enough. Information must support coordinated action when it matters.'], sequence: ['Find', 'Understand', 'Mobilize', 'Apply', 'Coordinate', 'Prove', 'Learn'], conclusion: 'CORO was born from this reality.' },
  evolution: { eyebrow: 'Our evolution', title: 'From documents to operational resilience', text: 'CORO was first designed to structure and modernize document production. Its trajectory is progressively expanding into an environment that can support an organization before, during and after an event.', path: ['Documents', 'Buildings', 'People', 'Occupancy', 'Exercises', 'Incidents', 'Knowledge', 'Operations', 'Improvement'], note: 'This trajectory combines current, in-development and envisioned capabilities; it does not mean every capability is already available.' },
  identity: { eyebrow: 'Why the name CORO', title: 'Operational Compliance + Organizational Resilience', cards: [{ code: 'CO', title: 'Operational Compliance', text: 'Plans, requirements, procedures, responsibilities, qualifications, evidence, traceability, maintenance and corrective actions. Compliance is not merely about having a document: the required information must support operations.' }, { code: 'RO', title: 'Organizational Resilience', text: 'The ability to understand the environment, anticipate, prepare, detect, decide, act, protect, learn and improve as conditions change.' }], conclusion: 'CORO connects both. A truly resilient organization does more than demonstrate compliance; truly operational compliance must support action when the situation demands it.' },
  vision: { eyebrow: 'Our vision', title: 'The operating system for organizational resilience', text: 'This expression describes CORO’s target vision, not a claim that every capability is fully realized today.', detail: 'CORO aims to become a connected environment where the same information supports preparation, understanding, decisions, response, evidence and improvement — rather than a collection of independent tools.' },
  continuum: { eyebrow: 'The CORO continuum', title: 'Continuity before, during and after an event', steps: ['Know', 'Anticipate', 'Detect', 'Decide', 'Act', 'Protect', 'Prove', 'Learn', 'Improve'] },
  data: { eyebrow: 'Our principle', title: 'One source of data. Multiple uses. Operational continuity.', text: 'CORO progressively aims to make structured information useful at several points in the operational cycle, without promising complete automation for every relationship.', flows: [['Building', 'Document'], ['Procedure', 'Response'], ['Occupancy', 'Evacuation'], ['Incident', 'After-action review'], ['After-action review', 'Corrective action'], ['Corrective action', 'Improvement']] },
  lifecycle: { eyebrow: 'Before · During · After', title: 'An ecosystem designed across time', note: 'These groups represent the ecosystem and its trajectory. They combine existing, in-development and future capabilities and are not a statement of availability.', stages: [{ phase: 'Before', title: 'Prepare and understand', text: 'Structure knowledge and preparedness.', capabilities: ['Documents', 'Knowledge', 'Projects', 'Resilience', 'Exercises', 'Sentinelle'] }, { phase: 'During', title: 'Understand and act', text: 'Put useful context at the service of decisions and response.', capabilities: ['Sentinelle', 'Incident', 'Ops', 'AI', 'Building Bridge', 'QR Intervention'] }, { phase: 'After', title: 'Prove and improve', text: 'Preserve the record, learn and track improvement.', capabilities: ['Operational log', 'Reports', 'After-action reviews', 'Corrective actions', 'Performance', 'CORO Index', 'Network'] }] },
  human: { eyebrow: 'People at the center', title: 'Intelligence expands capability. It does not replace accountability.', text: 'CORO can progressively help structure, retrieve and contextualize information, support recommendations and orchestrate selected tasks.', responsibility: 'Sensitive decisions remain under human control. The platform supports coordinators, advisors, managers, emergency teams and responders without replacing their judgment.' },
  network: { eyebrow: 'From building to network', title: 'Building → Portfolio → Organization', text: 'CORO is designed to understand a building in context, then progressively enable a consolidated view of document status, preparedness, occupancy, incidents, open actions, indicators and trends.', levels: ['Building', 'Portfolio', 'Organization'], note: 'In this vision, CORO Network represents cross-organizational management across buildings, portfolios and organizations — not simply a multi-site map.' },
  canada: { eyebrow: 'A Canadian platform', title: 'Built in Canada. Designed for field realities.', text: 'CORO is developed in Canada from hands-on experience in emergency management, fire safety, business continuity and organizational resilience.', caution: 'It aims to support operational realities and the progressive integration of applicable requirements. CORO does not make an organization automatically compliant.' },
  cta: { title: 'Build resilience that works in the real world.', text: 'See how CORO can connect preparedness, information and action across your organization.', primary: 'Request a demo', secondary: 'Explore the platform' },
};

export const aboutContent: Record<Locale, AboutContent> = { fr, en };
