"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import AppLayout from "@/components/layout/AppLayout";
import api from "@/lib/api";

type Kind="cost"|"valuation"; type Value={assumptionCode:string;assumptionVersion:string;scopeKey:string;valueType:string;decimalValue?:string;moneyMinorValue?:string;currency?:string;unit?:string};
type Version={id:string;versionNumber:number;status:"DRAFT"|"PUBLISHED"|"ARCHIVED";methodologyVersion:string;methodologyCode?:string;values:Value[]};
type SetRow={id:string;code:string;name:string;description?:string;methodologyCode?:string;versions:Version[]};
type ContractDefinition={code:string;version:string;valueType:"MONEY"|"DECIMAL";scope:"COMPONENT_CODE"|"ROLE"|"GLOBAL_OR_COMPONENT"}; type MethodologyContract={methodologyCode:string;methodologyVersion:string;definitions:ContractDefinition[]};
type UiDefinition={code:string;label:string;type:"MONEY"|"DECIMAL";unit:string;scopes:string[][]};
const LABELS:Record<string,[string,string]>={LINE_UNIT_COST_MINOR:["Coût unitaire direct","CAD/unité"],LOADED_DIRECT_DELIVERY_COST:["Coût direct chargé","CAD/heure"],STANDARD_DELIVERY_EFFORT:["Effort standard de livraison","heure"],STANDARD_SENIOR_REVIEW_EFFORT:["Effort standard de revue senior","heure"],STANDARD_SUPPORT_EFFORT:["Effort standard de soutien","heure/période"]};
const VALUE_DEFINITIONS:readonly UiDefinition[]=[{code:"PRODUCTIVITY_GAIN",label:"Gain de productivité approuvé",type:"DECIMAL",unit:"ratio",scopes:[["GLOBAL","Global"]]}];
const toMinor=(v:string)=>{if(!/^\d+(?:\.\d{1,2})?$/.test(v))throw new Error("Montant CAD invalide");const[w,f=""]=v.split(".");return(BigInt(w)*BigInt(100)+BigInt(f.padEnd(2,"0"))).toString()}; const fromMinor=(v?:string)=>v?String(Number(v)/100):"";

export function AssumptionAdmin({kind}:{kind:Kind}){
 const isCost=kind==="cost"; const[sets,setSets]=useState<SetRow[]>([]),[message,setMessage]=useState(""),[setForm,setSetForm]=useState({code:"",name:"",description:"",methodologyCode:isCost?"direct-cost":"proposal-value"}),[selected,setSelected]=useState("");
 const[methodologyVersion,setMethodologyVersion]=useState(isCost?"v2":"v1"),[values,setValues]=useState<Record<string,string>>({}),[contracts,setContracts]=useState<MethodologyContract[]>([]),[componentCodes,setComponentCodes]=useState<string[]>([]);
 const load=useCallback(async()=>{const[r,c,b]=await Promise.all([api.get(`/admin/v1/commercial/simulator/assumptions/${kind}`),isCost?api.get("/admin/v1/commercial/simulator/assumptions/cost/definitions"):Promise.resolve({data:[]}),isCost?api.get("/admin/v1/commercial/price-books"):Promise.resolve({data:[]})]);setSets(r.data);setSelected(s=>s||r.data[0]?.id||"");setContracts(c.data);const books=b.data as Array<{versions:Array<{components:Array<{code:string}>}>}>;setComponentCodes(Array.from(new Set(books.flatMap(book=>book.versions.flatMap(version=>version.components.map(component=>component.code))))).sort())},[isCost,kind]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 const current=sets.find(s=>s.id===selected),draft=current?.versions.find(v=>v.status==="DRAFT");
 const definitions=useMemo<readonly UiDefinition[]>(()=>{if(!isCost)return VALUE_DEFINITIONS;const contract=contracts.find(c=>c.methodologyVersion===methodologyVersion);return(contract?.definitions??[]).map(d=>{const[label,unit]=LABELS[d.code]??[d.code,""];const scopes=d.scope==="COMPONENT_CODE"?componentCodes.map(code=>[code,code]):d.scope==="ROLE"?[["ROLE:DELIVERY_PROFESSIONAL","Professionnel de livraison"],["ROLE:SENIOR_REVIEWER","Réviseur senior"]]:[["GLOBAL","Global"],...componentCodes.map(code=>[`COMPONENT:${code}`,code])];return{code:d.code,label,type:d.valueType,unit,scopes}})},[componentCodes,contracts,isCost,methodologyVersion]);
 const key=(code:string,scope:string)=>`${code}|${scope}`; const payload=useMemo(()=>definitions.flatMap(d=>d.scopes.flatMap(([scope])=>{const raw=values[key(d.code,scope)];if(!raw)return[];return[{assumptionCode:d.code,assumptionVersion:"v1",scopeKey:scope,valueType:d.type,moneyMinorValue:d.type==="MONEY"?toMinor(raw):undefined,decimalValue:d.type==="DECIMAL"?raw:undefined,currency:d.type==="MONEY"?"CAD":undefined,unit:d.unit}]})),[definitions,values]);
 const run=async(t:()=>Promise<unknown>,ok:string)=>{try{await t();await load();setMessage(ok)}catch(e){setMessage((e as{response?:{data?:{message?:string}}}).response?.data?.message??(e as Error).message)}}; const edit=(v:Version)=>{setMethodologyVersion(v.methodologyVersion);const next:Record<string,string>={};v.values.forEach(x=>next[key(x.assumptionCode,x.scopeKey)]=x.valueType==="MONEY"?fromMinor(x.moneyMinorValue):(x.decimalValue??""));setValues(next)};
 return <AppLayout><main className="mx-auto max-w-6xl space-y-6 p-6"><header><h1 className="text-3xl font-semibold">{isCost?"Hypothèses de coûts internes":"Hypothèses de valeur client"}</h1><p className="text-sm text-slate-600">{isCost?"Autorité de coût direct interne — jamais un prix client ni une donnée de paie.":"Méthodologie interne de valeur — aucun benchmark de productivité par défaut."}</p></header>{message&&<p role="status" className="rounded border bg-white p-3">{message}</p>}
 <form onSubmit={e=>{e.preventDefault();void run(()=>api.post(`/admin/v1/commercial/simulator/assumptions/${kind}`,isCost?{code:setForm.code,name:setForm.name,description:setForm.description||undefined}:{code:setForm.code,name:setForm.name,methodologyCode:setForm.methodologyCode}),"Jeu créé.").then(()=>setSetForm({...setForm,code:"",name:"",description:""}))}} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-4"><Field label="Code stable" value={setForm.code} onChange={v=>setSetForm({...setForm,code:v.toUpperCase().replace(/[^A-Z0-9_]/g,"_")})}/><Field label="Nom" value={setForm.name} onChange={v=>setSetForm({...setForm,name:v})}/><Field label={isCost?"Description":"Méthodologie"} value={isCost?setForm.description:setForm.methodologyCode} onChange={v=>setSetForm({...setForm,...(isCost?{description:v}:{methodologyCode:v})})}/><button className="self-end rounded bg-slate-900 p-2 text-white">Créer le jeu</button></form>
 <section className="rounded-xl border bg-white p-5"><label className="text-sm">Jeu d’hypothèses<select value={selected} onChange={e=>setSelected(e.target.value)} className="ml-2 rounded border p-2">{sets.map(s=><option key={s.id} value={s.id}>{s.name} · {s.code}</option>)}</select></label>{isCost&&<label className="ml-4 text-sm">Méthodologie<select value={methodologyVersion} disabled={!!draft} onChange={e=>{setMethodologyVersion(e.target.value);setValues({})}} className="ml-2 rounded border p-2">{contracts.map(c=><option key={c.methodologyVersion} value={c.methodologyVersion}>direct-cost/{c.methodologyVersion}</option>)}</select></label>}{current&&<div className="mt-4"><button disabled={!!draft} onClick={()=>void run(()=>api.post(`/admin/v1/commercial/simulator/assumptions/${kind}/${current.id}/versions`,isCost?{currency:"CAD",methodologyCode:"direct-cost",methodologyVersion,values:[]}:{methodologyVersion,values:[]}),"Brouillon créé.")} className="rounded border px-3 py-2 disabled:opacity-40">Nouvelle version DRAFT</button><div className="mt-4 space-y-2">{current.versions.map(v=><div key={v.id} className="rounded border p-3"><div className="flex justify-between"><b>v{v.versionNumber} · {v.status} · {v.methodologyCode??current.methodologyCode}/{v.methodologyVersion}</b><span>{v.values.length} valeur(s)</span></div>{v.status==="DRAFT"&&<button onClick={()=>edit(v)} className="mt-2 underline">Modifier les valeurs structurées</button>}{v.status==="PUBLISHED"&&<button onClick={()=>void run(()=>api.post(`/admin/v1/commercial/simulator/assumptions/${kind}/versions/${v.id}/archive`,{reason:"Superseded through commercial administration"}),"Version archivée.")} className="mt-2 underline">Archiver</button>}</div>)}</div></div>}</section>
 {draft&&<form onSubmit={(e:FormEvent)=>{e.preventDefault();void run(()=>api.put(`/admin/v1/commercial/simulator/assumptions/${kind}/versions/${draft.id}`,{values:payload,reason:"Structured commercial assumption draft update"}),"Brouillon enregistré.")}} className="rounded-xl border bg-white p-5"><h2 className="text-xl font-semibold">Valeurs du brouillon v{draft.versionNumber} · {draft.methodologyCode??"direct-cost"}/{draft.methodologyVersion}</h2><p className="text-xs text-slate-500">Une valeur absente reste NON CONFIGURÉE; aucun zéro de remplacement.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{definitions.flatMap(d=>d.scopes.map(([scope,label])=><Field key={key(d.code,scope)} label={`${d.label} · ${label} · ${d.unit}`} value={values[key(d.code,scope)]??""} required={false} onChange={v=>setValues({...values,[key(d.code,scope)]:v})}/>))}</div><div className="mt-4 flex gap-2"><button className="rounded bg-slate-900 px-4 py-2 text-white">Enregistrer le brouillon</button><button type="button" disabled={!payload.length} onClick={()=>void run(()=>api.post(`/admin/v1/commercial/simulator/assumptions/${kind}/versions/${draft.id}/publish`,{reason:"Approved commercial assumption publication"}),"Version publiée et immuable.")} className="rounded bg-red-700 px-4 py-2 text-white disabled:opacity-40">Publier après revue</button></div></form>}
 </main></AppLayout>
}
function Field({label,value,onChange,required=true}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="text-sm">{label}<input required={required} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded border p-2"/></label>}
